### ISSUE TITLE
When v0.24.0 release is planned?

### ISSUE THREAD

**Issue by vt-alt** [sigoden/aichat#1002]
I plan to build aichat for ALT Linux, so I'm curios if I should wait for `v0.24.0` release soon or it will be not very soon. Currently, there is `v0.24.0-rc2` tag but since there is no other `-rc` tags it's hard to extrapolate how frequently they are updated.

In case it will not be released anytime soon I should perhaps just build package for `v0.23.0`.

**Comment by sigoden** [comment]
Before November 26

**Comment by vt-alt** [comment]
Thank you!
