### ISSUE TITLE
Example todo / todo-sh agent? Also .starter command is not available

### ISSUE THREAD

**Issue by cmardiros** [sigoden/aichat#1003]
The docs reference a todo agent (sometimes referred to `todo-sh`). The docs also mention a `.starter` command to ` Use the conversation starter` but this doesn't work and there are no agents pre-configured. Are there any examples how to build a simple agent with vars/tools etc? I was hoping I could peak into the config of an existing one.

Thanks

**Comment by sigoden** [comment]
@cmardiros 

see https://github.com/sigoden/llm-functions

**Comment by cmardiros** [comment]
Oh I see, I hadn't realised the docs reference a different repo. Thanks for the clarification
