### ISSUE TITLE
Excluding Tempratures in O1 Models

### ISSUE THREAD

**Issue by sabify** [sigoden/aichat#1004]
O1 models do not support setting temperature. Is it possible to skip adding the temperature field for requests to avoid errors on API requests? Without this, we have to always try to use `.set temperature 1` at the beginning of chats especially when we define it in role files to be used in other models.

```stderr
Error: Failed to call chat-completions api

Caused by:
    Unsupported value: 'temperature' does not support 0.3 with this model. Only the default (1) value is supported. (type: invalid_request_error)
```

**Comment by sigoden** [comment]
We will not support this feature.

o1-* is in beta; it will eventually support all the features like GPT-4o.
Recently, `o1-*` have started to support streaming, and other features will be gradually supported.

You can avoid the above situation through the [patch](https://github.com/sigoden/aichat/wiki/Configuration-Guide#patch-api-request).

**Comment by sabify** [comment]
Thanks for the explanation and maintaining this great project.

I followed the `patch` document, but I couldn't make it work. Here is my configuration:

```yaml
clients:
  - type: openai
    patch:
      chat_completion:
        'o1-.*':
          body:
            temperature: 1
```

Am I missing something here?

**Comment by sabify** [comment]
Ooops! I missed a character in my config. It is working now...
