### ISSUE TITLE
[REPL] Copying the full formatted session

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#1005]
I am trying to copy a full formatted conversation from a REPL session.

What I am trying is to do a `.info session`, which prints out the full formatted session. 
But then when I try `.copy` in order to copy that in the **clipboard**, I get the following error : 

```
.copy
Error: Failed to copy the last response

Caused by:
    No text to copy
```

It might be relevant to be able to copy the whole session this way? Alternatively, a `.copy all` might be a good option, what do you think?

**Comment by sigoden** [comment]
We do not think this will be a common requirement, so we do not plan to support it.

Why not just duplicate the terminal using the mouse and keyboard? It's more versatile.

**Comment by dtrckd** [comment]
Thanks for your suggestion.

Yes, because it's tedious to select and seek back to the starting point of the conversion in a long terminal history.
