### ISSUE TITLE
--session not respected with piped input

### ISSUE THREAD

**Issue by Konfekt** [sigoden/aichat#1006]
#512 /  the fix to #545 threw out the child with the bathwater, even `echo 1 | aichat --session` will no longer show a REPL. Could `-s/--session` be respected regardless of piped input?

**Comment by sigoden** [comment]
This is expect.

**Comment by Konfekt** [comment]
Exactly. Please respect `--session` in this instance as well.

**Comment by Konfekt** [comment]
It used to work, now it's broken

**Comment by Konfekt** [comment]
You can pinpoint to #512 as regression

**Comment by sigoden** [comment]
What does `respect --session` mean? Can you explain it more clearly?

Why not use the [bug issue template](https://github.com/sigoden/aichat/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=)
