### ISSUE TITLE
respect --session unconditonally

### ISSUE THREAD

**Issue by Konfekt** [sigoden/aichat#1007]
**Describe the bug**

`-session` does not start a session if input is piped

**To Reproduce**
`echo 1 | aichat -s`

**Expected behavior**

A session is started

**Configuration**
```
model                   openai:gpt-4o
max_output_tokens       -
temperature             0.2
top_p                   -
dry_run                 false
stream                  true
save                    true
keybindings             emacs
wrap                    auto
wrap_code               false
function_calling        true
use_tools               -
agent_prelude           -
save_session            -
compress_threshold      4000
rag_reranker_model      -
rag_top_k               4
highlight               false
light_theme             true
env_file                /home/konfekt/.config/aichat/.env
config_file             /home/konfekt/.config/aichat/config.yaml
roles_dir               /home/konfekt/.config/aichat/roles
sessions_dir            /home/konfekt/.config/aichat/sessions
rags_dir                /home/konfekt/.config/aichat/rags
functions_dir           /home/konfekt/.config/aichat/functions
messages_file           /home/konfekt/.config/aichat/messages.md
```

**Environment (please complete the following information):**
- os version: Ubuntu 22.04
- aichat version: 0.23
- terminal version: Urxvt 9.30

**Additional context**

See #1006 ; piping should by default not start a session, but `-s` should take precedence.

**Comment by sigoden** [comment]
No, it start a `temp` session but the session have nothing.

**Comment by Konfekt** [comment]
I cannot start a temp session as soon as input is piped, same for `aichat -s --empty-session`.

It seems to me that `aichat` checks first if input is piped, then never starts a session, in particular discards `-s`. 

However, the user explicitly gave `-s` and it is documented as `starting a session`, therefore it should open a session. 

Where am I using or reading`aichat` wrong?

**Comment by sigoden** [comment]
have you checked the https://github.com/sigoden/aichat/wiki/Command-Line-Guide#examples

The `-s` option without a session name is special; it starts a temporary session that is always empty.

`echo 1 | aichat -s` equals to `aichat -s temp 1`.

**Comment by Konfekt** [comment]
Okay, yes, I thought it practically synonymous to enter the REPL. I am still at loss how to enter the REPL when input is piped. I don't understand the use case for `echo ... | aichat -s test1` as is

**Comment by David-Else** [comment]
@sigoden I think there is some misunderstanding here, what @Konfekt and myself would like to do is:

```
echo my cat is blue | aichat -s test1 
```
AND it opens a session called test1 so we can talk about the color of my cat. 

I am trying to create a command in my code editor that first opens a new terminal window and then pipes the current selection into aichat and starts a session to talk about the code.

Please how can we do that? Thanks!
