### ISSUE TITLE
Use free OpenAI account API to access GPT-3.5 or older?

### ISSUE THREAD

**Issue by irav2** [sigoden/aichat#1016]
When I try and use my OpenAI account with Aichat it tells me that it cannot access GPT-4o, I am guessing Aichat is configured to use the latest model when you select OpenAI, how could I use GPT-3.5 or GPT-2 with Aichat? Also, if I can't access even the old models using my OpenAI account's API key, what will allow me to use Aichat for free?

**Comment by sigoden** [comment]
in config.yaml
```yaml
model: openai:gpt-3.5-turbo
```
or run `aichat -m openai:gpt-3.5-turbo`

**Comment by irav2** [comment]
Now it says I have exceeded my current quota, it seems I have to pay for the API usage.
