### ISSUE TITLE
Can you have a chat session with memory for executing commands?

### ISSUE THREAD

**Issue by irav2** [sigoden/aichat#1022]
How do I start a chat session, but for executing commands, where I return standard error to the machine, and it can make revisions to the code to accommodate for it?

**Comment by sigoden** [comment]
AIChat can't capture the standard error for the command.

AIChat runs the abirtray command, which may log a lot of information before exiting, may never exit, may output binary data, or may produce ANSI color output. Capturing its standard error is not considered a good practice.
