### ISSUE TITLE
SSH support

### ISSUE THREAD

**Issue by Snify89** [sigoden/aichat#1024]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An SSH assistant but as client.
Basically aichat which also conmects via SSH.

**Describe alternatives you've considered**
None

**Additional context**
I have many Linux servers to administer
and I'd like to wish to use natural language 
on them. They're often old and sometimes hard(er) to handle.

**Comment by sigoden** [comment]
[llm-functions](https://github.com/sigoden/llm-functions)  is responsible for the development of agents, other than aichat.

Please submit the issue using this [link](https://github.com/sigoden/llm-functions/issues/new?assignees=&labels=enhancement&projects=&template=add_agent.md&title=%5BAgent+Request%5D+Add+%3CAgent+Name%3E) to create it directly on  [llm-functions](https://github.com/sigoden/llm-functions) repo.
