### ISSUE TITLE
Display citations from Perplexity API

### ISSUE THREAD

**Issue by makp** [sigoden/aichat#1028]
**Is your feature request related to a problem? Please describe.**
I have been using the client `openai-compatible` to interact with the Perplexity API. It works fantastic, but it doesn't display the citation sources. The citations come in the API response under the field "citations".

**Describe the solution you'd like**
After the content response finishes displaying, a section called "Citations" could display the citations used in the answer.

**Comment by sigoden** [comment]
We will not support this feature.

1. AIchat needs to support more than 20 providers, and it is impossible to handle specifically for a certain provider.

2. Data cannot be layered or collapsed in TUI. Displaying citations will interfere with the display of original answer.
An answer may have two or three lines, but citations may have dozens or hundreds of lines.
