### ISSUE TITLE
Enable AI Platform Setup Wizard to Configure Additional Platforms with Existing config.yaml

### ISSUE THREAD

**Issue by devxpain** [sigoden/aichat#1037]
**Is your feature request related to a problem? Please describe.**
Currently, the setup wizard can only be used when `config.yaml` does not exist, and it only allows configuring one AI platform during initial setup. After that, any further configuration requires manually editing `config.yaml`. This process is not user-friendly, especially for users who may not be comfortable directly modifying YAML files or want to make changes quickly.

**Describe the solution you'd like**
It would be helpful to enhance the setup wizard functionality to allow triggering it even if `config.yaml` already exists. For example, a command like `.model setup` could be introduced to re-trigger the wizard. This would make it easier to reconfigure the model settings or add additional AI platforms without manual editing.

**Describe alternatives you've considered**
- Manually editing the `config.yaml` file to make changes, which is error-prone and less user-friendly.
- Writing custom scripts to modify `config.yaml` indirectly, but this adds complexity and is not ideal for most users.

**Additional context**
Leveraging the existing wizard code to reconfigure models would likely reduce development effort. The enhancement would improve the overall user experience by providing a consistent, interactive setup process, even after the initial configuration.

**Comment by sigoden** [comment]
We will not support this feature.

## Reasons:

1. Most people only use one provider and the current setup is suitable for this.
2. config.yaml may contain comments and their unique format, which cannot be easily processed correctly by programs, especially Rust is weak in processing YAML.
