### ISSUE TITLE
[Feature request] More advanced role interface

### ISSUE THREAD

**Issue by jottr** [sigoden/aichat#104]
A method to query the roles in the REPL interface could be very useful.
Something along these lines:

```
$ .role define coder > You are a helpful assistant

$ .role ls 
 .bash
 .coder
 .wiki
 
$ .role prompt bash
  Some prompt definition.

$ .role rm bash
 ```

**Comment by sigoden** [comment]
I disagree.

1. role requires careful design, It is more appropriate to edit, import and share through file.
2. `.role <tab>` will trigger completion, which list all avaliabe roles.
