### ISSUE TITLE
roles in subdirectories

### ISSUE THREAD

**Issue by kiil** [sigoden/aichat#1040]
**Is your feature request related to a problem? Please describe.**

I have a lot of different roles because I use `aichat` in many different contexts. This means that my `roles` directory is a mess with too many files.

**Describe the solution you'd like**

I would like for `roles` to support subdirectories, like so

`roles/danishprompts/rolename.md`

`roles/englishprompts/rolename.md`

They could be referred as such:

```
aichat -r "danishprompts/rolename"
```

Then roles directly in the `roles` directory could still be referred to as simply `aichat -r rolename` making the change backwards compatible.

**Comment by sigoden** [comment]
We will not support this feaure.

I suggest you use a common prefix name to group, such as `englishprompts-rolename`, `danishprompts-rolename`.
