### ISSUE TITLE
Set OpenRouter's referer header

### ISSUE THREAD

**Issue by taha-yassine** [sigoden/aichat#1043]
**Is your feature request related to a problem? Please describe.**

Not a problem, but OpenRouter gives apps the ability to specify an optional `HTTP-Referer` header to identify them and make them discoverable to users: https://openrouter.ai/docs/requests#request-headers

**Describe the solution you'd like**

Setting the header would allow aichat to appear in the "app showcase" list on OpenRouter's home page, which would be good for visibility if that's something desired.

**Describe alternatives you've considered**

**Additional context**

**Comment by sigoden** [comment]
Thank you for your suggestion, but we will not implement this feature.

Reasons:
- AIChat only sends necessary data to the server, and these two HTTP headers are not essential.
- AIChat provides an optional `user_agent` configuration for users who need to identify requests sent by AIChat.
- AIChat is a non-commercial product, and there is no need to promote it in this way.
