### ISSUE TITLE
Lines show in duplicate/triplicate on narrower terminals

### ISSUE THREAD

**Issue by benoliver999** [sigoden/aichat#105]
I'm using aichat in Arch Linux with Kitty terminal. Using i3 as a display manager.

It works great, until I set the terminal to half-screen size, when lines appear several times over. This does not seem to occur on wider terminals.

![2023-04-05-17:18:11-screenshot](https://user-images.githubusercontent.com/4549631/230142800-2d120f87-d731-4660-b297-78b2b38d5cd2.png)

**Comment by XOKP** [comment]
I come across the same issue on macOS from time to time, but unsure how to replicate it.

**Comment by benoliver999** [comment]
Yeah actually, this is happening to me on full-width terminals too!

**Comment by MorganBergen** [comment]
yeah how do we change that so it wraps?

**Comment by sigoden** [comment]
@benoliver999 Is there any way for me to reproduce this problem again?

**Comment by sigoden** [comment]
With pr #154 merged, it will be much easier to debug such bugs.

Can someone reproduce the issue in dry-run mode for me to debug?

NOTE: Providing OS version and terminal version will be helpful
