### ISSUE TITLE
Document Loaders don't seem to work with -f or --file

### ISSUE THREAD

**Issue by jimmycav** [sigoden/aichat#1059]
When I use the example configuration for document loaders, I continue to get the error message:

```
Error: Failed to load files

Caused by:
    0: Unable to read file '/home/jamie/XYZ Cloud Principles 0.2 - redacted.docx'
    1: stream did not contain valid UTF-8

```

The configuration I'm using is below:

```
document_loaders:
  # You can add custom loaders using the following syntax:
  #   <file-extension>: <command-to-load-the-file>
  # Note: Use `$1` for input file and `$2` for output file. If `$2` is omitted, use stdout as output.
  pdf: 'pdftotext $1 -'                         # Load .pdf file, see https://poppler.freedesktop.org to set up pdftotext
  docx: 'pandoc --to plain $1'                  # Load .docx file, see https://pandoc.org to set up `pandoc`
```

I have checked and the commands in the configuration are working correctly. 

The documentation implies that this is used for both RAG and for loading files, is this correct?

**Comment by sigoden** [comment]
Cannot confirm the problem; 

This feature has been supported since v0.25.0. Please ensure your AIChat version is up to date.

**Comment by jimmycav** [comment]
Thanks, I had an older version and should have checked.
