### ISSUE TITLE
Is it possible to implement a feature for AIChat to reference the output or error message from the previous command

### ISSUE THREAD

**Issue by sunk926** [sigoden/aichat#1063]
For example:   **aichat  --lastOut   1   'What's the issue here'**

**Comment by sigoden** [comment]
We will not support this feature.

This feature requires tmux (or something similar) to access the terminal buffer, which contains previous commands and error messages.

Maybe you can write a script that invokes tmux and aichat to achieve the same functionality.

**Comment by sunk926** [comment]
> We will not support this feature.
> 
> This feature requires tmux (or something similar) to access the terminal buffer, which contains previous commands and error messages.
> 
> Maybe you can write a script that invokes tmux and aichat to achieve the same functionality.

I changed my approach by opening two windows in tmux. Window ID 0 is used for entering commands, while window ID 1 runs `aichat`. I then set up a hotkey `set-keys > tmux capture-pane -t 0 -p -E 20` to pass the content from window ID 0 to ID 1. However, there's still an inconvenience: in the Chat-REPL, I can't execute `capture-pane`. I wish I could run bash commands directly within the REPL.
