### ISSUE TITLE
Feature request: <command> + <Enter> to sent messages in web UI.

### ISSUE THREAD

**Issue by curiosusJR** [sigoden/aichat#1064]
When using a non-English input method, the Enter key is used for typing English symbols, or when multiple-lines text are entered into the input box, the text is sent. 

I wish it could be sent the text using <command> (or <ctrl> in Windows) + <enter>. Thank you!

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the `extra_keybindings` function to add a new key binding for Cmd+Enter (Ctrl+Enter on Windows) that triggers the Enter action. This allows users to send text using this key combination, addressing the issue with non-English input methods and multi-line text entry.

You can review changes in this commit: https://github.com/wwqwq2313/sigoden-aichat-1064/commit/490b73328c527ff8d2448ed23e4277d78dd01404.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by sigoden** [comment]
The webUI already supports `shift + enter` to input a newline, `enter` to submit, like chatgpt.
