### ISSUE TITLE
Is there a way of setting use_tool for a specific model?

### ISSUE THREAD

**Issue by shaked8634** [sigoden/aichat#1065]
I'm using aichat with both local (ollama) and remote models (like OpenAI).
When `use_tool: true` the remote models works and call functions as expected, but the local models fail with:
 
>Error: Failed to call chat-completions api
>
>Caused by:
>    registry.ollama.ai/library/deepseek-coder-6.7b-instruct.Q4_K_M:latest does not support tools (type: api_error)
 
Is there a way to disable use_tools per model?

**Comment by sigoden** [comment]
Please create a role for it. 

For example, a role `gpt-4o-functions` to set use_tool for openai:gpt-4o
```
---
model:  openai:gpt-4o
use_tools: all
---
```
