### ISSUE TITLE
Compress session on command line

### ISSUE THREAD

**Issue by garyblankenship** [sigoden/aichat#1070]
I am using 0.26.0 with a session from cli that I am chatting with. I ran out of context with the model. Can the session compression work from cli too or only in the repl?

Error: Failed to call chat-completions api

Caused by:
    Input request contains (33425) tokens, which is more than the max tokens limit allowed: (32768) (status: INVALID_ARGUMENT)

**Comment by sigoden** [comment]
Please use `.compress session` REPL  command or `compress_threshold: <value>` configuration.

**Comment by garyblankenship** [comment]
I can only continue the session in REPL. Is that correct then?

**Comment by sigoden** [comment]
The `.compress session`  only works for non-empty session

**Comment by garyblankenship** [comment]
Example: This session trivia will never compress. Compress only works with REPL?

```
while true; do
    aichat --model gemini --role trivia --session trivia "Add 5 unique new questions."
    sleep 30
done
```

**Comment by sigoden** [comment]
In script mode, try to use role to solve the problem. If you can not, use read-only session.

If you must use session in read-write, then I wish you good luck.
