### ISSUE TITLE
undo and clipboard integration  features in the README?

### ISSUE THREAD

**Issue by sudomain** [sigoden/aichat#109]
Hi I just want to check to see that I'm not missing something obvious here. It appears the README mentions:
```
Undo support
Clipboard integration
```
I can't find anything in the help or github search. Are these yet to be implemented or am I bad at searching?

**Comment by sigoden** [comment]
`undo support` means you can use `ctrl+z` to undo typing.
clipboard integration is internal feature, i will remove it from readme.
