### ISSUE TITLE
Some confusing items .help

### ISSUE THREAD

**Issue by zach-is-my-name** [sigoden/aichat#112]
I find the following .help items confusing:

.info "Print **_the_** information" -- lol print what information? 

"Ctrl+C to abort readline" -- how is this differnt than .exit? 

"Ctrl+D to exit the REPL" -- how is this different than Ctrl+C?

**Comment by sigoden** [comment]
`.info` - print system-wide information
`ctrl + c` - can abort openai connection/request/response.
`ctr + d` - is same to `.exit`
