### ISSUE TITLE
After configuring aichat in mac terminal getting failed to fetch error every time

### ISSUE THREAD

**Issue by SanthoshKumar189** [sigoden/aichat#115]
My internet connection is stable and restarted the terminal multiple times still getting the error

<img width="1425" alt="Screenshot 2023-04-26 at 12 38 40 PM" src="https://user-images.githubusercontent.com/98883296/234497382-34619ef4-a405-4999-b993-fc7456c3d0bb.png">

My config

<img width="608" alt="Screenshot 2023-04-26 at 12 40 45 PM" src="https://user-images.githubusercontent.com/98883296/234497613-76ed0960-5501-4c4d-a81e-9e7093ab3755.png">

Do i have change the configs?

**Comment by skiman6010** [comment]
I would revoke that api_key and blur out your new api_key and re-upload your screenshots... Wouldn't want your active keys to get stolen.
