### ISSUE TITLE
[Feature request] Replace OpenAI API Endpoint with Custom Endpoint 

### ISSUE THREAD

**Issue by line2** [sigoden/aichat#116]
I would like to suggest adding a new feature to the aichat  that would allow users who can't directly access the OpenAI API endpoint, or who wish to use Azure OpenAI Service, to replace the default endpoint with a custom endpoint. This would provide users with greater flexibility in selecting an endpoint based on their specific use-case.

The feature should include a new command-line option or environment variable that allows the user to specify their custom endpoint, which can then be used by the aichat app to make API calls to the custom endpoint instead of using the default OpenAI API endpoint.

I believe that this feature would be particularly beneficial for users who are trying to integrate aichat with their own custom AI models or services, or for those who rely on Azure OpenAI Service for their AI needs.

Thank you for considering this feature request.

**Comment by StereoApp** [comment]
need this feature too

**Comment by chenjunweicc** [comment]
Is this feature under development?

**Comment by shodanx2** [comment]
I would like to use with locally, offline hosted text generator AI running the following interface

https://github.com/oobabooga/text-generation-webui
