### ISSUE TITLE
Autodetect theme

### ISSUE THREAD

**Issue by pomdtr** [sigoden/aichat#121]
My terminal theme is synced with my system, so I have light terminal during the day and a dark one during the evening.

It would be cool to have to have a `theme: automatic` option.

**Comment by MrConnorKenway** [comment]
Can we use https://github.com/bash/terminal-colorsaurus to detect theme? Here is how `bat` does it: https://github.com/sharkdp/bat/pull/2896, https://github.com/sharkdp/bat/pull/2896/files#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87eR152
