### ISSUE TITLE
Configuring path for history.txt and messages_file

### ISSUE THREAD

**Issue by ultraSsak** [sigoden/aichat#122]
Hi there,
I'm just starting with this amazing tool, so first of all - big thanks to community! :)

I have a question regarding configuration,
Is there a way to define path of `history.txt` and `messages_file`?

I've searched this github repo, but didn't find it,
I've asked aichat for it, he didn't help either ;)

I've tried adding line 
```yaml
messages_file: '~/.cache/aichat/messages.md'
```
but that didn't work either

**Comment by sigoden** [comment]
You can change the configuration directory via the environment variable AICHAT_CONFIG_DIR , but not the location of individual files.
