### ISSUE TITLE
Add base url option

### ISSUE THREAD

**Issue by alexkreidler** [sigoden/aichat#127]
There are various open source models and hosted LLMOps tools that are compatible with the OpenAI API, like [LocalAI](https://github.com/go-skynet/LocalAI) and [Helicone](https://helicone.ai/). It would be great to be able to use the `OPENAI_API_BASE` environment variable or the config file to use aichat with these systems!

**Comment by molezz** [comment]
need the custom URL function ~~

**Comment by vaderyang** [comment]
> need the custom URL function ~~

PR #143 already addressed this issue. but never being accepted.
