### ISSUE TITLE
[Feature Request] ability to use local llms, perhaps with the llm crate

### ISSUE THREAD

**Issue by AnthonyMichaelTDM** [sigoden/aichat#129]
It'd be nice to be able to use this tool w/ a offline, locally running, open source, llm instead of using the openAI API's. You could probably use the https://github.com/rustformers/llm crate to achieve this.

**Comment by AnthonyMichaelTDM** [comment]
though honestly, just allowing users to define their own endpoint(s) to be used for API requests should allow this (they just need to self-host a compliant REST server w/ their LLM of choice as it's backend) and would also resolve a few other open Issues, though I'm less sure how that would be done implementation-wise

**Comment by 0m364** [comment]
depends on your local bot ... i wrote some script to use with the alpaca/llama locals but it isnt as straigforward as running the code as this is you have to open the main and find where to splice... after that it will read from a .json

**Comment by AnthonyMichaelTDM** [comment]
I suppose

**Comment by 0m364** [comment]
> though honestly, just allowing users to define their own endpoint(s) to be used for API requests should allow this (they just need to self-host a compliant REST server w/ their LLM of choice as it's backend) and would also resolve a few other open Issues, though I'm less sure how that would be done implementation-wise

you could load it into Google cloud dev or AWS and generate an API.. but the cost of doing so my not justify the speed/latency && it would not longer be local

**Comment by 0m364** [comment]
> It'd be nice to be able to use this tool w/ a offline, locally running, open source, llm instead of using the openAI API's. You could probably use the https://github.com/rustformers/llm crate to achieve this.

this might work .. I don't have time to test and twerk right now but when I get home later I'll try I forked the llm and wrote this (I'm on my phone so if it doesn't work I'll fix it ) but this should just generate the API. https://github.com/0m364/aichat/blob/main/make_local_API.rs

**Comment by vaderyang** [comment]
for a lightweight tool, merging local llm would be too heavy. I added a #143 to use third party local LLM with customizable API url should be a solution for this.
