### ISSUE TITLE
Highlight issue on macOS (M1)

### ISSUE THREAD

**Issue by xxxAleksandrxxx** [sigoden/aichat#132]
Thank you for this awesome app!
during my playing around it i realised that on macOS (M1) with 'highlight: true' the code highlighting works a little buggy:

<img width="747" alt="Screenshot 2023-06-28 at 18 15 44" src="https://github.com/sigoden/aichat/assets/103126986/7336fa36-10ba-4222-a301-d74323160f54">

by the way with 'highlight: false' it works well

<img width="747" alt="Screenshot 2023-06-28 at 18 16 31" src="https://github.com/sigoden/aichat/assets/103126986/cfdeab85-91e0-4200-90de-87003d896584">

Is there any way to adjust highlighting locally?

**Comment by sigoden** [comment]
If anyone encounters the same problem, can you provide the following information?

os: e.g. ubuntu22.04, macos 14.0
terminal_version: e.g. GNOME Terminal 3.44.0
aichat_version: e.g. 0.8.0

Is the result the same when running without repl: `aichat a echo server in node.js`?

**Comment by sigoden** [comment]
Due to lack of user feedback, this issue is closed.

**Comment by chiefMarlin** [comment]
I just tested V0.14 and have the same issue, if highlighting is turned off then it looks fine (but no highlighting)

<img width="995" alt="Screenshot 2024-03-18 at 12 19 53 PM" src="https://github.com/sigoden/aichat/assets/96321026/e6a2a379-e4a5-4ea5-8517-6ccba1466d0d">

Running `aichat a echo server in node.js` produces the same issue
I am running
OS: 14.4 (23E214)
Terminal: Version 2.14 (453)
aichat vers:  0.14.0

Here is my config
```
model: claude
temperature: 1.0                 # GPT temperature, between 0 and 2
save: true                       # Whether to save the message
highlight: true                  # Set false to turn highlight
light_theme: false               # Whether to use a light theme
wrap: no                         # Specify the text-wrapping mode (no, auto, <max-width>)
wrap_code: false                 # Whether wrap code block
auto_copy: false                 # Automatically copy the last output to the clipboard
keybindings: emacs               # REPL keybindings. (emacs, vi)
prelude: ''                      # Set a default role or session (role:<name>, session:<name>)

# Compress session if tokens exceed this value (valid when >=1000)
compress_threshold: 1000
# The prompt for summarizing session messages
summarize_prompt: 'Summarize the discussion briefly in 200 words or less to use as a prompt for future context.'
# The prompt for the summary of the session
summary_prompt: 'This is a summary of the chat history as a recap: '

# Custom REPL prompt, see https://github.com/sigoden/aichat/wiki/Custom-REPL-Prompt
left_prompt: '{color.green}{?session {session}{?role /}}{role}{color.cyan}{?session )}{!session >}{color.reset} '
right_prompt: '{color.purple}{?session {?consume_tokens {consume_tokens}({consume_percent}%)}{!consume_tokens {consume_tokens}}}{color.reset}'
```
