### ISSUE TITLE
Is it possible to chat with ChatGPT rather than a GPT-* model?

### ISSUE THREAD

**Issue by sudomain** [sigoden/aichat#139]
This is a bit pedantic, but is it possible to use aichat with specifically ChatGPT? I've successfully used it with GPT-3.5+ which requires an API key. ChatGPT on the other hand doesn't require a key and afaict can only run in the browser. This project claims to also be able to use ChatGPT, but I can't figure out how to. Any tips?

Edit: FWIW, I'm able to access ChatGPT in the terminal using [this library](https://github.com/acheong08/ChatGPT) and the basic client found in its wiki. Rather than an API key, it uses the user's account username and password. It would be great of this could be integrated into aichat so that I could use my aichat roles with ChatGPT

**Comment by powellnorma** [comment]
After a quick look, I think this is currently not implemented. I think it would be easier to use some kind of (maybe local) proxy, that simulates the OpenAI API. Then all this Client would need to do is use that URL here: https://github.com/sigoden/aichat/blob/bbf3672a5f95c6348600029caf1f48a52813fb62/src/client.rs#L13

**Comment by sigoden** [comment]
You can find a way to turn the web version of chatgpt into an api server and call it through custom url, see #150

**Comment by sudomain** [comment]
Interesting. I'll give that a try once that feature makes it into the Termux repos
