### ISSUE TITLE
Highlighting: Strip trailing whitespace

### ISSUE THREAD

**Issue by powellnorma** [sigoden/aichat#141]
When highlighting is enabled, additional whitespaces  are present in the output. When using `--no-highlight` this does not happen. This is not ideal for copy pasting etc.

It seems to happen only in repl mode.

Example:

````
〉Write a python function for calculating primes. Only output the code
Sure! Here's a Python function that calculates and returns prime numbers:
                                                                         
```python
def find_primes(num):
    primes = []      
    for i in range(2, num + 1):
        is_prime = True        
        for j in range(2, int(i ** 0.5) + 1):
            if i % j == 0:                   
                is_prime = False
                break           
        if is_prime: 
            primes.append(i)
    return primes           
```              
   
You can use this function to find prime numbers up to a given `num` value. Simply call the function and provide the desired `num` as an argument. The function will then return a list of all prime numbers found.
````

**Comment by powellnorma** [comment]
@sigoden Ok, but why does this only occur when highlighting is enabled? I don't think these spaces are outputted by the model itself.

Also for illustration what this issue is about:
![image](https://github.com/sigoden/aichat/assets/101364699/bf769ed3-3ae1-4069-9ebc-c311c1cbbe2f)

**Comment by sigoden** [comment]
Everything is ok.

![aichat](https://github.com/sigoden/aichat/assets/4012553/bb5de798-d62c-4392-ab2c-a77e503e7dc9)

The trailing whitespace on selecting highlighting  is determined by the terminal and has nothing to do with aichat.

**Comment by powellnorma** [comment]
I think the screencast you provided does not show whether the bug is reproducible on your environment or not, since the entire line is highlighted. I see the problem only after I pasted the selected text somewhere (e.g. an editor), and look there how long each line is.

> The trailing whitespace on selecting highlighting is determined by the terminal and has nothing to do with aichat.

Possible, but I find it odd that the line always is padded exactly to the width of the previous line (see screenshot [here](https://github.com/sigoden/aichat/issues/141#issuecomment-1783736169)).

Okay I just tested other terminal emulators, and it seems this issue only happens with urxvt (aka rxvt-unicode), and not e.g. with xterm or alacritty. It seems similar to https://github.com/neovim/neovim/issues/4421

**Comment by sigoden** [comment]
I guarantee that what aichat outputs is what it receives, and there are absolutely no additional spaces added.

If you are concerned that copying from the screen may not be accurate, you can use the `.copy` command, or the `config.auto_copy` configuration.
