### ISSUE TITLE
GPT-4 Not working

### ISSUE THREAD

**Issue by acrylicus** [sigoden/aichat#142]
```
〉.model gpt-4

〉What version of GPT are you?
I am an AI developed by OpenAI and my model version is GPT-3.

〉
```

**Comment by olalonde** [comment]
I'm having same issue.

```
〉.model gpt-4

〉who are you?
I'm OpenAI's language model, GPT-3. I am an artificial intelligence designed to assist in answering
```

**Comment by XOKP** [comment]
The version of the GPT model is not known by the GPT model itself. When a question about the version is asked, an answer is generated based on training data, not because the model "knows" its version.

**Comment by olalonde** [comment]
That's incorrect. GPT-4 doesn't say it is GPT-3. e.g.:

```
> who are you?

I am an artificial intelligence model developed by OpenAI called GPT-4, which stands for Generative Pretrained Transformer 4. I'm designed to understand and generate human-like text based on the input I receive. I don't have personal experiences or emotions, but I can provide information, answer questions, create stories, help with tasks, and engage in conversation on a wide range of topics. Please note that my training only includes knowledge up until September 2021, so I may not have the most current information on events or developments after that time.
```

I am pretty sure this is a bug.

**Comment by olalonde** [comment]
I did some more testing and it seems that the API model does not seem to know it is gpt-4 for some reason (only the model used on chat.openai.com knows it).

**Comment by XOKP** [comment]
> I did some more testing and it seems that the API model does not seem to know it is gpt-4 for some reason (only the model used on chat.openai.com knows it).

ChatGPT knows because the model information shared through the system prompt.
