### ISSUE TITLE
Publish a new release with at least support of bracketed paste mode and gpt-3.5-16k

### ISSUE THREAD

**Issue by milanglacier** [sigoden/aichat#149]
Currently the latest release is still at v0.8 which lacks a lot of new features, including:

1. bracketed paste mode. This would be a very important release which allows user to paste arbitrary text from other sources as long as they are using a popular terminal.
2. gpt-turbo-3.5-16k. This is a great choice for the balance of price, speed, and long context.

A newer release would definitely very helpful especially for users incapable of installing the rust toolchain to compile the binary.

**Comment by sigoden** [comment]
There will be some important updates in the next few days, so please wait a little longer.
