### ISSUE TITLE
`.edit` and start with new line results in the following error: `error: Unknown command. Type ".help" for more information.`

### ISSUE THREAD

**Issue by milanglacier** [sigoden/aichat#152]
step to reproducde:

```
$ .edit
hello! <Ctrl-S>
```

get the Error: Unknown command. Type ".help" for more information.

**Comment by sigoden** [comment]
Did you build aichat with the latest commit?
Does the `.help` text contain `.edit` help information?

**Comment by milanglacier** [comment]
I am using macOS, built with the lates commit.

the error comes from newline directly following `.edit`

if there is a space between `.edit` and the newline, the error will not occur.
