### ISSUE TITLE
`.copy` is not working on Linux X11

### ISSUE THREAD

**Issue by gauravkumar37** [sigoden/aichat#160]
- Using the latest commit on Linux with X11 display server, `.copy` is not working and nothing happens, not even after quitting the app.
- Using Linux Majaro with 6.5.5-1 kernel on X11 with KDE as the desktop environment
- `echo ok | xclip -selection clipboard -i` this works

**Comment by sigoden** [comment]
This feature has been around for a long time, and no one has reported bugs. I've tried it myself and found no problem.
Is there something wrong with your operation？ Can you do it again based on the picture?

![image](https://github.com/sigoden/aichat/assets/4012553/698d5093-1374-4217-945e-8b11990dc6ef)

**Comment by gauravkumar37** [comment]
Yes, tried again like in the picture.
I think this may be because of https://github.com/1Password/arboard/issues/114

**Comment by gauravkumar37** [comment]
Ok, tried with the library arboard on local. Here's my debugging steps, not super familiar with rust but I think this has something to do with text reference vs actual data?

```rust
use std::time::Duration;

use arboard::Clipboard;

fn main() {
    copy("this does not work");

    let mut clipboard = Clipboard::new().unwrap();
    clipboard.set_text("this works").unwrap();

    // give it a second to sync with clipboard before exiting the program
    std::thread::sleep(Duration::from_secs(1));
}

pub fn copy(src: &str) {
    let mut clipboard = Clipboard::new().unwrap();
    clipboard.set_text(src).unwrap();
}
```

**Comment by gauravkumar37** [comment]
Aah, got it, you need some delay in the function `copy`. This fixes it:

```rust
use std::time::Duration;

use arboard::Clipboard;

fn main() {
    copy("this was not working earlier but now works");

    let mut clipboard = Clipboard::new().unwrap();
    clipboard.set_text("this works").unwrap();

    // give it a second to sync with clipboard before exiting the program
    // std::thread::sleep(Duration::from_secs(1));
}

pub fn copy(src: &str) {
    let mut clipboard = Clipboard::new().unwrap();
    clipboard.set_text(src).unwrap();

    std::thread::sleep(Duration::from_secs(1)); // <-- this is the fix
}
```

**Comment by sigoden** [comment]
Is 1 second is enough? or 100 milliseconds is enough?
Is delay related to the length of the content?
Moreover, aichat supports `config.auto_copy`. Long delay will affect the user experience.

It is better to wait for arboard to fix related problems.

**Comment by gauravkumar37** [comment]
auto copy is also not working and I think this is why: `clipboard` is being initialized inside the `copy` function every time. So before it has a chance to actually copy (asynchronously) data to OS clipboard, the `clipboard` is dereferenced because `copy` function returns.
The timeout was just a band-aid fix. Actual fix is to extract out the `clipboard` out of the `copy` function and only initialize it once.

```rust
use std::time::Duration;

use arboard::Clipboard;

fn main() {
    let mut clipboard = Clipboard::new().unwrap();

    copy(&mut clipboard, "hello");

    // give it a second to sync with clipboard before exiting the program
    // only needed in this test cli, not in aichat
    std::thread::sleep(Duration::from_secs(1));
}

pub fn copy(clipboard: &mut Clipboard, src: &str) {
    clipboard.set_text(src).unwrap();
}
```

**Comment by sigoden** [comment]
cloud you test #161 for me?

**Comment by gauravkumar37** [comment]
Works like a charm. Also tested the `auto_copy` feature, that is also working. Thanks for such a wonderful tool and also for providing a fix so promptly :rocket:

**Comment by sigoden** [comment]
You're welcome and thank you for your contribution.
