### ISSUE TITLE
Ambiguous behavior when trying to save a session with name `temp`

### ISSUE THREAD

**Issue by milanglacier** [sigoden/aichat#164]
Step to reproduce:

```bash
aichat -s

# some conversions

<Ctrl-D>

? Save session? (Y/n)
y
? Session name: (temp)
Press Enter, do not give any name
```

then `temp.yaml` will be written into the `session` folder.

the next time to start with `aichat -s` again,

you can see that the history of `temp` is completely ignored, for example, you can assign the `.role` again, and save the `temp` conversation again will override previous `temp.yaml`.

I find this behavior is ambiguous. Given that `temp` is the default name for the new session, saving a `temp.yaml` to the history would lead to confusion. It would be better if if can throw an error when user tried to save current session with name `temp`.

**Comment by sigoden** [comment]
It was designed this way intentionally.

The `aichat -s` starts a new temp session.
The `aichat -s temp` reuses previous temp session.

**Comment by milanglacier** [comment]
ok, I think it also makes sense if we could add another config options like `session_first` that will automatically start `aichat` in a new session even if no `-s` if supplied when this option is set to true?

**Comment by sigoden** [comment]
There is currently no best solution for this problem.
Different people may have different options when starting the REPL:

- default: one-off request
- session_new: similar `aichat -s`
- session_named: similar `aichat -s temp`
