### ISSUE TITLE
aichat hangs on some terminals (fail to detect theme)

### ISSUE THREAD

**Issue by milanglacier** [sigoden/aichat#173]
Whe using the latest commit with automatically detect theme enabled:

the aichat will hang on some terminals:

I suppose this is because many different terminal app's implementation to handle the escape code differently?

I tried different terminal apps:

1. when use `alacritty` with `tmux`, not work. `TERM=tmux-256color, TERM_PROGRAM=tmux`
1. when use `alacritty` without `tmux` on macOS, it works, `TERM=alacirtty, TERM_PROGRAM=""`
2. when use `windows terminal` with WSL, not work, `TERM=xterm-256color, TERM_PROGRAM=""`
3.  `wezterm` with WSL, not work. `TERM=xterm-256color, TERM_PROGRAM=Wezterm`
4. use neovim embedded terminal, not work, `TERM=xterm-256color, TERM_PROGRAM=""`
5. use vscode embedded terminal, it works `TERM=xterm-256color, TERM_PROGRAM="vscode"`.

Here is a step to reproduce on windows terminal + WSL + tmux:

step to reproduce:

tmux config:

```
set -as terminal-features ",xterm-256color*:RGB"
set -as terminal-features ",alacritty*:RGB"
set -g default-terminal "tmux-256color"
```

windows terminal config: default config

aichat config:

```yaml
model: openai:gpt-3.5-turbo-16k

clients:
  - type: openai
    api_key: xxxxxxxxx

```

```
tmux
aichat
```

see that aichat hangs:

<img width="394" alt="Screenshot 2023-10-29 at 14 29 02" src="https://github.com/sigoden/aichat/assets/45728125/0a4a7746-ff5c-4efa-917a-695a8eb7aa06">

**Comment by milanglacier** [comment]
Here is some results from `cargo run` with `termbg` program:


1. Inside tmux +  neovim embedded terminal:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/termbg`
Check terminal background color
11;?11;?  Term : Tmux
  Latency: 984.583µs
  Color: detection failed Io { source: Custom { kind: TimedOut, error: "future timed out" } }
  Theme: detection failed Io { source: Custom { kind: TimedOut, error: "future timed out" } }

```

2. Inside alacritty + neovim embedded terminal:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/termbg`
Check terminal background color
  Term : XtermCompatible
  Latency: 1.011417ms
  Color: detection failed Io { source: Custom { kind: TimedOut, error: "future timed out" } }
  Theme: detection failed Io { source: Custom { kind: TimedOut, error: "future timed out" } }

```

3. Inside tmux:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/termbg`
Check terminal background color
  Term : Tmux
  Latency: 1.026625ms
  Color: detection failed Io { source: Custom { kind: TimedOut, error: "future timed out" } }
  Theme: detection failed Io { source: Custom { kind: TimedOut, error: "future timed out" } }

```

**Comment by sigoden** [comment]
Theme detect had too many problems, I decided to remove this feature.
