### ISSUE TITLE
Session with command mode does not save commands in session file

### ISSUE THREAD

**Issue by gauravkumar37** [sigoden/aichat#184]
**Describe the bug**
Session with command mode does not save those commands in session file.

**To Reproduce**
1. Start a new session
2. Ask something inside the session
3. Exit while saving the session
4. Inspect the sessions files, it will have the Q and A in it
5. Use the command mode with this session name, the command is now NOT saved in the session file.

**Expected behavior**
Session should be saved when using command mode
The `sum it` command didn't have the response from `reverse it` command

**Screenshots/Logs**
![image](https://github.com/sigoden/aichat/assets/2500570/bf4a7aa1-c639-40a8-8069-b1eb3e49d7d2)

**Environment (please complete the following information):**
- os version: Manjaro
- aichat version: latest from main branch
- terminal version: KDE X11 Konsole 23.08.1

**Comment by sigoden** [comment]
Specifically designed this way.

The session file is used to prepare a meaningful context environment for easy reuse. not just record less important chat history.

Based on this concept, I did not design to automatically save the conversation to the session file during REPL, but waited for the user to manually confirm the save.

Another consideration is that the more chat messages in the session, the more tokens will be consumed in the next request, and the cost will increase sharply.

Therefore, in command mode, the session will not be modified, and the session is similar to a role.

**Comment by gauravkumar37** [comment]
Thanks, this also works. But we have to be in repl mode already. I guess command mode is purely a one-off and cannot be included in the session directly.
