### ISSUE TITLE
It appears that the interaction mode of the role lacks contextual information.

### ISSUE THREAD

**Issue by changcui** [sigoden/aichat#2]
![image](https://user-images.githubusercontent.com/22012466/222634237-6c224268-db9b-4bc3-8dc9-ce9af4bee130.png)
Do I need to indicate the role each time I pose a prompt?

**Comment by sigoden** [comment]
This will fix in next release.
The role should persist until  cleared via `.clear-rule`.

**Comment by changcui** [comment]
Great work!
