### ISSUE TITLE
Suggestion: don't use `"""` as multipline input indicator

### ISSUE THREAD

**Issue by milanglacier** [sigoden/aichat#228]
`"""` is used as the multiple-line string in python and is frequently used.

Using `"""` would lead to confusion when user want to use `aichat` for reading and debugging python code.

**Comment by sigoden** [comment]
Do we have any other better options?

- `.edit .role myrole ...` is wired，also not sure if `ctrl+s` will conflict with terminal shortcuts.
- `[` or `{` is not very friendly to JSON.

**Comment by milanglacier** [comment]
how about grammar similar to bash heredoc:

like this:

```
<< HELLO

multilines doc

HELLO
```

Possible conflictions: 

1. conflict with bash heredoc, however, in case it is possible for the conflict to happen, the user can change the title of the heredoc to avoid conflict:

```
<< HELLO2
<< HELLO1

HELLO1
HELLO2
```

3. yaml uses `<<` as the anchor, but I don't see any possible situations where `<<` would be at the beginning of line without spaes

**Comment by sigoden** [comment]
There are some basic requirements:
1. The indicator string should not be too long, three characters are sufficient.
2. The end indicator should be rare to avoid potential conflicts.

`<< HELLO`  is too long, difficult to input.

The use of common words as end indicators is not recommended.

**Comment by sigoden** [comment]
These three characters may be suitable.

```
〉***

***
```

```
〉%%%

%%%
```

```
〉$$$

$$$
```

**Comment by milanglacier** [comment]
`:::` is good, I haven’t remembered any languages used three `:`s as idenfiers, lua uses `::` to indicate the `goto` block and we should be good.

Latex and matlab uses `%` as comment sign, so it is not good.

It is possible to have pointers of three levels in `C`, so `*` is not good.

**Comment by sigoden** [comment]
I agree. `:::` is the best. thank you for your contribution.
