### ISSUE TITLE
Error: Invalid model 'gpt-4'

### ISSUE THREAD

**Issue by tomsib2001** [sigoden/aichat#237]
**Describe the bug**
Any call with model gpt-4 or gpt-4-1106-preview results in 
Error: Invalid model 'gpt-4'

**To Reproduce**
```shell
aichat --model gpt-4 --info
```
or
```shell
aichat --model gpt-4 "What is the capital of France?"
```
or even
```shell
 aichat --model gpt-3.5-turbo --info
```

**Environment (please complete the following information):**
- os version: Ubuntu 22.04 in WSL
- aichat version: 0.10.0
- terminal version: Windows Terminal

**Additional context**
I had a network error:
```shell
Error: Failed to fetch stream

Caused by:
    Request failed, Bad gateway.
```
before upgrading ( I can't remember if I was at 0.8.0 or 0.9.0). so I upgraded and the current behaviour replaced the previous one.

**Comment by sigoden** [comment]
Please run 'aichat --list-models' and choose one from the list

**Comment by sigoden** [comment]
You may have missed the `openai:` prefix. try `openai:gpt-4`
