### ISSUE TITLE
Ollama support

### ISSUE THREAD

**Issue by jhugs** [sigoden/aichat#241]
Easy configuration to use with [ollama](https://github.com/jmorganca/ollama) would be AMAZING. That is all.

**Comment by sigoden** [comment]
The Ollama API does not support context-aware conversations by appending an array of past messages. I hope jmorganca/ollama#991 will solve this problem.

The community strongly requests Ollama to support the OpenAI-compatibility API, see jmorganca/ollama#305, perhaps in the future, it will be possible to configure and use ollama through LocalAI client.

**Comment by jhugs** [comment]
Bummer, thanks for the info, keep up the good work!

**Comment by PetrarcaBruto** [comment]
I totally agree that ollama support of Open-AI will be a tremendous feature that will benefit a big part of the community.

**Comment by Elijer** [comment]
It looks like this feature was added but a google search on "how to use aichat sigoden with ollama" takes me here, and I haven't really been able to find great documentation yet on how to set up aichat with Ollama. Is there documentation for this?

**Comment by blob42** [comment]
You can do this
```
clients:
  - type: openai-compatible
    name: ollama
    api_base: http://ollama.srvlan:11434/v1                  # ENV: {client}_API_BASE
    # api_auth: Basic xxx                               # ENV: {client}_API_AUTH
    models:                                           # Required
      - name: llama3.1
        max_input_tokens: 56000
        supports_function_calling: true
```

Note that some features dont work such as  sending images to vision models as Ollama OpenAI compatibility is not complete.

**Comment by newptcai** [comment]
Do this actually work? The LLM on Ollama cannot see the previous messages.

```
xing@DKU-0992:~$ aichat
Welcome to aichat 0.30.0
Type ".help" for additional help.
> Okay, where is capital of the Zambic?
It seems like you meant the **"Capital of Zambia"** (the country name is *Zambia*, not "Zambic").

The capital of **Zambia** is **Lusaka**.

Would you like more details about Lusaka?

> Tell me about its population.
Could you clarify which place or entity you're referring to? Are you asking about:

- A **specific country** (e.g., France, Japan)?
- A **city** (e.g., Paris, New York)?
- A **region** (e.g., Catalonia, Texas)?
- A **company** or **organization**?

Once you provide the name, I can give you the latest population data (if available) or guide you on how to find it! 😊

*(Note: My knowledge cutoff is October 2023, so for the most recent statistics, I’d need to clarify where to look.)*
```
