### ISSUE TITLE
Expand *_API_KEY pattern and update documentation for env vars

### ISSUE THREAD

**Issue by ntippie** [sigoden/aichat#247]
**Is your feature request related to a problem? Please describe.**
The documentation only describes one *_API_KEY env var (OPENAI_API_KEY), but it is now possible to use multiple models from different services. The variable name suggests that this key is only for use with OpenAI (as it was recently renamed from AICHAT_API_KEY). A grep also reveals that `{env_prefix}_API_KEY` is called in `src/clients/ernie.rs`.

**Describe the solution you'd like**
The *_API_KEY pattern be followed for all models/services, and is properly documented in the README or in the [env vars wiki page](https://github.com/sigoden/aichat/wiki/Environment-Variables).

**Describe alternatives you've considered**
Maybe using env var OPENAI_API_KEY works for all services, I didn't test that. However the recent rename from AICHAT_API_KEY suggests that it doesn't.

**Additional context**
I'm looking to load the API key(s) in from the env and not in the config file so that I can store it elsewhere in an encrypted format.

**Comment by sigoden** [comment]
All API_KEY can be set through the `{env_prefix}_api_key` environment variable.
The `env_prefix` is the client's name or type.

**Comment by sigoden** [comment]
[Environment-Variables](https://github.com/sigoden/aichat/wiki/Environment-Variables) updated.
