### ISSUE TITLE
REPL prompt characters do not render with common fonts

### ISSUE THREAD

**Issue by ntippie** [sigoden/aichat#248]
**Describe the bug**
The REPL prompt (`src/repl/prompt.rs`) uses some rare characters that are not supported by most fonts and render as a square:
  - ）U+FF09 (FULLWIDTH RIGHT PARENTHESIS)
  - 〉U+3009 (RIGHT ANGLE BRACKET)

**To Reproduce**
I am using the fonts Noto Sans Mono, Noto Color Emoji, and Deja Vu Sans Mono. I also notice these characters are not available in Symbols Nerd Font. 

**Expected behavior**
Expected the characters to render in standard fonts.

**Screenshots/Logs**
![screenshot](https://github.com/sigoden/aichat/assets/7788417/6841629e-e248-4678-8ff0-e8f8e2cce1de)

**Environment (please complete the following information):**
- os version: Arch
- aichat version: 0.10.0
- terminal version: urxvt 9.31

**Comment by xytroyzy** [comment]
I think this is probably your terminal settings.  Deja Vu Sans Mono renders perfectly here. You'll want to be sure to be running a terminal that can display those characters.

`$ echo $TERM
xterm-256color

$ echo $LANG
en_US.UTF-8`

**Comment by sigoden** [comment]
@xytroyzy provided a great answer.

**Comment by ntippie** [comment]
```
$ echo $TERM     
rxvt-unicode-256color
$ echo $LANG
en_US.UTF-8
$ fc-list ':charset=3009 ff09'
/usr/share/fonts/noto/NotoSansNewTaiLue-Bold.ttf: Noto Sans New Tai Lue:style=Bold
/usr/share/fonts/noto/NotoSansNewTaiLue-Regular.ttf: Noto Sans New Tai Lue:style=Regular
/usr/share/fonts/noto/NotoSansNewTaiLue-Medium.ttf: Noto Sans New Tai Lue,Noto Sans New Tai Lue Medium:style=Medium,Regular
$ pacman -Qqe | grep -E 'ttf|fonts' 
gnu-free-fonts
noto-fonts
noto-fonts-emoji
ttf-dejavu
ttf-inconsolata
ttf-nerd-fonts-symbols
ttf-nerd-fonts-symbols-mono
```

As you can see I have a number of Arch font packages installed and the only font that has both characters is NotoSansNewTaiLue, a font in the Southeast Asian New Tai Lue script.

**Comment by ntippie** [comment]
```
$ echo $TERM     
rxvt-unicode-256color
$ echo $LANG
en_US.UTF-8
$ fc-list ':charset=3009 ff09'
/usr/share/fonts/noto/NotoSansNewTaiLue-Bold.ttf: Noto Sans New Tai Lue:style=Bold
/usr/share/fonts/noto/NotoSansNewTaiLue-Regular.ttf: Noto Sans New Tai Lue:style=Regular
/usr/share/fonts/noto/NotoSansNewTaiLue-Medium.ttf: Noto Sans New Tai Lue,Noto Sans New Tai Lue Medium:style=Medium,Regular
$ pacman -Qqe | grep -E 'ttf|fonts' 
gnu-free-fonts
noto-fonts
noto-fonts-emoji
ttf-dejavu
ttf-inconsolata
ttf-nerd-fonts-symbols
ttf-nerd-fonts-symbols-mono
```

As you can see I have a number of Arch font packages installed and the only font that has both characters is NotoSansNewTaiLue, a font in the Southeast Asian New Tai Lue script.

@sigoden Sorry to tag you but could you respond or reopen to prevent another issue?

**Comment by sigoden** [comment]
Use `〉`  as a prompt indicator is following a famous shell: [nushell](https://www.nushell.sh/). 

This project has been going on for almost a year, and you're the first one to report this issue. It suggests that few people have encountered this problem. It's likely an issue with your terminal.

I will not choose any other character.

You can try installing all the Noto fonts to see if it resolves the issue
```
pacman -S noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra
```

**Comment by xytroyzy** [comment]
Hey @ntippie, check this:

https://bbs.archlinux.org/viewtopic.php?id=221329

At the very least, it's got some troubleshooting tips that might help.

To answer your earlier question: none of the Deja fonts are returned with `fc-list ':charset=3009 ff09' | grep -i Deja`
And yet, it renders in my terminal using DejaVu Sans Mono both in aichat and `echo -e '\u3009'`

Charset stuff isn't my jam so I'll bow out now but feel to tag me or whatever if you think I can help further.

**Comment by David-Else** [comment]
@ntippie Did you ever get this sorted? plz see my issue https://github.com/sigoden/aichat/issues/248

**Comment by ntippie** [comment]
@David-Else I wasn’t able to find a way to fix other than adding fonts to my terminal font fallback, and also couldn’t identify a common font that had both symbols. (Even Symbols-Nerd-Font did not.)

Some terminal emulators add their own symbols (like pipes, borders, etc), and I believe that is why some people are not experiencing this issue.

**Comment by David-Else** [comment]
@ntippie What do you think of https://github.com/sigoden/aichat/pull/259 as a solution? I am not keen on adding fonts to my terminal font fallback just to solve this, I would much rather the devs just chose a prompt that worked for everyone. I have the default Debian fonts and Symbols Nerd Font v3, these are very mainstream.

**Comment by ntippie** [comment]
@David-Else I agree. I think that PR is a fine solution. As you can see in this issue, the maintainer was awaiting additional opinions.
