### ISSUE TITLE
is there a way to use openAI/chatGPT without a API key - but as chatGPT plus user? 

### ISSUE THREAD

**Issue by ipstone** [sigoden/aichat#255]
I have this question for a while, do you have some ideas on this?

I am wondering if someone using rust, figured out some way to interact with the chatGPT plus user account, without using the API key (as a chatGPT user, it seems paying twice? - pay for API and at the same time pay for chatGPT plus user account?)

Thanks

**Comment by xsigk** [comment]
try https://github.com/gngpp/ninja
