### ISSUE TITLE
aichat is configured to use gpt-4 but it is using gpt-3

### ISSUE THREAD

**Issue by sergeyka** [sigoden/aichat#256]
<img width="316" alt="image" src="https://github.com/sigoden/aichat/assets/1651493/5cdcdea2-0c2e-4ef8-8f41-2a2d38b9c1d3">

**Environment (please complete the following information):**
- os version: MacOS 14.1 (23B74)
- aichat version: 0.11.0

config.yaml contains:
api_key: (paid openai key)
save: true
model: openai:gpt-4

**Comment by sigoden** [comment]
see #142  
GPT-4's answer has always been this
