### ISSUE TITLE
Piping a file on macOS often results in an error

### ISSUE THREAD

**Issue by ahmedre** [sigoden/aichat#257]
**Describe the bug**
Thank you for building aichat!

I am running into a strange issue - if I do something like (apologies for the basic example):

```shell
cat file | aichat -r shell "Give me the number of lines in each file"
```

I get an output of:

```
⠋ Generating   Failed to initialize input reader

Failed to send ReplyEvent::Done

Caused by:
    sending on a disconnected channel
```

If, on the other hand, I am to run:

```shell
aichat --file o -r shell "Give me the number of lines in each file"
```

I correctly receive an output.

**To Reproduce**
Pipe something to `aichat` on macOS.

**Expected behavior**
Expect it to behave the same as using `--file`.

**Screenshots/Logs**
![CleanShot 2023-12-02 at 23 05 55@2x](https://github.com/sigoden/aichat/assets/47771/2d61fd36-c46b-496b-b0bc-6ebab729458c)

**Environment (please complete the following information):**
- os version: macOS 14.1.2
- aichat version: 0.11.0
- terminal version: Kitty 0.31.0

**Additional context**

- The shell role is the same as the one on the wiki.

**Comment by jacobaraujo7** [comment]
Same problem

**Comment by David-Else** [comment]
I am having a problem in Kitty on Linux that might be related.

```
$ aichat -s example
Welcome to aichat 0.11.0
Type ".help" for more information.
example）          
```
```
$ echo "hello" | aichat -s example
Not found session 'example'
```
I am getting the same result with any type of piping, it seems broken. I can't seem to add any session when piping, the basic command works OK:
```
echo "hello" | aichat
Hello! How can I assist you today?
```
It is version:
```
$ aichat --version
aichat 0.11.0
```

**Comment by David-Else** [comment]
> @David-Else Cmmand mode can use only existing sessions. That's how it's designed. When launch aichat with `-s example`, it just create a new empty session.

But command mode is not using existing sessions when piping is used. I have a session called `test`:

```
$ aichat -s test
Welcome to aichat 0.11.0
Type ".help" for more information.
test）               
```
works fine, but with piping it does not open the session:

```
$ echo 'hello' | aichat -s test
Hello! How can I assist you today?
david@mycomputer:~$ 
```

An example from the [README ](https://github.com/sigoden/aichat#command) implies that it should work:

```
cat config.json | aichat -s i18n             # Read stdin with a session
```

**Comment by David-Else** [comment]
@sigoden Sorry about that! I have deleted the comments here and opened a new issue as requested.
