### ISSUE TITLE
Command mode is not opening an existing sessions when piping is used

### ISSUE THREAD

**Issue by David-Else** [sigoden/aichat#261]
I have a session named `test` which I can initiate using the following command:

```bash
$ aichat -s test
Welcome to aichat 0.11.0
Type ".help" for more information.
test）
```

This command functions correctly. However, when I attempt to open the session using piping, it does not work as expected, the session does not open and I return to the command prompt:

```bash
$ echo 'hello' | aichat -s test
Hello! How can I assist you today?
david@mycomputer:~$
```

According to an example provided in the [README](https://github.com/sigoden/aichat#command), this functionality should be operational:

```bash
cat config.json | aichat -s i18n # Read stdin with a session
```

**Environment details:**
- Operating System version: Debian 12
- aichat version: 0.11.0
- Terminal emulator version: kitty 0.26.5

**Comment by sigoden** [comment]
Aichat will only enter REPL mode when there is no input.
```
echo hello | aichat     # command mode
aichat hello            # command mode
aichat                  # repl mode
```

If you want to use file in session, please use `.file` command

```
Usage: .file <file>... [-- text...]

.file message.txt
.file config.yaml -- convert to toml
```

**Comment by David-Else** [comment]
Thanks for the updated info, but it does not explain what the following from the README does:

```
cat config.json | aichat -s i18n # Read stdin with a session
```

Maybe I just not understanding properly, thanks for the amazing project!

**Comment by David-Else** [comment]
Thank you, now I understand.
