### ISSUE TITLE
`.file` command does not work for binary file

### ISSUE THREAD

**Issue by z-gong** [sigoden/aichat#268]
I'm using `aichat 0.11.0` and `gpt-4` model to process a image file.
```
.file xxx.png -- message
```
However, `aichat` compains that the stream did not contain valid UTF-8.

If I attach a text file instead of a image file, then the message can be processed properly.

**Screenshots/Logs**
![image](https://github.com/sigoden/aichat/assets/379616/ddab34ca-eca7-4923-b5de-c6a819912c20)

**Environment (please complete the following information):**
- os version: WSL Ubuntu 20.04
- aichat version: 0.11.0

**Comment by David-Else** [comment]
Have you tried using `.model openai:gpt-4-vision-preview` instead? I uploaded an image file to that OK.

**Comment by sigoden** [comment]
1. After #270 merged, you can use an image with an uppercase extension. But now, you should change `.PNG` to `.png` to make it work.
2. Only models that support vision can use image files. Make sure that the model you use is `openai:gpt-4-vision-preview`.

**Comment by z-gong** [comment]
Thanks for the explanation. It works now with lowercase extension name and GPT4V model.
So this `.file` command is designed only for image files working with GPT4V?
The GPT4 model is able to process different file types, like `docx` or `pdf`. Is there any way to use it with `aichat`?

**Comment by sigoden** [comment]
Currently,  no api from openai supports docx or pdf.
