### ISSUE TITLE
Custom REPL prompt

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#279]
Is it possible to have a custom REPL prompt, in order to, for exemple see the current model and role we use in a aichat terminal ?

```
mistral:mistral-medium > python$ ...
```

(also I found that the difference in the last character use to identify session and non-session terminal hard to distinguish compared to older versions of aichat. )

Many thanks,
love this program.

**Comment by sigoden** [comment]
Three is no easy way to custom prompt in aichat. Let's me explain.

Current aichat have three types of prompt:

| state   | screenshot                                                                                      |
| :------ | :---------------------------------------------------------------------------------------------- |
| normal  | ![image](https://github.com/sigoden/aichat/assets/4012553/9d405aac-8ea0-4336-b84c-9b3d8f526f45) |
| role    | ![image](https://github.com/sigoden/aichat/assets/4012553/5a335a25-aad2-437f-b373-8cf44e89b4dc) |
| session | ![image](https://github.com/sigoden/aichat/assets/4012553/3ece0bc6-d38e-4be8-a89f-bbb21f6c2938) |


If we want to support custom prompts, three types need to be provided. And color is also need to be supported.

This is the most basic functionality. Later, some users may also require the realization of more variables (such as the current model, wrap settings, whether auto_copy is enabled).

This will make it difficult for users to customize prompts.

The current prompt is fine and not difficult to distinguish; it is probably just a matter of habit.

If anyone has a better solution, please give feedback.

**Comment by dtrckd** [comment]
I'll find more intuitive and nice to have a configuration like something this : 

```yml
eop_session = ")"
eop_default = ">"
repl_prompt = "{session%: }{model%>} {role}{eop}" 
# the characters after % only appears if the preceding variable exists.
```
I understand that then, other setting sshould be exposed as well (like temperature if one want to have it...), but having at least the session, model and role names available wiill be great. (leaving the color tuning for later enhancement...)

---

In my terminal (kitty), the terminal character looks like this for session and no-session (the ">" icon is not sharp )

![image](https://github.com/sigoden/aichat/assets/8218696/39c0b55c-e144-4591-ac2b-05d98cb320bd)
