### ISSUE TITLE
.copy copies nothing on linux wayland

### ISSUE THREAD

**Issue by kiil** [sigoden/aichat#286]
**Describe the bug**
When using the REPL, the `.copy` command does not copy the last reply to the clipboard.

**To Reproduce**
enter the REPL and chat with any model, then give the `.copy` command and see that it does not copy the last reply to the clipboard.

**Expected behavior**
I expected the last reply to be copied to the clipboard.

**Environment (please complete the following information):**
- os version:  Manjaro sway, Linux x86_64 - wayland
- aichat version:  0.12.0
- terminal version: foot

**Comment by sigoden** [comment]
I don't have a machine running wayland alone, can you help me test it? @kiil

**Comment by kiil** [comment]
@sigoden - Yes, I will do my best. How do I test the fix?

**Comment by sigoden** [comment]
Thank you @kiil 

1. If you have Cargo installed, then build from source.
```sh
git clone https://github.com/sigoden/aichat
cd aichat
cargo run
```

[aichat.tar.gz](https://github.com/sigoden/aichat/files/13785661/aichat.tar.gz)

2. if you have no cargo installed, use the binary I just uploaded
```sh
wget https://github.com/sigoden/aichat/files/13785661/aichat.tar.gz
tar -xf aichat.tar.gz
./aichat 
```

**Comment by kiil** [comment]
It copies to the clipboard now. Thanks for the fix :)
