### ISSUE TITLE
aichat not present in Arch Repos. 

### ISSUE THREAD

**Issue by madsamjp** [sigoden/aichat#287]
https://archlinux.org/packages/?sort=&q=aichat&maintainer=&flagged=

Readme suggests aichat can be installed using `pacman -S aichat`. As it doesn't exist in the Arch repos, it cannot be installed using pacman. aichat is present in the AUR, but that requires a different method for installation (for instance using a helper such as yay).

**Comment by sigoden** [comment]
https://aur.archlinux.org/packages/aichat

**Comment by sigoden** [comment]
fix [e198e35](https://github.com/sigoden/aichat/commit/e198e35a2805d13c0c25b9bd87fb4f59ba04bf47)
