### ISSUE TITLE
Add option to display cost information

### ISSUE THREAD

**Issue by itsFrank** [sigoden/aichat#289]
First off, thank you for making this tool, I really like the approach to roles and session management, having the ability to save sessions built-in is particularly awesome!

**Is your feature request related to a problem? Please describe.**
I would like to be able to see how much money I am spending. Especially as sessions get longer, with pricey models like gpt4 the cost can increase rather quickly. Having feedback about cost is very important for me.

**Describe the solution you'd like**
My current preferred ai cli, [gpt-cli](https://github.com/kharvd/gpt-cli), shows both the cost of the previous query and the cumulative cost since starting repl mode. This helps me keep track of how much I am spending and is also a great signal to start a new session when the cost of the last message becomes too big.

Screenshot:
 
<img width="1048" alt="Screen Shot 2023-12-28 at 10 44 18 AM" src="https://github.com/sigoden/aichat/assets/7297152/5d5d0fb8-bef0-4c83-824b-e06d0a06608f">

**Describe alternatives you've considered**
Well one alternative is to simply not do this, which would probably lead to me sticking with gpt-cli, even though I prefer the rest of the UX provided by this tool.

I don't have a preference if it's on by default or not

**Comment by sigoden** [comment]
see #258
