### ISSUE TITLE
.copy command not working in WSL2 terminal

### ISSUE THREAD

**Issue by mortenscheel** [sigoden/aichat#29]
Running aichat in Ubuntu 22.04 on Windows WSL2, the `.copy` command doesn't work.
I suppose copypasta thinks it's running a standard Linux machine, but is there some kind of workaround?
In order to write to the Windows clipboard from WSL, you can pipe the contents to `clip.exe` which is in PATH.

**Comment by sigoden** [comment]
It also doesn't work on ssh remote servers.

The original intention of the `.copy` command is that the rendered markdown is changed (like ` ``` ` become `───`) and cannot be copied directly.

I have just refactored the markdown rendering engine #26 , and the output markdown is only highlighted, not changed. Can be copied directly from the terminal screen.

So prepare to abandon`.copy` command in new release.

**Comment by sigoden** [comment]
As pr #30 merged, I close this issue

**Comment by omaru-ok** [comment]
@sigoden i would like to inform a point too 
that in window , there is brilliant CLI package manger 
[scoop](http://scoop.sh/) 
it would be better if u can post aichat there for easy acces to updates and installtion 

:)
