### ISSUE TITLE
error sending request for url (https://api.openai.com/v1/chat/completions): error trying to connect: tls handshake eof

### ISSUE THREAD

**Issue by huangbqsky** [sigoden/aichat#290]
> aichat start
Failed to get answer

Caused by:
    error sending request for url (https://api.openai.com/v1/chat/completions): error trying to connect: tls handshake eof

**Comment by sigoden** [comment]
This is not a aichat issue. Your machine is using an old insecure TLS version that aichat refuses to accept. 

try to run with curl, do throw same error?
```
curl -X POST https://api.openai.com/v1/chat/completions
```

do you use a proxy?

@huangbqsky
