### ISSUE TITLE
Caused by: You exceeded your current quota, please check your plan and billing details. For more information on this error

### ISSUE THREAD

**Issue by huangbqsky** [sigoden/aichat#291]
Failed to get answer

Caused by:
    You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.

**Comment by sigoden** [comment]
![image](https://github.com/sigoden/aichat/assets/4012553/8ef5806b-188b-4577-810b-091bd4f208a2)

Please follow openai's instructions.

**Comment by rinshadka** [comment]
HI

same issue for me too,

![image](https://github.com/sigoden/aichat/assets/40381766/eb8ed18f-5537-4679-8133-700ccbb9f7ec)


But my key is a newly created under openai plus plan

**Comment by rinshadka** [comment]
> HI
> 
> same issue for me too,
> 
> ![image](https://private-user-images.githubusercontent.com/40381766/304653938-eb8ed18f-5537-4679-8133-700ccbb9f7ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDc5MjEsIm5iZiI6MTcwNzkwNzYyMSwicGF0aCI6Ii80MDM4MTc2Ni8zMDQ2NTM5MzgtZWI4ZWQxOGYtNTUzNy00Njc5LTgxMzMtNzAwY2NiYjlmN2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDEwNDcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZGU0YTM0NGNjZWQ2NWVjNTc3MGI5MTYyYjk2NDY5NzI3OTY0YjNjMTkwZDNjYjRkNDhmZjI5MDUzZGY3NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MZZRhNGh8lfPaeYM4RMSghDflSFKSRPnWEPjDXhaPKs)
> 
> But my key is a newly created under openai plus plan

I got this issue resolved by creating a new chatGPT account and making use of that KEY for configuring further.

**Comment by paulodiovani** [comment]
I still have this issue, 
while api keys work fine on other apps, it keeps giving me this error for `aichat`
