### ISSUE TITLE
Add a .clear command to clear the session history

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#293]
When you want to stay in a session, but reset the history, you need to exit the session, click Y/N to save, then re-enter a session. So you need to type 2 command, plus click on a Y/N dialog. 

It might be more convenient to just type one command, like .clear to do that job seamlessly.

**Comment by sigoden** [comment]
Clearing session history is not a common operation. Aichat will not support it.

**Comment by dtrckd** [comment]
Thank you for you're response.

Nevertheless, I so often find myself in this situation where I just want to restart/reset/clear a conversation to start a new one, that I wonder if I am using the wrong pattern or if I just need to got used to the triple input interaction...

I'd be curious to know how you guys handle this ?

**Comment by dtrckd** [comment]
:heart:
