### ISSUE TITLE
Lots of space between end of multiline string and response

### ISSUE THREAD

**Issue by jacksongoode** [sigoden/aichat#294]
**Describe the bug**
There's an issue that in some cases where a lot of code is pasted into a multi-line prompt. At the end or conclusion of that multi-line prompt there will be a lot of new lines created before the chat response begins.

**To Reproduce**
Paste some code, write some comments below in a multi-line message.

**Expected behavior**
No new lines created after the input message and between the response.

**Screenshots/Logs**
<img width="455" alt="image" src="https://github.com/sigoden/aichat/assets/54308792/54fc726b-b382-4c61-8306-0b07e1acec3a">

**Environment (please complete the following information):**
- os version: macOS (13.6)
- aichat version: 0.12
- terminal version: WezTerm (latest)

**Comment by sigoden** [comment]
Waiting for upstream to fix the issue nushell/reedline#703

**Comment by chiefMarlin** [comment]
@sigoden seeing how nobody @nushell/reedline has replied since january, do you think there is another fix available for this ?

**Comment by sigoden** [comment]
nushell/reedline#703  has been fixed. When the new version of reedline is released, this problem will be resolved.

**Comment by sigoden** [comment]
c4c948a upgraded reedline to [version 0.32](https://github.com/nushell/reedline/releases/tag/v0.32.0) which includes the fix.
