### ISSUE TITLE
Using session with individual commands

### ISSUE THREAD

**Issue by 0x766C70** [sigoden/aichat#299]
**Is your feature request related to a problem? Please describe.**
I only can use session in REPL mode

**Describe the solution you'd like**
I'd like to use session with individual commands:
`aichat -s test -r test_role "I have a duck into my pocket"`
`> nice`
`aichat -s test -r test_role "what is in my pocket"`
`> you have a duck`

I have notice that into the yaml session file, only the first command and answer are logged.
I's like the second command were not attached to the session 

I may have missed smth ?

Et of course, big thanks for this amazing tools !!

**Comment by sigoden** [comment]
see https://github.com/sigoden/aichat/issues/184#issuecomment-1785423404

**Comment by 0x766C70** [comment]
Thanks, I have missed this issue !! Sry
