### ISSUE TITLE
Support amazon bedrock models?

### ISSUE THREAD

**Issue by psanford** [sigoden/aichat#300]
### Please confirm whether the following requirements are met:

- [ X] Must have a REST/HTTP API.
- [ X] Must be publicly accessible. It cannot require application review or have regional restrictions. A beta version is acceptable.
- [ X] Must not open-source. Open source models can be used through LocalAI and do not need to be supported separately.
- [ X] Must not act as an agent or proxy for other platforms.

> Tip: If the API of the new model is compatible with OpenAI's API, it can be used through localai client.

### Please provide the following documents or links:

- API Documentation (required)

https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InvokeModel.html

- TOKEN calculation document (optional)

**Comment by sigoden** [comment]
Many models in amazon-bedrock do not support context-aware conversations by appending an array of past messages.
Different models have different request bodies, which is difficult to implement.

So I will not support amazon bedrock models.

But you can use amazon-bedrock with litellm.

- Install litellm (`pipx install litellm`)
- Start litellm. LiteLLM will then start listening on port 8000
```
$ export AWS_ACCESS_KEY_ID=
$ export AWS_REGION_NAME=
$ export AWS_SECRET_ACCESS_KEY=

$ litellm --model bedrock/anthropic.claude-v2
```
- Configure aichat to use it (note the ollama/ prefix on the model name):
```
- type: localai
  api_base: http://localhost:8000/v1
  api_key: xxx
  models:
    - name: bedrock/anthropic.claude-v2
```
