### ISSUE TITLE
Optional api_base parameter for openai type client

### ISSUE THREAD

**Issue by qcts33** [sigoden/aichat#301]
I hope it's possible to give the openai clients the optional `api_base` parameter. 
I can't access the openai interface directly, so I need to access it through a service like [openrouter.ai](https://openrouter.ai/docs#quick-start). Those service provide the same interface as the offical openai endpoint, thus provide a `api_base` parameters should be sufficient.

**Comment by sigoden** [comment]
#302 implements the feature.

The `model` parameter in  [openrouter.ai](https://openrouter.ai/docs#quick-start) is different from openai, changing `api_base` don't work. Please use `localai` client instead.
