### ISSUE TITLE
Clipboard integration with termux on android

### ISSUE THREAD

**Issue by Mamut3D** [sigoden/aichat#320]
**Describe the bug**
First of all, thanx a lot for termux package 😀. Bug: When yoy
u want to use a .copy feature to clipboard i get the following
'''
Failed to copy the last output

Caused by:
    No available clipboard
'''

**To Reproduce**
Enter Reply mode, ask question and pass .copy command

**Expected behavior**
Copy last message to android clipboard possibly via termux-clipboard-set command or at least allow to pass last message to other cli util

**Screenshots/Logs**
Failed to copy the last output

Caused by:
    No available clipboard

**Environment (please complete the following information):**
- os version: android 12
- aichat version: 0.12.0
- terminal version: termux

**Comment by sigoden** [comment]
No way to implement clipboard functionality on termux safely.
Termux-clipboard-set depends on termux-api which needs to be installed.

**Comment by sudomain** [comment]
Good day. I was also going to request this. I'm curious why is it not safe? I can live with piping into termux-clipboard-set for one-off prompts like so:
`aichat hi | termux-clipboard-set`
copy/pasting in the Termux UI is painful if the terminal scrolls, but it's doable.

**Comment by sigoden** [comment]
see https://github.com/sigoden/aichat/pull/321#issuecomment-1962397669

**Comment by igorlima** [comment]
Hi there! 👋 I'm here to contribute with one more experience with copying and pasting in the Termux environment.

After exploring the repository issues, I understand there have been some discussions about this topic. Here's my current workflow that's working okay with AICHAT in Termux:

1. I use Vim as my primary editor with [the `vim-repl` plugin](https://github.com/sillybun/vim-repl)
2. This plugin lets me:
   - send commands to the terminal while staying in my current buffer
   - open a terminal inside Vim
   - easily copy and paste between Vim buffers
   - <details><summary><i><sup><sub>illustrations...</sup></sub></i></summary>
      
      | image A | image B | image C|
      | :---: | :---: | :---: |
      | ![image](https://github.com/user-attachments/assets/7bc28c5c-e633-4c3f-a6fd-20b551b7a010) | ![image](https://github.com/user-attachments/assets/bc84870f-b5d2-40d6-b2f2-ef9bd54e3338) | ![image](https://github.com/user-attachments/assets/9add2eb3-cfb0-4131-bbd6-0e295abe6404) |
      
      </details>

I'm happy to share an alternative workflow and want to hear how others handle similar scenarios, too! 😊

Additionally, I have another suggestion regarding the `termux-clipboard-set` proposal: What if we made clipboard interaction configurable in the [AICHAT YAML config file](https://github.com/sigoden/aichat/blob/bfb87a6669f61eaa80c6822c88a4a60efae106b7/config.example.yaml)? Users could specify their preferred clipboard command _(like `pbcopy` or `termux-clipboard-set`), [similar to the earlier PR](https://github.com/sigoden/aichat/pull/321)_ but more flexible. This way, everyone could use their preferred clipboard CLI tool!

What do you think about this approach? Looking forward to more thoughts!
