### ISSUE TITLE
Add PawanOsMan support

### ISSUE THREAD

**Issue by backdoor-dev-official** [sigoden/aichat#325]
The PawanOsMan api is free, you just have to go to the discord and you can receive a token. You should also be able to use the normal openai models, but those are paid and in themselves allow the use of your own good quality multi-language models, approximately 50 to 60 languages in which you can generate text in addition to having models specialized in roleplay and all completely free. In fact, right now it is compatible but it would be rough. As I did it, I modified the openai.rs of the code a little, I put the endpoint that It's not very different and I changed the name of the models and that's it. It worked although I possibly broke more than one thing because of that but it was able to compile and run without problems so I think it would be a good addition and not that difficult to do (I think) Thanks for your time. And this is the link to the PawanOsMan documentation repository, although I recommend you enter the discord because it is a little outdated.

https://github.com/PawanOsman/ChatGPT

**Comment by sigoden** [comment]
The PawanOsMan is openai proxy, just use `openai` client.
```
clients:
  - type: openai
    name: PawanOsMan 
    api_key: xxxx
    api_base: https://api.pawan.krd/v1
```

**Comment by backdoor-dev-official** [comment]
Oh thanks and sorry for the mistake
