### ISSUE TITLE
Feature Request: Sliding Window Context

### ISSUE THREAD

**Issue by ahmedre** [sigoden/aichat#329]
Thank you for the awesome work on aichat!

I know this was briefly discussed in #280, but I wanted to re-open it to try to make the case for it. I understand the solution of using an LLM with a larger context, but the use case I have (where I ran into this issue and why I am making this request) is a bit different.

I tried once to use aichat with the coder role to write some code. As I'd get solutions, I'd ask clarifying questions, ask for changes, etc. About 2 or 3 revisions in, I am exceeding the token limit. For any similar types of work (debugging / writing code, or having aichat open in a terminal window for just asking questions throughout the day), the limits quickly become an issue.

In this case, I neither need nor want the whole history - it's more like having an on-going chat with a friend, where even though all the history is there, you really are usually only talking about the recent messages sent from either one of you, and aren't referring to the messages sent from x months back.

Please consider adding a sliding window for context.

Thanks!

**Comment by sigoden** [comment]
I wonder if the results will still be accurate if sliding Window is enabled in sessions?

And which sliding window strategy will have the best results?
- Only the most recent conversation
- Only the last n conversations
- Only the earliest m conversations and the last n conversations, discard the middle ones

**Comment by ahmedre** [comment]
My first thought is "the last n messages," where n is variable and is determined by the number of tokens so that it remains within the limit (so if your messages are super short, n might end up being large, but if the recent messages are super long, then n might end up being very small).

You'll lose accuracy for things needed for context that are past the window, but that would happen anyway (since without this type of sliding window, the approach has to be to run a new session of aichat, which by definition will clear the history).
