### ISSUE TITLE
--execute ignores prompt?

### ISSUE THREAD

**Issue by kumraa-1** [sigoden/aichat#330]
It seems like --execute somehow overrides the prompt and doesn't read out OS-Data so it's not very helpful.

```
r@Nobara-Desktop:~/.config/aichat$ aichat --execute --role shell "update system"
sudo apt-get update && sudo apt-get upgrade -y
> [e]xecute, [d]escribe, [a]bort:  a

r@Nobara-Desktop:~/.config/aichat$ aichat --role shell --execute "update system"
sudo apt update && sudo apt upgrade -y
> [e]xecute, [d]escribe, [a]bort:  a

r@Nobara-Desktop:~/.config/aichat$ aichat --role shell "update system"
sudo dnf update --refresh
```

The role shell is basically your default config with a line added to be specific on Fedora 39.

**Comment by sigoden** [comment]
This is expected behavior.

The `--execute` has a builtin role [`__execute__`](https://github.com/sigoden/aichat/blob/b2f86f2899b79b291eb56435f99402509105b7ec/src/config/role.rs#L24).  The builtin role is aware OS and SHELL.

Run following command to inspect the builtin  role.
```
aichat --execute --info
```

@kumraa-1

**Comment by kumraa-1** [comment]
Ah I see, the model doesn't seem to know nobara. Thanks for the quick help! Is there a way to override the execute role?

**Comment by sigoden** [comment]
I will make the override of the built-in role available.

**Comment by sigoden** [comment]
#331 solved the problem.
