### ISSUE TITLE
New Claude 3 endpoints

### ISSUE THREAD

**Issue by jacksongoode** [sigoden/aichat#335]
https://www.anthropic.com/news/claude-3-family
`claude-3-opus-20240229` and `claude-3-sonnet-20240229` both at 200K

**Comment by ahmeteid7** [comment]
all these platforms are paid, even gemeni has limit(90 days)free,  can you  add to the configration the option of cookies of the gemeni app and bing ai app from the browser to use?

**Comment by ahmeteid7** [comment]
Thank u very much
