### ISSUE TITLE
是否可以自定义默认的prompt

### ISSUE THREAD

**Issue by sparkssssssss** [sigoden/aichat#352]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/sigoden/aichat/issues) before creating one.

**Describe the bug**
终端下,答复都是md语法,颜色显示异常,导致很难阅读,
可以进aichat的shell中设置role,但是一般使用都是在bashshell下使用.
是否可以定义默认prompt,让bot不要使用md语法

**To Reproduce**
随便让写一段代码
![Snipaste_2024-03-13_19-18-32](https://github.com/sigoden/aichat/assets/14211550/e7be4995-6928-4aaf-b666-a78600b0bd97)

**Expected behavior**
期望可以自行设置默认的prompt,让其不使用md语法

**Screenshots/Logs**

**Environment (please complete the following information):**
- os version: [e.g. Ubuntu 20.04]
- aichat version: [e.g. 0.9.0]
- terminal version: [e.g. GNOME Terminal 3.44.0]

**Additional context**

**Comment by sigoden** [comment]
No, try the following solutions

1. Use `alichat -r shell`, maybe set it as a shell alias
2. Change to light theme through the `--light-theme` option or `light_theme: true` config
