### ISSUE TITLE
Add a '.clear session' command or support for aliases ?

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#354]
Good evening,

Today, we have a `.clear messages` to clear the message history, which is really convenient.

But if we are in a session and within a role, and we want to exit it, we need two actions:  1° clear the message, and 2° exit the role (note that there is little inconsistency here, after clearing the messages, the autocompletion, does not propose you to '.exit role').

So an idea to ease that workflow is to add a  `.clear session` that will at the same time, clear the session messages and exit the role.

One another idea, instead of adding too many special, and potentially confusing commands, is to provide the ability for the users to create aliases (This could open the door to chain generations too!).

For my exemple, it could be something like the following:
- alias ".clear session"=".clear messages >> .exit role"

**Comment by sigoden** [comment]
I will fix the missing `.exit role` completion after `.clear messages`.
I won't add `.clear session` as it may be confused with `.exit session`.
I won't support aliases because AIChat has less than 10 commands so it's not worth it.

**Comment by dtrckd** [comment]
Hop,

There is a related issue here (tell me if you prefer that I open a new one @sigoden )

`.clear messages` delete the "system" prompt when you are in a role. It should not be the case as `.clear messages` does not clear the role as discussed.

**Comment by sigoden** [comment]
`.clear messages` will not remove the system prompt (which will be automatically generated from the role), please build from the latest commit and try again. @dtrckd

**Comment by dtrckd** [comment]
> I will fix the missing `.exit role` completion after `.clear messages`.

.exit role seems to not be available (in 0.19.0), even if the session is cleared/empty.
