### ISSUE TITLE
Cannot print output

### ISSUE THREAD

**Issue by 0x9bb1** [sigoden/aichat#36]
When I update to version 0.4.0, after I enter the problem, I can't see the output. But I found the response in the `messages.md`.
- OS: `Windows 10`
- shell: `powershell`
- terminal : `alacritty`
- version: `aichat 0.4.0`

**Comment by sigoden** [comment]
Is the buggy version compiled from git source code? 

I downloaded v0.4.0 from github release and found no problems.
