### ISSUE TITLE
--session for non-interactive mode

### ISSUE THREAD

**Issue by johnd0e** [sigoden/aichat#362]
```
  -s, --session [<SESSION>]  Create or reuse a session
```
In fact `--session` option help describes it's function in interactive mode.
In non-interactive it is not possible to create session:
```
Not found session 'my-session'
```
For pre-existing session it works, but only for reading (does not update the session file).

I propose:
- either to change `--session`'s behavior to create/update session file
- or add a complimentary option, like `--update`

**Comment by sigoden** [comment]
This is expected behavior.

I am not planning to change in the near future.

**Comment by johnd0e** [comment]
> This is expected behavior.

Then current help text is not quite true.

> I am not planning to change in the near future.

May I know the reasons behind that?

**Comment by sigoden** [comment]
The help text should be concise, there is not much space to describe more details, please understand.

https://github.com/sigoden/aichat/issues/184#issuecomment-1785423404  is the reason.

Is there something wrong with sessions in  REPL mode? Why insist on using modifiable sessions in command mode?

**Comment by johnd0e** [comment]
> https://github.com/sigoden/aichat/issues/184#issuecomment-1785423404 is the reason.

I can agree that roles-feature is essential (and certainly deserves mention in the help).
However, even when used interactively, it is not as seamless as it could be.
Consider the following workflow:
- I open the chat as continuation of some role-session.
- I continue conversation and then want to keep it for later.
- Aichat asks me if I want to save session. Indeed I do, but then it propose me that initial name.

So in this way it is easy to mess up, and overwrite my role-session just by mistake.

To my taste, the things would be more clear if we had special option name for `--role`.
- The file format can remain the same, allowing roles to be created from sessions.
- The key difference is that `--role` would create an anonymous session by default (which cal later be saved with any name).
- Additionally, both `--role` and `--session` options could be used together to start a named session.

> Why insist on using modifiable sessions in command mode?

Because I need to call aichat from another app, piping its output.

**Comment by chiefMarlin** [comment]
Im not sure its clear what it is that you want implemented, can you elaborate with some examples

**Comment by sigoden** [comment]
This can be further discussed in #371

**Comment by sigoden** [comment]
@johnd0e What you need is to add the `--save-session` option or use `save_session` config item.

**Comment by johnd0e** [comment]
@sigoden Thank you!
