### ISSUE TITLE
[feature request] Get api keys from password managers

### ISSUE THREAD

**Issue by gilcu3** [sigoden/aichat#366]
It would be nice to allow for executing a command to obtain secret keys. This way config files can be shared without revealing secrets, and data at rest remains secure.

**Comment by sigoden** [comment]
Aichat will not support this feature. 

All api keys can be provided through environment variables. see https://github.com/sigoden/aichat/wiki/Environment-Variables
You can use protected environment variables to accomplish this.
```sh
OPENAI_API_KEY=$(op get item aichat-apikeys  --field openai) aichat
```
