### ISSUE TITLE
allow enabling and disabling Gemini safety features in config

### ISSUE THREAD

**Issue by Deon588** [sigoden/aichat#367]
Not sure if it's already possible however I have not found a way to enable and disable Gemini safety features e.g. offensive content in Aichat.

If you are requesting support for the new model, goto [model-request](https://github.com/sigoden/aichat/issues/new?assignees=&labels=enhancement&projects=&template=model_request.md&title=).

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sigoden** [comment]
Could you explain why this feature is needed?

[The current `safetySettings`](https://github.com/sigoden/aichat/blob/4d52479545082254315171d6716ee9c3588f76f5/src/client/vertexai.rs#L263) are the least strict.

Stricter `safetySettings` or disabling it will only result in more requests becoming unresponsive. Does this make sense?

@Deon588
