### ISSUE TITLE
Custom session saving policy

### ISSUE THREAD

**Issue by sigoden** [sigoden/aichat#371]
### add `save_session` config item

```
save_session: null              # Ask whether to save the session when exiting the session
save_session: true              # Save the session automaticlly when exiting the session
save_session: false             # Do not ask or save automaticlly when exiting the session
```

### add `--save-session` cli option

```
aichat -s session02 --save-session 1 to 5, odd only  # Start a new session
aichat -s session02 --save-session to 7              # Continue the session
```

### add repl command `.set save_session`

Change global or session-scoped `save_session` config item
```
.set save_session true
```

### add repl command `.save sesion`

Save session manually
```
.save session
.save session new-name
```

**Comment by dtrckd** [comment]
It would be nice to disable auto-session saving as discussed. Thanks for projecting this.

However, I've found that most of the time we don't save the session because the data isn't valuable enough, except in certain cases. And when it happens you known you want to save the session. So in this case it would be nice to be able to explicitly save the session under the given name like `.save my-session-name`. 
Does it make sense ?

**Comment by sigoden** [comment]
@dtrckd  Why need a new repl command? 

If you have not thought about the purpose of the session, just use `aichat -s` or `.session` to open a  new temp session. When you exit the session, you will be prompted to name it.
![image](https://github.com/sigoden/aichat/assets/4012553/6d04ef34-ead1-426f-9ce4-d9bdcd02478a)

**Comment by dtrckd** [comment]
In the case where the default behavior is to **not save** the session on exit, so neither asking nor saving (which would be the option I'd use, if available).
The user should still have the possibility to save an interesting session, with a `.save [session-name]`.

I believe it should behave like `:w [file-name]` in vim : 
- if no session-name is given, it saves it to the current session name (or ask for name if it is a new one).
- else it saves it to the given session-name given.

**Comment by sigoden** [comment]
#370 add `save_session` config item to control whether sessions are saved automaticcly without asking when exiting the session.
#377 add seperate `save_session` config item to session. You can enable `save_session` for some sessions only.

I don't feel the need to add an extra `.save` command.

**Comment by sigoden** [comment]
all done.
