### ISSUE TITLE
Duplicate lines

### ISSUE THREAD

**Issue by chiefMarlin** [sigoden/aichat#376]
Hi
I noticed that for some responses with long lines, i am seeing duplicates on the terminal, however when .copy is ran and pasted, there is only 1 instance of the long line:

Line in terminal
<img width="1470" alt="Screenshot 2024-03-26 at 5 13 25 PM" src="https://github.com/sigoden/aichat/assets/96321026/e15af7e4-ccc0-43f7-bab6-f00fff66c5a0">

Pasted line when copied with .copy
```go
	if *action == "" || *dockerImage == "" {
		fmt.Println("Usage: go run main.go -action [load|save] -image <docker-image> -endpoint <s3-endpoint> -access-key <s3-access-key> -secret-key <s3-secret-key> [-use-ssl]")
		flag.PrintDefaults()
		os.Exit(1)
	}
```

I am using 0.14.0 commit 527da63.
This is on mac with default terminal app.

Chat was started like this

```bash
aichat
.model claude:claude-3-opus-20240229
.session
```

**Comment by sigoden** [comment]
I think the tab is the problem.

**Comment by chiefMarlin** [comment]
@sigoden thank you so much, i will try it.
