### ISSUE TITLE
Feature Suggestion: Allow role-specific configuration

### ISSUE THREAD

**Issue by XOKP** [sigoden/aichat#38]
I would like to suggest a new feature that allows users to assign specific configuration for each role. It would be great if we could specify different temperature settings for different prompts since some prompts might perform better with different temperatures.

For instance, when we write a story, it typically requires greater creativity; whereas, when we ask for a definition of terms, we typically require more formality.

**Comment by sigoden** [comment]
specify different temperature is reasonable.
