### ISSUE TITLE
Output is completely unreadable on black-on-white terminals (white text on white background).

### ISSUE THREAD

**Issue by dreirund** [sigoden/aichat#383]
**Describe the bug**  
I use white background, black text terminals, and the output is completely unreadable (white text on white background), screenshot:

---

![aichat-output-blackonwhite](https://github.com/sigoden/aichat/assets/1590519/45abdcb6-467f-425e-944e-5124077a1ac2)

---

**Expected behavior**  
Do not mess with colours at all by default, add options to specify colourscheme.

Regards!

**Comment by chiefMarlin** [comment]
Have you tried setting highlight to false ?

**Comment by sigoden** [comment]
please use light theme 
1. `aichat --light-theme`
2. add `light_theme: true` to config yaml

**Comment by dreirund** [comment]
> Have you tried setting highlight to false ?

Yes (option `-H`).

**Comment by dreirund** [comment]
> please use light theme 
> 1. `aichat --light-theme`
> 2. add `light_theme: true` to config yaml

That works.

But to not have users run into the truble in the first place, can you
make colouring off by default and only enable upon request by config
option or command line parameters?

That will also make it compatibl with dump terminals.

Regards!

**Comment by sigoden** [comment]
No, most user use dark theme by default.

**Comment by sigoden** [comment]
This is a light/dark theme issue, not a color issue. No color will make more people unhappy.
Most users don't think this is a problem

**Comment by peterhass** [comment]
Had the same issue as @dreirund and found this thread here. For me, the solution wasn't as easy since I'm switching my color scheme from time to time but I got something that works. Leaving it here in case somebody finds this thread in the future:

.zshrc:

```zsh
# tested with KDE plasma / gnome should be fine as well
function get_color_scheme() {
	scheme=$(
		gdbus call --session --timeout=1000 \
			--dest=org.freedesktop.portal.Desktop \
			--object-path /org/freedesktop/portal/desktop \
			--method org.freedesktop.portal.Settings.Read org.freedesktop.appearance color-scheme
	)

	case "$scheme" in
		'(<<uint32 1>>,)') echo "dark";;
		'(<<uint32 2>>,)') echo "light";;
		*) echo "default";;
	esac
}


function aichat() {
	color_scheme=$(get_color_scheme)

	if [[ "$color_scheme" == "light" || "$color_scheme" == "default" ]]; then
		AICHAT_LIGHT_THEME=true
	else
		unset AICHAT_LIGHT_THEME
	fi

	export AICHAT_LIGHT_THEME
	command aichat "$@"
}
```
