### ISSUE TITLE
Shell completions

### ISSUE THREAD

**Issue by sigoden** [sigoden/aichat#392]
Provide completions scripts for bash, zsh, fish, powershell and nushell.

**Comment by sigoden** [comment]
The completion script generated based on clap doesn't support the dynamic completion for options like `--model`, `--role` and `--session`.

If you need such features, you can try [argc-completions](https://github.com/sigoden/argc-completions).


https://github.com/sigoden/aichat/assets/4012553/2dfa993a-aa81-4e98-920d-7e034e984d04

**Comment by Konfekt** [comment]
[Here's] a ZSH completion

**Comment by sigoden** [comment]
@Konfekt very nice, could your submit a PR?

**Comment by ezuk** [comment]
With the fish one (added to my config.fish verbatim) I get:

```
> aichat complete: no auto <max-width>: contains a syntax error          (base)
complete: Expected a string, but found a redirection
no auto <max-width>
        ^
```

Any idea?

**Comment by Konfekt** [comment]
Maybe the escaping of colons is dispensable in fish? (For ZSH it was not, but that's perhaps a particularity of the ZSH completion script syntax.)

**Comment by Konfekt** [comment]
Piggybacking, [some commands](https://gist.github.com/Konfekt/5748fbe2d72749ab9b2ea8362f703a7e) to pipe/edit lines to/by aichat in Vim.
