### ISSUE TITLE
[Feature Request] chat/session mode (i.e. back and forth conversation)

### ISSUE THREAD

**Issue by int** [sigoden/aichat#40]
Currently, aichat behaves in a one-off request/response manner -- it has no "context" info.

e.g.

```
> show me some haskell code to print fibonacci numbers
Here is the Haskell code to print the first n Fibonacci numbers:

────────────────────
fib :: Int -> [Int]
fib n = take n fibList
  where fibList = 0 : 1 : zipWith (+) fibList (tail fibList)

main :: IO ()
main = do
    putStrLn "Enter the number of Fibonacci numbers to print:"
    n <- readLn
    putStrLn $ "The first " ++ show n ++ " Fibonacci numbers are: "
    print $ fib n
────────────────────

> now convert it to python
Sorry, I'm an AI language model and I would need to see the original code to convert it to Python. 
Can you please provide more context or the original code you would like to convert?
```

We have `chat` in our name, so it'd be nice if it can mimic a real chatting bot (a la ChatGPT) who can have a conversation.  Implementation-wise (from a high level view), we can just extend the `messages` sent to the OpenAI API with every input & output we've got so far.

As for the UI, we probably can make it default in interactive mode, while adding some extra commands  like `.clear session`,  `.mode chat`, etc.

**Comment by sigoden** [comment]
AIChat use [`gpt-3.5-turbo`](https://platform.openai.com/docs/guides/chat).

`gpt-3.5-turbo` is the same model used in the ChatGPT product but it is stateless, so it's **cheaper($0.002/1K tokens), faster and high availability**.

With `gpt-3.5-turbo` and suitable prompt, AIChat become a universal tool.

Just add following snippet to `roles.yaml`, AIChat become a command prompt tool.

```yaml
- name: shell
  prompt: >
    I want you to act as a linux shell expert.
    I want you to answer only with bash code.
    Do not write explanations.
```
```
〉.role shell

〉resize app.png to 256x256
convert app.png -resize 256x256 app.png

〉 extract password protected app.zip to /tmp/app
unzip -P password app.zip -d /tmp/app
```

With a little prompt, AIChat become a format conversion tool.
```
cat data.json | aichat turn following json to yaml
```

Most of the people chatting in the terminal are mostly asking technical/codeing questions, and the context-aware chatting is not that important.

Press the up arrow key, select the previous history, modify it and ask again, it is not difficult.

> Openai's APIs are all stateless and context-free. There is no way to implement a chat experience similar to Chatgpt Web.

**Comment by int** [comment]
I know `gpt-3.5-turbo` is the same model as used in ChatGPT and the API itself is stateless per se.
But we can extend the `messages` with all the context.

Quote as documented in the official OpenAI API guide
https://platform.openai.com/docs/guides/chat/introduction: 

```
# Note: you need to be using OpenAI Python v0.27.0 for the code below to work
import openai

openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)
```

> Including the conversation history helps when user instructions refer to prior messages. In the example above, the user’s final question of “Where was it played?” only makes sense in the context of the prior messages about the World Series of 2020. Because the models have no memory of past requests, all relevant information must be supplied via the conversation. If a conversation cannot fit within the model’s token limit, it will need to be shortened in some way.

An example: https://github.com/evilpan/gptcli

If not making it default behavior for interactive shell, here's hoping for adding it as an opt-in (e.g. via `.set`).

**Comment by sigoden** [comment]
gpt-3.5-turbo's maximum limit is 4096 tokens. 

I just sample some reply texts and calculated them with tiktoken. Most of them have about 400-700 tokens.

That is, a maximum of 7 to 8 questions per session.

**Comment by int** [comment]
8 actually seems enough and reasonable.  Last time I checked, the new Bing only had a cap of 6 replies for one conversation - they probably are starting to raise it to 8 or 10 by now. 

IMHO, even 2 (i.e. we only have one "previous" context info) would boost the user experience *a lot* and the result would be more than pleasant.   For most use cases though, we probably don't really need many rotations.   (user can also do something like  `.clear session`)

That said, maybe we could use a FIFO to keep messages within the quota instead of setting an hard limit of replies like 8.  This way, how the limit is triggered depends on users' queries -- if they tend to make short queries (with short replies back), they can make more ones than those who do long queries.

e.g. 
![Screenshot 2023-03-08 224017](https://user-images.githubusercontent.com/84553/223742816-3aac79eb-3da5-4cca-9726-f73f98daf5a4.png)

we probably could do 100 instead of just 8.
