### ISSUE TITLE
Add AWS Bedrock support

### ISSUE THREAD

**Issue by smrtl** [sigoden/aichat#401]
- It seems there's a rust client lib: https://docs.rs/aws-sdk-bedrockruntime/latest/aws_sdk_bedrockruntime/
- Ideally instead of a token we would input a profile name (and an aws region)

**Comment by sigoden** [comment]
Which AWS Bedrock-provided LLM do you need to use? The most attractive Claude model is not yet publicly accessible (use case details required).

Additionally, AWS Bedrock supported LLMs have their own unique input data structures, and many LLMs lack support for history messages (sesssion required), I lack the passion to support them.

Check for an alternative solution at https://github.com/sigoden/aichat/issues/300#issuecomment-1916614299
