### ISSUE TITLE
Get debug information from OpenAI request

### ISSUE THREAD

**Issue by pmatos** [sigoden/aichat#406]
**Is your feature request related to a problem? Please describe.**

Currently I am getting the following from openai:
```
Failed to get answer

Caused by:
    You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
```

**Describe the solution you'd like**

I would like to enable debug information so I can obtain the exact issue occurring with the API request. OpenAI returns many values in the headers to understand what's missing in my account. See https://platform.openai.com/docs/guides/rate-limits/rate-limits-in-headers

**Comment by sigoden** [comment]
There is no more information returns from oepanai, you need to check the documentation yourself https://platform.openai.com/docs/guides/error-codes

There is not nothing to do with rate-limits

**Comment by sigoden** [comment]
It's actually related.

**Comment by carlreid** [comment]
@sigoden I think I have a related issue, where getting debug output (_the request that was built_) might help me diagnose if I have misconfigured something. I see a [`!debug`](https://github.com/sigoden/aichat/blob/main/src/client/azure_openai.rs#L47) call/out being made. I am just not sure how to get this output to work. Maybe a `--verbose` argument or something would be nice to output this kind of stuff.

I get the following output:
```
Failed to get answer

Caused by:
    error sending request for url (https://<REVOKED>.openai.azure.com/openai/deployments/<REVOKED>/chat/completions?api-version=2023-05-15)
```

I can call the URL that is output from this manually, and get a response. Now I feel just kind of stuck not knowing where the problem might be in `aichat` 😩

**Comment by sigoden** [comment]
```sh
git clone https://github.com/sigoden/aichat
cd aichat
cargo run
```
Navigate to `<aichat-config-dir>`, where you will find `aichat.log`.

**Comment by carlreid** [comment]
Installed Rust, C++ tooliong etc, just to be met with:
![image](https://github.com/sigoden/aichat/assets/33623601/30b1ac3e-af13-4d74-a58c-595643c40cea)

Probably can't do much about this being blocked. Would appreciate if it's possible to get the same debug output on a released binary.
