### ISSUE TITLE
When sessions are active the messages.md file is not updated

### ISSUE THREAD

**Issue by tj800x** [sigoden/aichat#408]
Sessions seem to prevent message.md from being updated.  

Without a session being activated the message.md file in my current directory is updated.  Once I activate a session that message.md file is not updated.  Deactivating the session will start updating that message.md file again.  This occurs regardless of the model I am running.

os version: OSX 23.2.0 X86_64
aichat version: 0.16
terminal version: iterm2 3.4.23
Note: I am specifying $AICHAT_CONFIG_DIR before starting aichat.

**Comment by tj800x** [comment]
I saw that and assumed it was more an internal file than the output document.  It's not really usable without parsing.  An option to turn on markdown output while in a session would be nice.  Changing the .info command results would also be useful.

**Comment by sigoden** [comment]
This is the best solution currently.
Since the session requires load and reuse, it can only be saved in yaml format.
If you want to view the session in markdown format, please use `.info session` in the session.
