### ISSUE TITLE
[Feature Request] use `bat::PrettyPrinter` for better highlighting

### ISSUE THREAD

**Issue by int** [sigoden/aichat#41]
instead of calling `syntect` directly in our code.

Looks `bat` produces better result overall (it uses `syntect` too under the hood).
This hopefully could also simplify the render code a bit.

https://docs.rs/bat/latest/bat/
https://docs.rs/bat/latest/bat/struct.PrettyPrinter.html

**Comment by sigoden** [comment]
I used syntect to achieve the same effect as bat.

AIChat's [syntaxes.bin](https://github.com/sigoden/aichat/blob/main/assets/syntaxes.bin) comes from bat's [syntaxes.bin](https://github.com/sharkdp/bat/blob/master/assets/syntaxes.bin)

**Comment by int** [comment]
Thanks for the prompt replies to feature requests. :)

I didn't do extensive tests.  Just as a normal user, from my own limited usage:

![Screenshot 2023-03-08 201158](https://user-images.githubusercontent.com/84553/223711390-655c4a0a-61c2-4b96-8962-35456946a3ee.png)

Left is aichat 0.4.0; right is https://github.com/ddddddeon/a which uses `bat::PrettyPrinter`.

My wild (could-be-wrong) guess is that, to be on par with `bat`, we probably have to do some extra work.  While in the same time, `bat` has all the bells and whistles (or in today's words, batteries included) already wrapped nicely for us.  Things might become easier. -- Just a humble suggestion.

Btw I've created this and #40 just because I love this project and hope it better -- I wanted to politely use the `enhancement` label but github wouldn't let me to -- seems only those who have write permission (i.e. maintainers & contributors) can.  Please feel free to use whatever you like for the design & implementation.  ;)

**Comment by sigoden** [comment]
In aichat 0.4.0, we use mdcat. after pr #26, we switch to syntect. You will see in next release.

**Comment by int** [comment]
just did a fresh `cargo build --release` against 7270308

![Screenshot 2023-03-08 212400](https://user-images.githubusercontent.com/84553/223731280-8c770caa-a0f6-49a2-a048-90b7ba54d1bc.png)


looks like the problem remains.  env is wsl2 on win10 if it matters.

**Comment by sigoden** [comment]
In bat, code blocks without language information are also not highlighted.
It just display as normal text.
![image](https://user-images.githubusercontent.com/4012553/223734341-5a4a42ee-a66f-47a0-9159-d6b67501065e.png)


aichat display unknown-lang code block  as string text

**Comment by int** [comment]
oh i see.
just noticed that ddddddeon/a passed a `lang` hint
https://github.com/ddddddeon/a/blob/f02464082b04a17286c9fce79f1f61ad5c43737b/src/main.rs#L15

**Comment by sigoden** [comment]
With suitable prompt, aichat can also do what  `ddddddeon/a` do

```
- name: coder
  prompt: >
    I want you to act as a senior programmer. 
    I want you to answer only with the fenced code block.
    I want you to add an language identifier to the fenced code block.
    Do not write explanations.
```

![image](https://user-images.githubusercontent.com/4012553/223764724-1d35ee57-2869-40d6-8b57-f7ce54a3372e.png)

**Comment by int** [comment]
@sigoden Thanks.  Just been playing with the API and tools recently.

I'd love to - if i could help in a way or two.

For collecting prompts, maybe we could start with this one:
https://github.com/f/awesome-chatgpt-prompts
