### ISSUE TITLE
[Feature request] expose aichat as a rest api endpoint

### ISSUE THREAD

**Issue by zuisong** [sigoden/aichat#410]
**Is your feature request related to a problem? Please describe.**
I want to run `aichat` to serve a API endpoint that allows access ai completion.

**Describe the solution you'd like**
just like
```shell
$ aichat --server
$ curl https://localhost:3000/v1/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "aichat-client-1:gpt-3.5-turbo",
        "messages": [{"role": "user", "content": "Hello"}]
    }'
```

**Comment by dtrckd** [comment]
Hi @zuisong 
Interesting, how did you complete this issue finally ?

**Comment by zuisong** [comment]
This tool was initially designed for command-line usage, and I find this request somewhat intrusive.

Later, I try to implement it myself and encountered difficulties.

**Comment by sigoden** [comment]
#431 supports this feature.
