### ISSUE TITLE
Ctrl + O not working with Windows Terminal

### ISSUE THREAD

**Issue by AlexVermette-Eaton** [sigoden/aichat#416]
**Describe the bug**
The Ctrl+O keybind to open a text editor does not work with Windows Terminal. 

**To Reproduce**
1. Download Windows Terminal
2. Use any profile (e.g., Command Prompt or Git Bash)
3. `aichat`
4. Ctrl+O, nothing happens. The Ctrl+C keybind works great.

**Expected behavior**
A text editor should open to allow me to edit my current query.

**Screenshots/Logs**
N/A

**Environment (please complete the following information):**
- os version: Windows 10
- aichat version: 0.14.0
- terminal version: Windows Terminal 1.19.240226003

**Additional context**
N/A

**Comment by sigoden** [comment]
The command for editing the current line buffer with Ctrl+O might not be available. Please check your `$EDITOR` and `$VISUAL` environment variables and ensure at least one of them is set.

I will add a configuration item in the future to avoid using environment variables.

**Comment by AlexVermette-Eaton** [comment]
I confirm that adding `$EDITOR` environment variable works. Thanks a lot!
