### ISSUE TITLE
Compression should be based on max-input-tokens

### ISSUE THREAD

**Issue by justinlovinger** [sigoden/aichat#424]
**Is your feature request related to a problem? Please describe.**

With automatic compression,
the context of a model is irrelevant
unless `compression_threshold` is manually modified whenever changing models.

**Describe the solution you'd like**

Instead of a configurable threshold to trigger compression, compression should trigger when near the max-input-tokens of a model. Furthermore, more messages should be kept the larger the available context of the model.

Perhaps the number of messages to keep, relative to the context of the model, can be configurable. For example, an option could be to "keep `n`% of context worth of message", where `n` is configurable. The higher this number, the more often compression will occur, but the better the model will perform.

**Describe alternatives you've considered**

Disable automatic compression and add a command to manually compress.

**Comment by sigoden** [comment]
I don't think so. The differences between various models are too significant, ranging from 4096 to 10,000,000 and beyond. 
Plus, price is a more important factor than the model's max input tokens. Allowing users to set specific values is the most appropriate approach.

**Comment by justinlovinger** [comment]
Then perhaps compression should be disabled by default or the threshold should be greatly increased.

As a new user, it took me a while to realize why my conversations would break down long before they ran out of context.

**Comment by sigoden** [comment]
#426 could help users realize session compression.
