### ISSUE TITLE
Feature request: config option, flag to automatically start in multi-line input mode

### ISSUE THREAD

**Issue by sudomain** [sigoden/aichat#443]
If you are requesting support for the new model, goto [model-request](https://github.com/sigoden/aichat/issues/new?assignees=&labels=enhancement&projects=&template=model_request.md&title=).

**Is your feature request related to a problem? Please describe.**

I'd like to be able to enter directly in multi-line edit mode (:::). I use this mode 95% of the time but sometimes forget to start the message with `:::`

**Describe the solution you'd like**
A config option/flag e.g. `start_in_multiline_mode = true` or `--multi-line-mode. Additionally, being able to enter multi-line mode at any point in the message might be useful:
```
this is a :::
multiline
message:::
```

**Describe alternatives you've considered**

I tried making a role just for this, but the config file being yaml did not enjoy parsing `:::` 😄 

**Additional context**

**Comment by sigoden** [comment]
I will not support this feature.
In fact, aichat has already put a lot of effort into supporting multiline input.

Recommended strategies for your case:
- Use `ctrl+enter` to input newline (requires terminal support)
- Use `ctrl+o` to open an external editor (requires `$EDITOR` environment variable)  (recommended)
