### ISSUE TITLE
Doesn't show setup prompt upon initial launch with scoop on windows

### ISSUE THREAD

**Issue by RayyanNafees** [sigoden/aichat#448]
**Describe the bug**

> Upon first launch, Aichat will guide you through the configuration process. An example configuration file is provided below:

None of it happens as stated in the [docs](https://github.com/sigoden/aichat#configuration)

**To Reproduce**
```pwsh
scoop install aichat
aichat
```

**Expected behavior**
Should have shown the configuration prompt for setting up custom modals and API keys

**Screenshots/Logs**
![image](https://github.com/sigoden/aichat/assets/59685062/47a88df8-06e7-4d6a-a3f8-df751029eb55)

**Environment (please complete the following information):**
- os version:  Windows 11 Enterprise x86_64
- aichat version: 0.16.0
- terminal version: PowerShell 7.4.2

**Additional context**
Bug solved after removing OPENAI_API_KEY variable from the environment variables
![image](https://github.com/sigoden/aichat/assets/59685062/3c4809c2-401e-472a-a3d4-f2e7795f926f)

**Comment by sigoden** [comment]
Have you configured the OPENAI_API_KEY?
For backward compatibility, the OpenAI client is automatically used when the OPENAI_API_KEY environment variable is detected, without prompting the user to generate a configuration.
