### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by VictorioBerra** [sigoden/aichat#449]
**Is your feature request related to a problem? Please describe.**
GitHub Issues are for issues and features. Not things like Q&A.

**Describe the solution you'd like**
Enable GitHub Discussions, especially Q&A.

**Describe alternatives you've considered**

**Additional context**
Discussions can be nice to ask simple questions without having to fill out a huge issue report for something that may not even be an issue.

**Comment by sigoden** [comment]
GitHub discussions aren't necessary; issues are good enough. Maybe later on, if there are more aichat users, we'll consider enabling it.
