### ISSUE TITLE
[REQUEST] make window install easy using scoop 

### ISSUE THREAD

**Issue by NormTurtle** [sigoden/aichat#45]
i think that is the time when , project must be handled / Installed using package manger 
but most of time people forgot window , so im here 

[scoop](scoop.sh) is package manger for `window` which i use , 
so i want aichat on its manifest for easier install and upgrade  

thx

**Comment by sigoden** [comment]
Issue a package request on scoop need some conditions.

The most important of these is:
```
Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks) 
```

Need to give aichat more time.

Or everyone can help spread the word and speed up the time

**Comment by omaru-ok** [comment]
okay sir ⭐  im ahead of posting to my friends

**Comment by omaru-ok** [comment]
@sigoden  i think the time has came , **500** star already

**Comment by sigoden** [comment]
done, see ScoopInstaller/Main#4579
