### ISSUE TITLE
If you have env vars such as OPENAI_API_KEY set, then you wont get prompted to setup a new config file.

### ISSUE THREAD

**Issue by Zate** [sigoden/aichat#461]
**Describe the bug**
I had an old OPEN_AI_KEY env var in the shell I was using to startup aichat and so it was skipping asking me if I wanted to setup a new config file, and yet none of the config files that .info or --info were suggesting, existed.

**To Reproduce**
In a command prompt:
```
>unset OPENAI_API_KEY
>aichat
```
You will be prompted to setup a config.

Now:
```
>export OPENAI_API_KEY=stuff
>aichat
```
You will see a list of information, defaulted to openai, and listing config_file and others that likely do not exist.  (Did not on my mac)

**Expected behavior**
I would expect that it verifies whether the config files exist on file, and runs initial setup if they do not.
I would expect that if there are any existing env vars that it finds as useful, it says so, and asks if you want to import those into a config/role etc
I would expect there is a cli switch to force recreation/setup of new configs as per the "Out Of The Box" experience

**Screenshots/Logs**
![image](https://github.com/sigoden/aichat/assets/410234/81857ebd-48ec-4418-ad1c-6a92a4854ac1)

**Environment (please complete the following information):**
- os version: Darwin <snip> 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64
- aichat version: 0.16.0
- terminal version: Mac Termina, VSCOde Termins, zsh and bash.

**Additional context**
You could likely parlay this into a cli command to add new config elements to make the user experience nicer.

**Comment by sigoden** [comment]
same to #448.

So many misunderstandings. I will remove this backward compatibility.
