### ISSUE TITLE
[Feature Request] Clarify the beginning of the answer from LLM.

### ISSUE THREAD

**Issue by kyu08** [sigoden/aichat#474]
Thank you for creating awesome CLI LLM client! I love this tool and use it everyday.
This is a feature request about session feature. And I created PR for this feature. Please take a look at it.(#475)

## **Is your feature request related to a problem? Please describe.**
When I launch aichat with `aichat -s` and I ask long question to LLM, I sometimes lose track of where the beggining of the answer is.

<img width="1511" alt="image" src="https://github.com/sigoden/aichat/assets/49891479/7c64415d-86fa-4f6f-94c0-cd564d7df78b">

## **Describe the solution you'd like**
Like session name, I want to have the AI Assistant name to the beggining of the answer from LLM.

Like this:
<img width="1502" alt="image" src="https://github.com/sigoden/aichat/assets/49891479/e2f30b7f-88cf-4741-af36-d6f7f3a36fb9">

## **Describe alternatives you've considered**
The purpose is to clarify the beginning of the answer from LLM. So, it is also option to render a ruled line like this:

<img width="1510" alt="image" src="https://github.com/sigoden/aichat/assets/49891479/756f52a8-46ed-4b5a-b705-3f1775f08d9b">

## **Additional context**
The version I'm using is` v0.16.0`.
```sh
$ aichat --version
aichat 0.16.0
```

**Comment by sigoden** [comment]
Indeed, it is necessary to make input/output easier to distinguish.
But printing a fixed symbol before output is not a good solution. I've seen so many REPLs, but I've never seen anyone do this. This approach is somewhat counter-conscious.

Multi-line indicators make it easy. Theme can alleviate this problem. Other solutions include bold/color input text.

![image](https://github.com/sigoden/aichat/assets/4012553/71f13b22-3256-4998-8060-cb96a9aa66a4)

**Comment by kyu08** [comment]
Thanks for the reply!

> But printing a fixed symbol before output is not a good solution. I've seen so many REPLs, but I've never seen anyone do this.

On second thought, this is true.

Also, thank you for creating the PR(#479)! 
I will close my PR.
