### ISSUE TITLE
feat: REPL with files

### ISSUE THREAD

**Issue by peperunas** [sigoden/aichat#478]
**Is your feature request related to a problem? Please describe.**
As of now, when adding a file(s) via `-f`, there is no way - to the best of my knowledge - to spawn a REPL and chat with the files. Instead, if no text is passed, the model will describe what the files are and then `aichat` terminates.

I have tested by passing multiple files via a wildcard, e.g. `aichat -f *.txt`. 

**Describe the solution you'd like**
It would be great to pass one or more files via `-f *.<extension>` and then open the REPL.

**Comment by sigoden** [comment]
please try `.file` repl command.

**Comment by peperunas** [comment]
It doesn’t support wildcards and tab completion from the filesystem.

Giulio De Pasquale

PhD Candidate in Program Analysis for Computer Security
King’s College London, Strand Campus

Website: https://pepe.runas.rocks

**Comment by sigoden** [comment]
But it's enough for use.

**Comment by sigoden** [comment]
Since LLM has context window limitations, it cannot actually process many files at a time. glob is not as useful as you think.
You can also use `rg --files` (or similar tools) to generate the file and paste it into the repl.

**Comment by peperunas** [comment]
I see, thanks @sigoden!

I will then just use this :-)

Giulio De Pasquale

PhD Candidate in Program Analysis for Computer Security
King’s College London, Strand Campus

Website: https://pepe.runas.rocks
