### ISSUE TITLE
Discord Invite expired

### ISSUE THREAD

**Issue by cboecking** [sigoden/aichat#480]
Hi Team,

I am getting an error when trying to join the discord using the below link (stating that it is invalid or expired):

https://discord.gg/dSHTvH6S

![Screenshot from 2024-05-02 12-58-21](https://github.com/sigoden/aichat/assets/16024854/224d4a91-39c9-464d-aab2-980d27279227)
Sorry to create an issue for this situation; however, I do not know a better way to communicate the situation with the team.

Thanks for your time and consideration! Chuck

**Comment by sigoden** [comment]
New Invite link: https://discord.gg/mr3ZZUB9hG

It's really strange that it has expired even though it is set permanently.
