### ISSUE TITLE
Mode for copying code blocks from responses

### ISSUE THREAD

**Issue by sashkachan** [sigoden/aichat#488]
To have a more efficient workflow in the terminal, it would be great to be able to copy code blocks (perhaps scan for markdown) using osc52 escape code. This way, copy pasting between aichat and terminal should become less friction-full.

This may be tricky, as that would require the ability to iterate over code blocks, and have a selection mechanism. Which in turns requires an alternative mode implementation, similar to search mode in Vi-like editor. 
Except in the case of aichat "code search mode", search would be constrained to markdown blocks.

## Alternatives
Currently to achieve this, a form of in-terminal search capability required, eg tmux. However, tmux search is more generalized.

Terminals like kitty allow to open the whole buffer in an editor of choice, so far this is the easiest option.
Maybe I am missing some obvious workflow improvements that makes this feature less useful?

**Comment by sigoden** [comment]
Is there any cli tools that can do this? Can you give me an example? @sashkachan

**Comment by sigoden** [comment]
Even if you have a way, isn't it easier than copying with a mouse?

Currently aichat repl supports the `.copy` command, you can copy the response to the editor, and then copy the code block in the editor.

If you think `.copy` is too troublesome, there is also an `auto_copy` option to automatically copy the latest response

**Comment by sashkachan** [comment]
Oh, you're right, I should've checked the docs for .copy.
.copy could deliver 100% of this (and is a lot less complex), if it allowed copying code blocks only.

I image it could work like this
- in chat response, code blocks are given an id (or sequential number)
- .copy would take an argument with the code block id and then copies only that code block
- additionally, .copy could implement osc52, this puts the text in OS clipboard, thus allowing copy into the clipboard when working on a remote server.
 
mouse is definitely the easiest, however, I do prefer keyboard only approach when working in terminal.

**Comment by sigoden** [comment]
Don't you think it's too cumbersome to select copied code blocks by ID? Not as simple and direct as mouse copying

As for osc52, I don't think it is mature enough to support various protocols and terminals.
