### ISSUE TITLE
aichat -e causes - Error: Unknown role `%shell%`

### ISSUE THREAD

**Issue by Heratiki** [sigoden/aichat#508]
**Describe the bug**
If the problem is related to dynamic response data, you should see if it can be reproduced through `--dry-run`.
Attempting to run aichat -e <anything> causes it to output Error: Unknown role `%shell%`

**To Reproduce**
Steps to reproduce the behavior, including any relevant code snippets.
aichat -e list files

**Expected behavior**
expect it to output either dir or ls

**Screenshots/Logs**

**Environment (please complete the following information):**
- os version: Windows 11 Pro - Build 22631.3447
- aichat version: aichat 0.17.0
- terminal version: PowerShell 7.4.2
- 
**Additional context**

**Comment by sigoden** [comment]
Cannot confirm the problem. Please provide more details. @Heratiki

**Comment by sigoden** [comment]
I confirmed the bug. . Add a empty `roles.yaml` to solve the problem.
> Run `aichat --info | grep roles_file` to get the `roles.yaml` path.

**Comment by Heratiki** [comment]
Thank you very much for the fix.  This is a fantastic piece of software.

**Comment by VictorioBerra** [comment]
This fixed it for me. I broke it when  I copy/pasted aichat.exe over my current installed one in appdata. Ideally would like an aichat -update command.

**Comment by Heratiki** [comment]
Yeah I’d love an aichat -update command but at the same time I typically use brew or similar package management to install it so the updating is already built in.

**Comment by VictorioBerra** [comment]
Got a brand new laptop today, decided to install scoop and install with scope, and ran `aichat -c "whatever"` and got this error.

Is there a way to prevent users from ever seeing this at all @Heratiki ?

**Comment by Heratiki** [comment]
It’s basically fixed with making sure roles.yaml exists even if it’s empty.  I believe this is an issue with the scoop installation method and not the package itself. But I believe sigoden corrected it already so maybe it’s just not cached correctly or hasn’t updated all of the package files everywhere? I’m not 100% sure. I have a new machine I can try and install it on later tonight.

**Comment by joshspicer** [comment]
I'm on version 0.17.0 (the latest in the [nixOS store](https://search.nixos.org/packages?channel=24.05&show=aichat&from=0&size=50&sort=relevance&type=packages&query=aichat)) and manually creating `roles.yaml` fixed this for me.
