### ISSUE TITLE
Multiline Input for Conversation Mode

### ISSUE THREAD

**Issue by XOKP** [sigoden/aichat#51]
Thank you for adding the conversation mode feature! It's great and takes aichat to another level! I really enjoy using it.

However, I noticed that the conversation mode doesn't currently allow for multiline input. Would it be possible to add an editor mode for multiline input in the conversation too? This would be very helpful for users who need to input longer prompts or code snippets.

Thank you for considering, and keep up the good work!

**Comment by sigoden** [comment]
You means `.editor` not work?

I checked and there is no problem.

**Comment by XOKP** [comment]
It was entirely my fault, `.editor` is functioning flawlessly. I apologize for making a false report. Sorry!
