### ISSUE TITLE
Offer .temperature as a helper function and argument

### ISSUE THREAD

**Issue by jacksongoode** [sigoden/aichat#511]
**Is your feature request related to a problem? Please describe.**
Instead of setting temp in the config, allow it to be passed in with `-t` and changed with `.temperature`

**Comment by sigoden** [comment]
Chat-REPL have `.set` command.
 See https://github.com/sigoden/aichat?tab=readme-ov-file#set---adjust-settings-non-persistent

**Comment by jacksongoode** [comment]
Thank you!
