### ISSUE TITLE
Initial text and continue with REPL

### ISSUE THREAD

**Issue by kadircancetin** [sigoden/aichat#536]
How to continue to chat with REPL after given the initial message. I want to pass initial message programmatically and continue to talk with ai.

Example use case:

```bash
 aichat -s "First, summarize this text. Then give me answers of my question. TEXT: <LONG TEXT>" 
```
or
```bash
echo "First, summarize this text. Then give me answers of my question. TEXT: <LONG TEXT>" | aichat -s
```

**Comment by sigoden** [comment]
It's a convention that if there's text input on the command line, it gets executed directly. If there's no text input, it enters the REPL.

I will not support this feature.
