### ISSUE TITLE
support for ncurse based tui with history retention

### ISSUE THREAD

**Issue by santosh** [sigoden/aichat#539]
Hi, aichat was suggested by one of my friends at work and I find this project really useful in my day to day work as I really spend most of my in terminal if not using web browser. aichat does it work really well, no complaints.

When I first heard about the project, I was imagining a ncurse based UI, something similar to what ranger, and htop has but **resembling the UI on the chatgpt.com**. 

I know that currently we are storing chat history somewhere. Can we utilize that history to have a UI which retains the previous chat? Maybe we can **tie one chat to one role**, that would be awesome. 

What do you guys think?

**Comment by sigoden** [comment]
We think REPL is convenient enough.

**Comment by santosh** [comment]
Cool. I think I'll create a fork and attempt to create the UI I'm thinking of.
