### ISSUE TITLE
No available model on aichat 0.17.0

### ISSUE THREAD

**Issue by Haasebastian** [sigoden/aichat#540]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Configuration**

**Environment (please complete the following information):**
- os version: [e.g. Ubuntu 20.04]
- aichat version: [e.g. 0.9.0]
- terminal version: [e.g. GNOME Terminal 3.44.0]

**Additional context**

**Comment by sigoden** [comment]
You need to reconfigure the `clients` parts in your `config.yaml` file.

Before version 0.17.0, AIChat defaulted to using the OpenAI client if it detected an `OPENAI_API_KEY`. 
However, this led to confusion. #448 and #461.
So this feature was removed in version v0.17.0

If you're using OpenAI, you'll need to add the configuration below to your config file.

```
clients:
  - type: openai
    api_key: xxx        # Delete this field if you set the OPENAI_API_KEY environment variable
```

> To find the configuration file path, run the command `aichat --info | grep config_file`.
