### ISSUE TITLE
Ability to pass in a URL as a file

### ISSUE THREAD

**Issue by lboklin** [sigoden/aichat#541]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to include a webpage as a document for context without separately downloading it as a file and converting it into a format that won't confuse the AI (they tend to get distracted by html and css elements), which is often more work than it is worth.

**Describe the solution you'd like**
The ability to pass a URL to an article or other static content into the `.file` command, or `-f` cli flag.

The implementation would likely involve using existing Rust libraries to download web content and extract article content into a format resembling what for example firefox's reader mode produces.

**Describe alternatives you've considered**
Using external tools to download and convert a document before passing it in with the `-f` flag from the cli. It is non-trivial for the user as there doesn't seem to be any one particular tool that fulfils this particular use case. It would involve downloading with one tool, such as `curl`, and then piping it into some tool that extracts article content if possible, but all I can find are browser extensions and various libraries.

Even if there existed an obvious and perfect external solution for turning a URL into a suitable local document, it would not be available in the REPL, so it could not be used with the `.file` command.

**Comment by sigoden** [comment]
We will not support this feature.

Most of the resources on the Internet are html pages, it may also contain a lot of useless header/footer data.
Many also have auth requirements.

These are very difficult to handle.  AIChat's focus isn't on this.


Users can directly copy web content, open the editor with Ctrl+O, paste the content, and use it.
What you see is what you get, safe and convenient.

**Comment by lboklin** [comment]
It *isn't* particular convenient, though. I already said why it isn't convenient, and your solution of manually selecting and copying text as presented to you isn't always going to work and doesn't preserve *any* formatting in most cases.

Your suggestion is obviously the first thing that comes to mind when you want to use it as context for a prompt, and the fact that people *don't* is a clue that it isn't a good solution.

**Comment by sigoden** [comment]
Then write a script yourself to download the webpage, extract the content, save it to a local file, and then use it with `.file`/`--file`.

**Comment by lboklin** [comment]
I'm sorry but it seems like you are just closing this because... it seems difficult to do? I'm not sure what the focus is if "not on this". Why are files different from web pages in this context?
