### ISSUE TITLE
Use external resources to generate properly informed results

### ISSUE THREAD

**Issue by lboklin** [sigoden/aichat#542]
**Is your feature request related to a problem? Please describe.**

Using aichat to generate things like commands, code snippets, or context-sensitive factual answers/concrete solutions, is very hit-or-miss due to the (complete) lack of resources at the model's disposal.

As pre-trained models merely pattern match based on generic knowledge, they are unable to adapt to constraints imposed by novel or highly specific environments such as managed shell environments and source code. There is only so much one can do with a prompt to restrict the output so as to only generate valid solutions, and the current context that is included is not enough.

While the fundamental problem is inherent to the current architecture (or paradigm, even) of available models, I believe some mitigating solutions exist or could be created.

**Describe the solution you'd like**

Through a combination of expanding the context and the use of tools, the model should be guided towards sourcing answers from 
- local resources such as
  - system-specific documentation (e.g. man-pages)
  - the file system
  - environment variables
  - package manager/-ment capabilities (which packages are or could be put into scope)
- external resources such as
  - searchable remote repositories
  - online documentation
  - web search results
  - extractable static web content
  - various feeds
  - misc online services

When I autocomplete something like `pipe url into html-to-pdf converter` in my zsh terminal on NixOS, I get `curl -s "$url" | wkhtmltopdf - output.pdf`. Now somewhat unfortunately, in this particular example I'm actually *surprised* to find that `wkhtmltopdf` is actually in nixpkgs, so it's not the best example (most commands in autocomplete results given by llama3 are fabrication and/or use flags that make no sense).

However, the command doesn't work simply because even though wkhtmltopdf exists, **it isn't in my path**, and so it should (syntax (in)correctness notwithstanding) have instead suggested `curl -s "$url" | nix run nixpkgs#wkhtmltopdf -- - output.pdf` or `nix shell nixpkgs#wkhtmltopdf -c curl -s "$url" | wkhtmltopdf - output.pdf`.

It should know to do this because it should have been instructed to only generate an expression that may include shell builtins, aliases, and binaries listed in my path (or the correct invocation of my package manager. It should also have used the relevant man-pages as reference when deciding which flag to use.

**Describe alternatives you've considered**

There is no alternative I can think of.

**Additional context**

This is a complex problem and probably too big for a single issue, but the scope can be as small or big as one wants to make it. Putting the user's path into context is a good start. Giving it more details about the package management would be even better. For NixOS, it would suffice if it at least had access to a cached index of packages so that it would be inclined to always put the relevant ones in scope: `nix shell nixpkgs#foo nixpkgs#bar-bin nixpkgs#baz -c sh -c 'foo | baz $(bar)'`.

**Comment by sigoden** [comment]
AIChat already has roles and function callings. #514

**Comment by lboklin** [comment]
You just love closing issues it would seem.

The fact that it has roles and function callings is great. That is a **prerequisite** for this issue, not a solution to it.

But I see that there isn't much point in trying to contribute to this project, so I'll probably stop.

**Comment by sigoden** [comment]
Some preliminary work is best done by yourself, or can only be done well by you. Don't expect tools to do everything for you.

The information you mentioned above should be collected by yourself and put into the role for aichat to use.

You know that after collecting the information you mentioned in the issue, 100K tokens may not be enough.

**Comment by lboklin** [comment]
> Don't expect tools to do everything for you.

I'm not sure I should even attempt formulating a response to this.

> The information you mentioned above should be collected by yourself and put into the role for aichat to use.

No, that information should be automatically gathered by the
> cutting-edge CLI chat and copilot tool that [provides] a powerful combination of chat-based interaction, context-aware conversations, and AI-assisted shell capabilities, all within a customizable and user-friendly environment.

Because the exact same work you're suggesting I do myself would have to be done by precisely all other NixOS users, because it isn't specific to my system, but to my **OS**.

> You know that after collecting the information you mentioned in the issue, 100K tokens may not be enough.

I am not suggesting that my entire operating system is dumped into a system prompt for context. I'm not sure why you would even say something like this, especially after we have established quite notably that aichat has tools and function calling...
