### ISSUE TITLE
Aichat is asking to save session while save_session=true, in repl chat.

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#546]
**To Reproduce**
set `save_session=true` in the config file

**Expected behavior**
Do not ask to save when exiting.

**Screenshots/Logs**
![image](https://github.com/sigoden/aichat/assets/8218696/21cf0684-ff4f-4e56-b22c-7dd403d5a079)

**Environment (please complete the following information):**
- os version: Debian 11.9
- aichat version:  aichat 0.17.0
- terminal version: kitty 0.34.0 / fish, version 3.7.1

**Comment by sigoden** [comment]
The `temp` session is special; `save_session` doesn't work on temp sessions.

**Comment by dtrckd** [comment]
Ah ok, the session must be named for save_session to be active, I hadn't noticed that.
Thanks for the hints.
