### ISSUE TITLE
[REPL] Go automatically in multine-mode when entering <C-Enter>

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#550]
This is a functionality supported in most chat to go multi-line when it REPL mode.
I believe it can be a really nice and handy feature.
What do you thing about it ?

**Comment by sigoden** [comment]
aichat has done its best to support multi-line
- type `:::`
- `ctrl+o` to open external editor
- `ctrl+enter` to enter newline

**Comment by dtrckd** [comment]
Yes, I agree, the multi-line mode is really is really good .
I just have `ctrl+enter` does not work on my side...I dont' know why

---

 -  os version: Debian 11.9
 -  aichat version: aichat 0.17.0
 -  terminal version: kitty 0.34.0 / fish, version 3.7.1

**Comment by sigoden** [comment]
The most frustrating aspect of multi-line input in terminals is the lack of a universal shortcut key combination for `enter`

https://github.com/crossterm-rs/crossterm/issues/685
