### ISSUE TITLE
Resizing window causes text to be mangled

### ISSUE THREAD

**Issue by hkrutzer** [sigoden/aichat#554]
**Describe the bug**
When I resize the panel aichat is running in, the LLM text output becomes corrupted

**To Reproduce**
Generate an LLM response and resize the terminal window during

**Expected behavior**
-

**Screenshots/Logs**

https://github.com/sigoden/aichat/assets/3464899/4196fa8c-fd58-4cbe-b5d5-e4f86deafbbf

**Configuration**
```
model               azure-openai:gpt-4
max_output_tokens   -
temperature         -
top_p               -
dry_run             false
save                false
save_session        -
highlight           true
light_theme         false
wrap                no
wrap_code           false
auto_copy           false
keybindings         emacs
prelude             -
compress_threshold  2000
```

**Environment (please complete the following information):**
- os version: macos 13.6.7
- aichat version: 0.7.0
- terminal version: Wezterm
- shell: Fish

**Comment by sigoden** [comment]
This problem only occurs on certain terminals, this problem cannot be fixed. 

Sorry.
