### ISSUE TITLE
Adding support for codestral model

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#556]
A code centered model that looks promising, freshly announced, codestral (a mistral model) : https://mistral.ai/news/codestral/
Some features : 
-  "open-weights" on Huggingface : https://huggingface.co/mistralai/Codestral-22B-v0.1/discussions
- support chat-completion  and FIM (fill-in-the-middle) API endpoints

**Comment by sigoden** [comment]
Users can access it using `.model mistral:codestral-latest`.

I'll add it to `models.yaml` just before the next release.
