### ISSUE TITLE
how to enable web-search functionality?

### ISSUE THREAD

**Issue by zhuganglie** [sigoden/aichat#558]
I added  this to congif.yaml

'''patches:
      "gemini-.*":
        request_body:
          connectors:
            id: web-search
''''

I got this error:

''''
Failed to get answer

Caused by:
    Invalid JSON payload received. Unknown name "connectors": Cannot find field. (status: INVALID_ARGUMENT)
'''

**Comment by sigoden** [comment]
`patch` is an advanced feature that requires an understanding of the LLM's API.

The Gemini API doesn't offer connectors like Cohere does.
