### ISSUE TITLE
Support for few-shot prompting in roles.yaml?

### ISSUE THREAD

**Issue by wilenius** [sigoden/aichat#559]
I've had a lot of success using so-called few-shot prompting (see https://cookbook.openai.com/examples/how_to_format_inputs_to_chatgpt_models), where the model is primed by a "fake" set of request & model reply messages. I wonder if it would make sense to add the possibility to specify these kinds of messages in roles.yaml?

For example:

``` yaml

- name: caqdas
  prompt: >
    You are a research assistant doing qualitative data analysis.
    You are given a set of tags and a source text.
    Your job is apply the tags to the source text, and reply with a diff output that shows the difference between the source text and the tagged text.
    Use standard HTML <span title="tag name" style="color:blue;"> and </span> tags to mark the sections of the text that apply to each tag.
    Use different CSS color for each tag.
  example-user:
    lorem lipsum dolor etc
  example-assistant:
    --- source text
    +++ tagged text
    @@ -1,1 +1,1 @@
    -lorem lipsum dolor etc
    +lorem <span title="filler text" style="color:blue;">lipsum</span> dolor etc
```

**Comment by sigoden** [comment]
see https://github.com/sigoden/aichat/wiki/Role-Guide#structured-prompt

**Comment by wilenius** [comment]
Brilliant – you're way ahead of me. =) Thanks and sorry for the redundant issue!

**Comment by wilenius** [comment]
I'll just add a comment that the advantage of the "example-user" and "example-assistant" properties are that the model does not refer back to their content, but instead, understands it as an example of the output required. When I tried the supported ### INPUT and ### OUTPUT -forms, the LLM output confused the actual request with the example. Dunno how well other models than OpenAI's support this.

This is not a dealbreaker, and can be circumvented with additional prompting. (E.g. "Now, my actual request is about a different topic, but the form should be the same as in the previous request.")
