### ISSUE TITLE
Can wget it simply on our Linux CLI  

### ISSUE THREAD

**Issue by Huge** [sigoden/aichat#561]
As the binaries are like 8 MB, I'd consider releasing them without archiving/zipping them first. That seems would make CLI life easier to download/install.

Even with the current release format, providing something like 
```
# Set the base URL
BASE_URL="https://github.com/sigoden/aichat/releases/download/v"

# Set the version as an environment variable
VERSION=${1:-""}

# Get the architecture from uname or lscpu
ARCH=$(uname -m)

# Download the file
wget "${BASE_URL}${VERSION}/${ARCH}/aichat-${VERSION}-${ARCH}-unknown-linux-musl.tar.gz"
```
in the https://github.com/sigoden/aichat?tab=readme-ov-file#pre-built-binaries would be great.

**Comment by sigoden** [comment]
Users will always find a way to install aichat.
