### ISSUE TITLE
Save sessions in ~/.local/share 

### ISSUE THREAD

**Issue by cortsf** [sigoden/aichat#563]
**Is your feature request related to a problem? Please describe.**
Saving sessions under `~/.config` causes my dotfiles repo to include all my aichat conversations. I'm not fully familiar with the XDG specification but I think that `~/.local/share` is the appropriate path for this kind of information.

**Describe the solution you'd like**
Saving sessions on `~/.local/share/aichat/sessions` by default and optionally, providing  a config option (and/or argument) to allow setting any custom session path.

**Comment by sigoden** [comment]
please try AICHAT_CONFIG_DIR, see https://github.com/sigoden/aichat/wiki/Environment-Variables
