### ISSUE TITLE
aichat doesn't respect AICHAT_CONFIG_DIR

### ISSUE THREAD

**Issue by t18n** [sigoden/aichat#573]
**Describe the bug**
I set `AICHAT_CONFIG_DIR` via `.bashrc` and it shows in the terminal the value correctly. Yet when I run `aichat`, it keeps asking for creating the config files. I can run with `{client}_API_KEY` and `AICHAT_PLATFORM` without creating the config file, but then the dir is set to the default one. 

Note that this command `AICHAT_CONFIG_DIR=~/.config/aichat aichat` works correctly

**To Reproduce**
Set AICHAT_CONFIG_DIR, then run `aichat`

**Expected behavior**
Config files should respect `AICHAT_CONFIG_DIR`

**Screenshots/Logs**
![image](https://github.com/sigoden/aichat/assets/14198542/b89c9942-aef2-47e0-a8f4-1f0dccf46e05)

**Configuration**
Please see the screenshot

**Environment (please complete the following information):**
- os version: Mac OS 
- aichat version: 0.18.0
- terminal version: Wezterm

**Comment by sigoden** [comment]
@t18n 
Connot confirmed the bug.

Run `printenv | grep AICHAT_CONFIG_DIR` to check if the `AICHAT_CONFIG_DIR` environment variable is set.

**Comment by t18n** [comment]
@sigoden that was it. Thank you very much :)
