### ISSUE TITLE
How does compression work?

### ISSUE THREAD

**Issue by johannesCmayer** [sigoden/aichat#576]
Hi, 

Could somebody explain to me how the compression works? I am slow to understand the code. I'd guess that summarize is called repeatedly for the start of the session text, to replace the current text, until we are under the compression threshold.

Is this a destructive edit, or is the previous session text saved somewhere?

I think it would be good if this was explained at least briefly in the main readme.

**Comment by sigoden** [comment]
https://github.com/sigoden/aichat/blob/5635ca6a58fb4a590419335b098b7317285bfb82/src/config/mod.rs#L795-L810

https://github.com/sigoden/aichat/blob/5635ca6a58fb4a590419335b098b7317285bfb82/src/config/session.rs#L297-L302
