### ISSUE TITLE
Support nushell for function calling

### ISSUE THREAD

**Issue by kiil** [sigoden/aichat#578]
[Nushell](https://www.nushell.sh/) is great for working with ai and structured data.

Nushell has a thing called custom commands [Custom commands | Nushell](https://www.nushell.sh/book/custom_commands.html), essentially a way to make functions.

It would be great if Aichat could support bringing in these custom commands in function calling, giving aichat the local powers of the Nushell custom commands and all the rest that Nushell brings.

PS. I believe this project already uses [nushell/reedline](https://github.com/nushell/reedline) from the Nushell project.

**Comment by sigoden** [comment]
AIChat completes function calling by running a standalone binary. see https://github.com/sigoden/llm-functions

**Comment by cboecking** [comment]
Hi @kiil, I very much agree with your comment about the power of using nushell with aichat. I would appreciate being able to share thoughts if you are interested. Let me know. chuck@chuboe.com

**Comment by kiil** [comment]
Hi @cboecking -

Thanks for your comment.

I've done a lot of experimentation with nushell and aichat. You can read a little about some of it in these blog posts:

[Using Nushell 🐘 with Generative Artificial Intelligence 🤖 · Kiils](https://www.kiils.dk/en/blog/using-nushell-with-generative-artificial-intelligence/)

[tuc as text based data structure for online research · Kiils](https://www.kiils.dk/en/blog/2024-06-04-tuc-as-a-basic-ai-data-structure/)

[Working with tuc in nushell · Kiils](https://www.kiils.dk/en/blog/2024-06-11-working-with-tuc-in-nushell/)

My background is not really in programming, so I am just scratching the surface, but find aichat and nushell very helpful for working with text content.

**Comment by cboecking** [comment]
@kiil - that is kind of you to share. It is creative and inspiring. I hope to have something to return the favor!

**Comment by kiil** [comment]
@cboecking if you are on discord, I can recommend the nushell channel there. It is quite active and very helpful :)

**Comment by cboecking** [comment]
@kiil  - Thank you - @chuboe
