### ISSUE TITLE
[REQUEST] Loadin/saving conversations

### ISSUE THREAD

**Issue by olalonde** [sigoden/aichat#59]
It would be useful to be able to load / save conversations.

**Comment by sigoden** [comment]
You can easily retype your messages through the history.
You can easily view the conversation history in messages.md.
if you want to start a conversation in a kind of context or scenario, use ".role" or ".prompt" 
With the max token limit of 4096, i can't find anybenefit of loading conversations or saving conversations individually

**Comment by olalonde** [comment]
Oh ok. I was under the impression that 4096 tokens was the limit for a single request but that a multi turn conversation could go beyond 4096 tokens.

**Comment by olalonde** [comment]
It seems you are right:

> Including the conversation history helps when user instructions refer to prior messages. In the example above, the user’s final question of "Where was it played?" only makes sense in the context of the prior messages about the World Series of 2020. Because the models have no memory of past requests, all relevant information must be supplied via the conversation. If a conversation cannot fit within the model’s token limit, it will need to be shortened in some way.
