### ISSUE TITLE
[Request] Automatically enter editor mode when pasting multiline text

### ISSUE THREAD

**Issue by olalonde** [sigoden/aichat#60]
Right now when you paste a text (e.g. code snippet), every line is submitted individually as a separate request. It would be more helpful if the text was pasted in editor mode so that the whole thing would be submitted at once.

**Comment by sigoden** [comment]
you need to type `{` at the begining of the line to enter multiple-line editing mode. In that mode, you can paste multiple line text.

Check readme for more details.

**Comment by olalonde** [comment]
I know how multiline works. I was just thinking it would be useful to detect when multiline text is being pasted but I now realize now that it might not be technically possible to achieve.

**Comment by olalonde** [comment]
Kind of a hack but maybe one way would be to detect it based on the timing of the input.

**Comment by sigoden** [comment]
You never know if the user is going to paste multiple lines of text or to paste every line of text.

Don’t Make Choices for Users, Give Them Choices

**Comment by olalonde** [comment]
Yeah, that's a limitation of terminals unfortunately.

**Comment by milanglacier** [comment]
See the "bracket paste mode"

https://cirw.in/blog/bracketed-paste

many REPLs including [ipython](https://github.com/ipython/ipython), [radian](https://github.com/randy3k/radian), uses this trick to know whether a text stream is pasted or directed input from the user

**Comment by olalonde** [comment]
@sigoden do you think we could implement that?

**Comment by milanglacier** [comment]
The bracketed paste mode works like a charm! Do we consider make a new release since it is an important new feature?
