### ISSUE TITLE
[Feature Request] Injectable API key

### ISSUE THREAD

**Issue by marty-oehme** [sigoden/aichat#61]
As far as I can see currently, the API key has to be supplied through the configuration file - put there in plain text.

What I would wish for is some way of injecting the API key without it appearing in plain text in my configuration file.

Three options that come to mind, sorted from what I think is the least to the most amount of implementation effort:

- A cli option `aichat --api-key <key>` or similar which directly receives the key over cli.
- An environment variable in the style of `AICHAT_API_KEY=<key>` which it reads the from the environment
- or A way to inject the key from the configuration file itself, usually by calling a command like `api_key_cmd: gpg --decrypt /password/file.gpg` within the `config.yaml` file. CLI/TUI projects like [vdirsyncer](http://vdirsyncer.pimutils.org/en/stable/keyring.html), [newsboat](https://newsboat.org/releases/2.30.1/docs/newsboat.html#_passwords_for_external_apis) and a few others went this route for their configuration files.

Let me know if you would consider one (or multiple) of these options feasible, and thank you for a very nice piece of software!

**Comment by sigoden** [comment]
#63 support injecting API key through AICHAT_API_KEY.

**Comment by marty-oehme** [comment]
Thank you so much for the quick solution!
