### ISSUE TITLE
"blocked content" errors happening at a high rate when they previously were not.

### ISSUE THREAD

**Issue by sid3xyz** [sigoden/aichat#612]
**Describe the bug**

Blocked Content errors are triggering randomly for what is not sensitive content. using Gemini.

**To Reproduce**
Reproducibility is hard. Sometimes it triggers after a simple "hello" via REPL or using the execute or code parameters.

**Expected behavior**
Not have random blocked content 

**Screenshots/Logs**
Not applicable 

**Configuration**
molly@jellyfish:~$ aichat --info
model               gemini:gemini-1.5-pro-latest
max_output_tokens   -
temperature         -
top_p               -
rag_top_k           4
function_calling    false
compress_threshold  0
dry_run             false
save                true
save_session        true
highlight           true
light_theme         false
wrap                auto
wrap_code           true
auto_copy           false
keybindings         emacs
prelude             -
config_file         /home/molly/.config/aichat/config.yaml
roles_file          /home/molly/.config/aichat/roles.yaml
functions_dir       /home/molly/.config/aichat/functions
rags_dir            /home/molly/.config/aichat/rags
bots_dir            /home/molly/.config/aichat/bots
sessions_dir        /home/molly/.config/aichat/sessions
messages_file       /home/molly/.config/aichat/messages.md
molly@jellyfish:~$ 

**Environment (please complete the following information):**
- os version: Debian 12
- aichat version: 0.18.0 current from git
- terminal version: Default gnome terminal for deb 12

**Additional context**

This only started happening since I updated to the new 0.18.0 versions to test the bot implimentation.

**Comment by sigoden** [comment]
The way to set `safetySettings` for gemini/vertexai changed.
https://github.com/sigoden/aichat/blob/b965c63be05c726c996ece298d6f5f2514a19316/config.example.yaml#L113-L124

**Comment by sigoden** [comment]
AIChat supports RAG and use two api types: `chat_completions` and `embeddings`.

`request_body`  was ambiguous, and has been changed to `chat_completions_body`
