### ISSUE TITLE
LLM Qwen support function calling

### ISSUE THREAD

**Issue by martianzhang** [sigoden/aichat#615]
This is Qwen's official documentation for the Function Calling API:

https://qwen.readthedocs.io/en/latest/framework/function_call.html

Thank you for adding the function calling feature to AIChat with the Qwen LLM.

**Comment by sigoden** [comment]
I have implemented it locally, And found that the dashscope api has some issues with multiple tool_calls.
```
$ cargo run -- -m qianwen:qwen-max -S --role '%functions%' what is the weather in Pairs and Berlin?
Call get_current_weather {"location":"Paris"}
Call get_current_weather {"location":"Berlin"}
Failed to get chat completions

Caused by:
    Multiple tool_calls are not supported in message. This feature will be supported in the future (code: InvalidParameter)
```

**Comment by sigoden** [comment]
see #616
