### ISSUE TITLE
Current colorscheme is not friendly to light background

### ISSUE THREAD

**Issue by dreamerlzl** [sigoden/aichat#64]
After upgrading to the latest 0.6 version, the response is invisible on a light background.

**Comment by dreamerlzl** [comment]
![Screenshot_2023-03-11_14-39-51](https://user-images.githubusercontent.com/28644777/224469560-2281a0d1-3347-49ed-aff8-4bc359dc3697.png)

**Comment by sigoden** [comment]
#65 resolved this issue
