### ISSUE TITLE
session compression saves newlines as literal \n

### ISSUE THREAD

**Issue by Konfekt** [sigoden/aichat#648]
With aichat 0.18.0 the newlines of the assistant output are saved as literal `\n` in the `sessions\session.yaml` as soon as session compression starts.
Expected would be newlines instead.

**Comment by sigoden** [comment]
There's no issue. The AIChat use serde_yaml to simply dump it.

**Comment by Konfekt** [comment]
I was aware of that, but still think that a human expects human-readable output regardless of technical intricacies like session compression being active at some point or not.
