### ISSUE TITLE
azure-openai streaming failure

### ISSUE THREAD

**Issue by git-jonathankinney** [sigoden/aichat#651]
**Describe the bug**
Within the last month or so, a deployment of gpt-4 or gpt-4o fail to stream, but work fine with -S to disable streaming.  However, -S to disable streaming is not honored after entering interactive mode, so I can only run single line chats with "aichat -S".  There is an APIM in front of the model but that should not be an issue, and the error reflects expected data is being returned but not handled properly.

**To Reproduce**
Have an Azure OpenAI gpt-4 or gpt-4o model deployed, and configured behind an APIM
Brew install aichat, currently version 0.18.0
Config model, type, api_base, api_key, name, etc.
run "aichat in a terse response give another name for a dog"
Returned error:
```
Failed to get answer

Caused by:
    Invalid response event-stream. content-type: , data: data: {"choices":[],"created":0,"id":"","model":"","object":"","prompt_filter_results":[{"prompt_index":0,"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}]}

    data: {"choices":[{"content_filter_results":{},"delta":{"content":"","role":"assistant"},"finish_reason":null,"index":0}],"created":1719359351,"id":"chatcmpl-9eACN6ilYpdNWtgqtFIYqTDaUDF1I","model":"gpt-4","object":"chat.completion.chunk","system_fingerprint":"fp_7ec89fabc6"}

    data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"Can"},"finish_reason":null,"index":0}],"created":1719359351,"id":"chatcmpl-9eACN6ilYpdNWtgqtFIYqTDaUDF1I","model":"gpt-4","object":"chat.completion.chunk","system_fingerprint":"fp_7ec89fabc6"}

    data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"ine"},"finish_reason":null,"index":0}],"created":1719359351,"id":"chatcmpl-9eACN6ilYpdNWtgqtFIYqTDaUDF1I","model":"gpt-4","object":"chat.completion.chunk","system_fingerprint":"fp_7ec89fabc6"}

    data: {"choices":[{"content_filter_results":{},"delta":{},"finish_reason":"stop","index":0}],"created":1719359351,"id":"chatcmpl-9eACN6ilYpdNWtgqtFIYqTDaUDF1I","model":"gpt-4","object":"chat.completion.chunk","system_fingerprint":"fp_7ec89fabc6"}

    data: [DONE]
```

**Expected behavior**
Same output as -S, but without streaming:
```
$ aichat in a terse response give another name for a dog
Canine
$
```

**Screenshots/Logs**
NA

**Configuration**
model               azure-openai:gpt-4
max_output_tokens   -
temperature         -
top_p               -
function_calling    false
compress_threshold  4000
dry_run             false
save                false
save_session        -
highlight           true
light_theme         false
wrap                no
wrap_code           false
auto_copy           false
keybindings         emacs
prelude             -
config_file         /Users/the.dude/Library/Application Support/aichat/config.yaml
roles_file          /Users/the.dude/Library/Application Support/aichat/roles.yaml
messages_file       /Users/the.dude/Library/Application Support/aichat/messages.md
sessions_dir        /Users/the.dude/Library/Application Support/aichat/sessions
functions_dir       /Users/the.dude/Library/Application Support/aichat/functions

**Environment (please complete the following information):**
- os version: MacOS 14.5 (23F79)
- aichat version: 0.18.0
- terminal version: iTerm.app 3.5.2

**Additional context**
I don't expect this to be related to the APIM, there is no magic there, just routing by model name in the URL, OpenAI compatible.  I could have sworn this was working fine maybe a month or 2 ago, but could be wrong, and just experiencing the stream as default change recently made.  If aichat could persist the -S in an interactive session, then my alias aichat="aichat -S" would solve things well enough for me, but it always streams unless its a single shot command.  I know Azure can be a black box, but hoping this is enough to see what is up.

**Comment by sigoden** [comment]
azure-openai should be openai-compatible. Does the APIM introduce any differences?

Please run the following argc command, then post the response.
```
 argc chat-openai-compatible --api-base <API-BASE> --api-key <API-KEY> --model <MODEL> [TEXT]...
```

This will help me pinpoint the issue.

**Comment by git-jonathankinney** [comment]
I checked out the repo, I installed argc, and ran the command from inside the repo but it errors out:
```
$ argc chat-openai-compatible --api-base https://some-deployment-api.azure-api.net --api-key anapikeyadfadsf --model gpt-4 in a terse response give another name for a dog
HTTP/1.1 404 Resource Not Found
Content-Length: 54
Content-Type: application/json
Request-Context: appId=cid-v1:e7f6b297-31f9-4297-bf97-53cfb09ac120
Date: Wed, 26 Jun 2024 05:12:37 GMT

{ "statusCode": 404, "message": "Resource not found" }
```
Its odd that without streaming its fine, but with streaming, it has an issue.  I will have to circle back to pull out some more information, maybe an strace, or a packet capture or something along those lines.

**Comment by sigoden** [comment]
>   Invalid response event-stream. content-type: ,

It seems the `content-type` is missing.

**Comment by sigoden** [comment]
@git-jonathankinney 
The azure-openai url is special. I added new argc command `chat-azure-openai`. 

Please run the following argc command, then post the response.
```
 argc chat-azure-openai --api-url   https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/embeddings?api-version=2024-02-01 --api-key <API-KEY> --model <MODEL> 
```

**Comment by git-jonathankinney** [comment]
If any of this seems malformed, and it really should not respond like this, or it is missing something in the response that a de-facto resource says should be there in this context, that would be good to know.  Boilerplate APIM code may be lacking, or something was lost in translation.

**Comment by sigoden** [comment]
As I mentioned, `Content-Type: text/event-stream` is missing. This is the most crucial field.

This is not an AIChat bug, closing this issue.
