### ISSUE TITLE
chatgpt output word limit 

### ISSUE THREAD

**Issue by vernon2gh** [sigoden/aichat#66]
pipe input/output, but output word too much, once can not be output completed, how to continue to output the previous content? Or in Chat mode (set config.conversation_first true), the ability to pipe the input file so that we can type 'continue' to let chatgpt continue typing before ?

**Comment by sigoden** [comment]
gpt-3.5-turbo has a maximum limit of 4096 tokens, and currently there is no way to surpass this limit.

Can only wait for the release of new models or restrictions to be lifted.

**Comment by vernon2gh** [comment]
If in Chat mode (set config.conversation_first true), the ability to pipe the input file so that we can type 'continue' to let chatgpt continue typing before.

The chatgpt web(https://chat.openai.com/chat) is able to do this.

**Comment by sigoden** [comment]
The only reason the stream has ended but the output hasn't finished is due to the max_tokens limit.

It's the same with or without conversation.

There is no chatgpt like `continue` in aichat/gpt3.5-turbo.

**Comment by vernon2gh** [comment]
yeah, I get this.

Can you add the ability to pipe the input file in Chat mode, so we can type 'continue' to let chatgpt continue typing before(When the stream has ended but the output hasn't finished).

**Comment by sigoden** [comment]
You can copy from `messages.md`.

**Comment by vernon2gh** [comment]
No, not fetch the output, is importing a large file

**Comment by sigoden** [comment]
Why not use command mode?

```
cat input.txt | aichat <tell ChatGPT how to handle file>
```
If you insist on using chat mode, you can use `{` to enable multi-line mode, and then you can directly paste the content.

**Comment by vernon2gh** [comment]
> cat input.txt | aichat <tell ChatGPT how to handle file>

The output word too much, once can not be output completed, I need touch 'continue' manually in Chat mode.

**Comment by sigoden** [comment]
I don't think aichat/gpt-3.5 will interrupt prematurely before using up 4096 tokens.

If a request/conversation has no more output, it means either the response is completed or the token has run out.

No continue in aichat/gpt-3.5
