### ISSUE TITLE
How to set the path of functions_dir on mac?

### ISSUE THREAD

**Issue by butchoosed** [sigoden/aichat#661]
Because there will be spaces in the path name on Mac, there are spaces in the functions_dir content displayed by the .info command, so the actual functions_dir directory cannot be located when executing %functions%. In this case, does it need to modify functions_dir as the correct content? Please give me more advice! thx～

**Comment by sigoden** [comment]
see https://github.com/sigoden/llm-functions?tab=readme-ov-file#getting-started-with-aichat
```
ln -s "$(pwd)" "$(aichat --info | grep -w functions_dir | awk '{print $2}')"
# OR
argc install
```

**Comment by butchoosed** [comment]
I have executed this command. When I executed the aichat -r %functions% command, it did not take effect, and the output was still the answer of the model. (I also installed argc and jq.)
<img width="563" alt="image" src="https://github.com/sigoden/aichat/assets/16630324/516c252e-b70d-4b89-ab6e-5bdb2871780f">

The following is my directory structure and aichat settings information:
<img width="483" alt="image" src="https://github.com/sigoden/aichat/assets/16630324/66fc7701-3cc4-4b22-959c-12a3166ac60b">

<img width="549" alt="image" src="https://github.com/sigoden/aichat/assets/16630324/b2a76d29-eb13-4afd-bc37-dae339020b9a">

<img width="586" alt="image" src="https://github.com/sigoden/aichat/assets/16630324/ba8339fb-971e-48ce-8255-8dda634a71f7">

**Comment by sigoden** [comment]
@butchoosed `deepseek-chat` does not support function calling.

![image](https://github.com/sigoden/aichat/assets/4012553/bb15eed4-d3bb-48df-9413-765560b0ba5d)

**Comment by butchoosed** [comment]
@sigoden 
i got it,Thank you very much!
