### ISSUE TITLE
Add Option to Hide Introductory Text

### ISSUE THREAD

**Issue by maxbraeutigam** [sigoden/aichat#663]
Hey, aichat is becoming my most important tool in the terminal. I really love it. Thank you very much. ❤️

**Is your feature request related to a problem? Please describe.**

Every time I start the `aichat` CLI, it displays an introductory message. While this message is useful for first-time users, it becomes repetitive and unnecessary for advanced users who are already familiar with its content.

```
Welcome to aichat 0.18.0
Type ".help" for additional help.
```

**Describe the solution you'd like**

I would like to request an option to hide the introductory message when launching the `aichat` CLI. This could be implemented as a command-line flag (e.g., `--no-intro`, `--quiet`) or a configuration setting in a configuration file.

**Describe alternatives you've considered**

One alternative could be to show the introductory message only the first time `aichat` is launched or provide an option during the start (e.g., a prompt asking if the user wants to see the introductory message in the future).

**Additional context**

Adding this feature would enhance the user experience for regular users by streamlining the startup process and focusing on the functionality they use `aichat` for. It would also keep the interface clean.

Thank you for considering this request.

**Comment by sigoden** [comment]
Many REPLs behave this way.

![image](https://github.com/sigoden/aichat/assets/4012553/dd6f4f88-c6de-4680-8e58-c9465b2d9f30)
