### ISSUE TITLE
Update RAG based on file changes

### ISSUE THREAD

**Issue by tomsib2001** [sigoden/aichat#664]
I love the new RAG feature! I use it to ask questions to my notes. However, sometimes my notes change, and I would love if there was a way for `aichat` to detect changes and reindex only the portions which have changed.

**Comment by sigoden** [comment]
AIChat will not support updating RAG when files changes,  but it provides a `.rebuild rag` command to synchronize changes manually (#672).

AIChat RAG supports not only local files and directories, but also remote files and websites, you cannot simply `watch` them.

**Comment by Squirreljetpack** [comment]
Can we have a cli option/command to perform this?
