### ISSUE TITLE
Feature request: make session mode aware of previous function calls

### ISSUE THREAD

**Issue by tomsib2001** [sigoden/aichat#667]
It seems that for now, under the `%functions%` role in session mode (in `0.19rc2`), the calls made in previous interactions are not available to the chatbot.
![image](https://github.com/sigoden/aichat/assets/2067520/2b5db427-4352-49b6-ac77-83f78acfbe62)
I understand that this might be a desirable feature in some cases, however I could see cases where you might suggest changes to the code that was just executed. Right now, it's not aware of that code:
![image](https://github.com/sigoden/aichat/assets/2067520/fcf9690e-589a-4d6c-993c-4c1941ec8479)
Could we imagine a parameter to include previous function calls in the chat history ?

**Comment by sigoden** [comment]
we will not support this feature.

Even if it is a function call, the key is the question and the answer, not the intermediate calculation process.
