### ISSUE TITLE
Docs: Clarify relation between role, RAG and agent

### ISSUE THREAD

**Issue by einarpersson** [sigoden/aichat#674]
Sorry if there is a better place for this kind of request, but I am confused by the new agent feature (using 0.19rc-2) and the relationship to roles and RAG. I am very eager to try this out but the mental model is not clear to me.

Here are a couple of questions that I have:
1. Can agents do everything a role/rag can do? I.e. if I try to add all functionality I want as agent definitions, can I forget about roles and RAG config? Are there multiple ways to achieve the same things?  Is there ever a use case for combining an agent and a role?
2. Are all tools global (all or nothing) or can certain tools be allowed to just some roles?
3. Is [llm-functions](https://github.com/sigoden/llm-functions) supposed to be a showcase, a helper tool or "the primary/only way to create agents and tools" for aichat?
4. It says that _"AI Agent = Prompt (Role) + Tools (Function Callings) + Knowndge (RAG)"_. But where are RAG definied for agents? Is it `documents:  - files/doc.pdf` in the agent `index.yaml`-file? (EDIT: Answered, YES)
5. Can RAG configurations be agent specific in the config file? (for example `rag_template`). It is also a bit confusing that some of these things should configured in the agent `index.yaml` and others in the `config.yaml`. 
6. Is there currently a way to reuse/share tools between agents?

Thank you for a very exciting project!

**Comment by einarpersson** [comment]
I've created a hello_world javascript agent now, with a RAG.

I think I have stumbled upon a REPL/CLI inconsistency though:
```
❯ aichat -a helloworld
helloworld>@rag>
```
(i.e. starts with rag)

However, if I write `aichat -a helloworld "What is the meaning of life"` it seems to not use the RAG. I need to use `aichat -a helloworld -R rag "What is the meaning of life"` for it to use the RAG.

If an agent always has the same RAG, then the -R flag doesn't make sense does it?

**Comment by sigoden** [comment]
1. `AI Agent = Prompt (Role) + Tools (Function Callings) + Knowndge (RAG)` is the answer. If you don’t understand something, try it yourself. Agent already contains its own role, how can it combine other roles?

2. There is only one `functions.json` file, but each role uses a `functions_filter` field to select its functions.

3. AIChat only requires a `functions.json` file and the existence of the related executable.  Anyone can create their own `llm-functions` project.

5. No, the agent's `index.yaml` file only contains data related to its functionality.  Remember, the agents of `llm-functions` are versatile and can be used in projects beyond just AIChat.

6. Unclear. We have not decided yet.

**Comment by sigoden** [comment]
Use `aichat -a helloworld <text>...` , no need to pass `-R rag`.
