### ISSUE TITLE
Would be nice to have a command copied to clipboard.

### ISSUE THREAD

**Issue by CentillionJinx** [sigoden/aichat#681]
With the current `aichat -e` command, user has the ability to either `approve`, `revise`, `explain`, or `cancel`. It would be nice to have another option to copy to clipboard, or to be pasted into commandline without executing, enabling the user to manually revise the command to his liking. I know the `revise` itself is meant for the literal feature I am asking, but would be nice to manually change it, gives somewhat control over what I would want to run, since llm can only suggest based on my natural language description of what I would want, could be time saving at some times. 

Having said that, it would be also nice to have an configuration that can be set, to auto save to clipboard when requested for a command, for instance if `aichat -e find the largest file in this dir` is ran, the menu comes up as usual, but at the same time, the suggested command that could be ran (showed in the menu) is saved to clipboard, hence if I were to cancel and exit, I could still run the command suggested previously from my clipboard. Same reason as before, convenience, and somewhat time saving

anyways thanks for a cool tool, I can replace warp with this! hehe W for open-source~

**Comment by sigoden** [comment]
We will not support this feature, please copy with your mouse.

**Comment by esafirm** [comment]
This sounds like a reasonable enhancement, `revise` with another natural language seems very difficult to get right, at least for me. Any reason why the feature will not be supported?
