### ISSUE TITLE
Claude 3.5 Sonnet 

### ISSUE THREAD

**Issue by DKchemistry** [sigoden/aichat#683]
### Please confirm whether the following requirements are met:

- [ y] Must have a REST/HTTP API.
- [ y] Must be publicly accessible. It cannot require application review or have regional restrictions. A beta version is acceptable.
- [ y] Must not act as an agent or proxy for other platforms.

### Please provide the following documents or links:

- API Documentation (required)
https://docs.anthropic.com/en/docs/welcome

though i think this is more direct
https://claude3.pro/claude-3-5-sonnet-api/#API_Access_and_Authentication

I don't know how to structure the yaml for Sonnet 3.5 specifically

**Comment by sigoden** [comment]
Already supported.
