### ISSUE TITLE
How to create a new RAG

### ISSUE THREAD

**Issue by jingluoguike** [sigoden/aichat#684]
I am new to aichat. Would very much appreciate your inputs about how to add an embedding model for using the RAG in aichat. Many thanks!

**Comment by sigoden** [comment]
```
.rag <name>
```

https://github.com/sigoden/aichat/wiki/RAG-Guide

**Comment by KhaaL** [comment]
For those stumbling into this from the future: you need to provide *two* asterixes in order to input the wildcard. I.e., you want to add all files from `/folder`, then you need to input `/folder/**` when building the RAG.
