### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by sigoden** [sigoden/aichat#687]
I'm putting together a FAQ wiki page. What questions do you have?

**Comment by sigoden** [comment]
@sid3xyz Please checkout https://github.com/sigoden/aichat/issues/684. You can comment on that issue.

**Comment by cboecking** [comment]
Hi @sigoden - I plan to perform rag against a git repository with markdown files. These files will change frequently over time. I do not see how to refresh the rag vector db with current content. Will you kindly explain? Chuck

**Comment by milanglacier** [comment]
How do we  contribute to the documentation?

Previously we can just make a PR for modifying README. But now the documentation is migrated to wiki, and it seems that wiki does not something similar to "PR"?

**Comment by sigoden** [comment]
@cboecking  `.rebuild rag` is what you need.

@milanglacier You can open an issue or discuss it on Discord.

**Comment by milanglacier** [comment]
> @milanglacier You can open an issue or discuss it on Discord.

Is it a concern that the documentation maintained in the wiki will be out of sync with the program itself since it is not maintained with git but maintained separately?

**Comment by sigoden** [comment]
@milanglacier I will update the wiki when a new version is released.

**Comment by cboecking** [comment]
@sigoden - FYI - I do not see the .rebuild reference in https://github.com/sigoden/aichat/wiki/RAG-Guide

**Comment by sigoden** [comment]
Folks, If you have any questions about AICHat, you can first ask the AICHAT Wiki.


https://github.com/sigoden/aichat/assets/4012553/d4a42406-bf86-4894-a041-215678ab0246

**Comment by milanglacier** [comment]
> Folks, If you have any questions about AICHat, you can first ask the AICHAT Wiki.
> 
>  aichat-wiki.mp4

This is an absolutely fun and intuitive video demonstrating how to use RAG. Love it!

**Comment by David-Else** [comment]
The WIKI page on RAG opens:

```
RAG can improve the efficacy of large language model (LLM) applications by leveraging custom data

AICHAT has a built-in vector database and full-text search engine, eliminating reliance on third-party services and providing ready-to-use RAG functionality.
```

It would be great to expand a little on this, for example, how do I work out how much it costs to use? I am not sure how the size of what I upload relates to the cost in tokens. What would it cost if I tried to uploads an entire PDF book for example? Explaining roughly how RAG works for beginners in the intro would be great :)

**Comment by kiil** [comment]
My question, how do you set the response format to json with aichat (with openai):

`"response_format": {"type": "json_object"}`

see: https://platform.openai.com/docs/guides/text-generation/json-mode

**Comment by sigoden** [comment]
> Cost in tokens

It is easy to estimate the cost.
One million tokens cost approximately $0.01 to $0.10 for embedding.
One million tokens are roughly equivalent to 750,000-800,000 words.
(750,000 words * 6 characters/word) bytes = 4.5 MB approximately

> Explaining roughly how RAG works for beginners in the intro would be great

There are a lot of materials online, so I won't repeat them. If you are really interested, you might as well read the source code directly.
https://github.com/sigoden/aichat/blob/19f5f6c397470630d428792c47b1ba599c4ca192/src/rag/mod.rs#L374

> how do you set the response format to json with aichat

No way. AIChat is a cli tool rather than a library, and it cannot take any parameters. If you really want to return json, you can ask for it in the prompt. In fact, `json_format` is not really needed.

**Comment by kiil** [comment]
> > how do you set the response format to json with aichat
> 
> No way. AIChat is a cli tool rather than a library, and it cannot take any parameters. If you really want to return json, you can ask for it in the prompt. In fact, `json_format` is not really needed.

Asking for it in the system prompt seems to work well.

**Comment by Viv1k** [comment]
Hi,

I don't have access to openai API in my country (Hong Kong). But I have a server in USfrom where I can access openai. I want to set up a proxy server or a client in aichat (local) config so that it can connect to aichat running in US. Is it possible to do so?

I tried --serve and setting the following in the config. It didnot work
```yaml 
# For any platform compatible with OpenAI's API
  - type: openai-compatible
    name: local
    api_base: http://localhost:8080/v1                # ENV: {client}_API_BASE
    api_key: xxx                                      # ENV: {client}_API_KEY
    chat_endpoint: /chat/completions                  # Optional
```

**Comment by dtrckd** [comment]
> Folks, If you have any questions about AICHat, you can first ask the AICHAT Wiki.
> aichat-wiki.mp4

I got this error when trying the rag feature on the aichat wiki : 

```
Unable to run `rag-crawler https://github.com/sigoden/aichat/wiki/ /tmp/aichat-output-3b193bdd-5cb7-4618-9522-f62c01646c68`, Perhaps 'rag-crawler' is not installed?
```
Any hints @sigoden , rag-crawler is not installed automatically with cargo ?

**Comment by sigoden** [comment]
> Any hints @sigoden , rag-crawler is not installed automatically with cargo ?

`rag-crawler` is written in Node.js and should be installed with npm.
https://github.com/sigoden/aichat/blob/17fd7b326097d43a20c7332031bc2f250dd8d4d0/config.example.yaml#L75

**Comment by dtrckd** [comment]
Very funny prompt injection ^^

![image](https://github.com/user-attachments/assets/6e6a5d5f-92e3-4a1b-8827-a4033aa22217)

**Comment by dtrckd** [comment]
How can I activate a pager in the TUI that waits for input before scrolling down when the results overflow the screen height in aichat?

**Comment by sigoden** [comment]
> How can I activate a pager in the TUI that waits for input before scrolling down when the results overflow the screen height in aichat?
No way.

**Comment by dtrckd** [comment]
> No way. Have you seen any other REPLs that have implemented this kind of feature?

Not directly I'd say. The pager that works well for example is the one in [batcat](https://github.com/sharkdp/bat). But I understand it is not an easy thing to do as we don't know the length of the generation in advance in streaming mode.

Concerning the GUI chats, most of them do not scroll down when they generate as it make it difficult to read moving lines.

**Comment by sammcj** [comment]
Would be good to have where to put the config file in the FAQ! 🤣

**Comment by dagelf** [comment]
How do you add multiple API providers?

**Comment by sigoden** [comment]
> Would be good to have where to put the config file in the FAQ! 🤣

@sammcj  ask wiki
![image](https://github.com/user-attachments/assets/1e3ab0d3-d9d5-4011-a200-0794bd6f8849)

> How do you add multiple concurrent API providers, without adding yet another aggregator in front of this?

@dagelf Not supported. I don't think the CLI multiple concurrent API providers.

**Comment by iskaa02** [comment]
is it possible to do text embedding incrementally? i'm crawling a large site and always after nearly 75% i'm facing operation time out error

**Comment by failable** [comment]
How to setup `aichat --serve` by env vars to enable multiple platforms support like using a config file? Should I set `AICHAT_PLATFORM` to only one fixed value?

**Comment by sigoden** [comment]
> How to setup `aichat --serve` by env vars to enable multiple platforms support like using a config file? Should I set `AICHAT_PLATFORM` to only one fixed value?

`AICHAT_PLATFORM`: Combined with `{client}_API_KEY` to run aichat without a configuration file (it will be ignored if a configuration file exists).

If you want to support multiple platforms, you must use a config file.

**Comment by ktunprasert** [comment]
Do you have any plans of adding some sort of "api_key" refresh mechanism? at the moment the Copilot auth token is short lived (less than an hour) so when it fails I have to quit out - reload the key and restart the session.
