### ISSUE TITLE
Session name auto-completion when saving session

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#696]
This function makes it easy to overwrite an existing session that has already been saved. 
(when typing `.save session [name auto completion from existing session]`

**Comment by sigoden** [comment]
Why is this necessary? 
Run `.save session` will overwrite an existing session.
Run `.save session <new-name` will save to `<new-name>.yaml`.

**Comment by dtrckd** [comment]
This is not what I am experiencing (0.19.0) 

1. I am in a session
2. I save it with `.save session <new-name>`
3. when I enter `.save session` it write it to `<temp>`, not `<new-name>`

**Comment by sigoden** [comment]
`.save session` will not change the current session name.
