### ISSUE TITLE
Allow rag file paths to be read from file

### ISSUE THREAD

**Issue by johannesCmayer** [sigoden/aichat#698]
**Is your feature request related to a problem? Please describe.**
Imagine you have a directory that contains both `*.md` files as well as  `*.excalidraw.md` files. You want to rag the `*.md` but not the `*.excalidraw.md` files. Currently, it is not possible to include just the `*.md` files with the 
add_documents can load complex document paths as there is no way to exclude files:
![image](https://github.com/sigoden/aichat/assets/24253624/113ee2fa-7bde-4950-9ccd-61e33fb06e62)

This problem extends to the case where we have a directory with many subdirectories, where we want to include some, but not others.

Typing out all of the paths at the CLI is impractical.

**Describe the solution you'd like**
Load paths from a pre-generated file e.g. paths.txt:
```
/home/gandalf/notes.md
/home/gandalf/spells.md
...
```
That can be generated e.g. with a command like
```shell
find . -type f -not -path '*/.obsidian' -not -path '*/.git' -not -path '*/_media' -iname '*.md' > paths.txt
```

**Comment by sigoden** [comment]
We will not support this feature.

Most well-designed document directories can be loaded directly with format `dir1/` or `dir1/**/*.{ext1,ext2}`.
If there is really no other way, `add_documents` allows input of arbitrary paths.

`paths.txt`  doesn't fit well into the current workflow.

### The solution

**1. Collect paths**
```
find . -type f -not -path '*/.obsidian' -not -path '*/.git' -not -path '*/_media' -iname '*.md' | tr '\n' ';'
 ```

**2. Copy the text and paste it into the `add_documents`**

> There is a minor issue with a trailing semicolon, but we will fix it. Now, simply remove the trailing semicolon.

**Comment by powerman** [comment]
How to handle a project directory which usually contains `.git/`?
It looks reasonable to provide a way to define excluded globs.
Maybe even add `.gitignore` support, to avoid processing files with secrets, binaries, caches, etc.
