### ISSUE TITLE
Model Configuration for Roles to prepare for GPT-4

### ISSUE THREAD

**Issue by XOKP** [sigoden/aichat#70]
GPT-4 has been introduced and its cost is significantly higher than that of GPT-3.5. It may be beneficial to assign the model to each role, thus ensuring that GPT-4 is used only when it is truly needed.

| Model      | Prompt            | Completion           |
| ---------- | ----------------- | -------------------- |
| 8K context | $0.03 / 1K tokens | $0.06 / 1K tokens    |
| 32K context| $0.06 / 1K tokens | $0.12 / 1K tokens    |

**Comment by sigoden** [comment]
#71 supports gpt-4

**Comment by XOKP** [comment]
Using GPT-4 as the default option may gets too costly. Could we also use it based on predefined roles, like the temperature?

**Comment by sigoden** [comment]
User can set the default model through `config.model`.

User can also flexibly switch the current model through `--model` and `.model`.

I haven't figured out whether to bind the model to the role.

**Comment by vrdel** [comment]
However using latest 0.8.0:
```
〉.model gpt-4

〉tell me something


Failed to fetch stream

Caused by:
    Request failed, The model: `gpt-4` does not exist
```

**Comment by icrunchbanger** [comment]
@sigoden 

Same problem here as @vrdel, i have access to GPT-4.

**Comment by sigoden** [comment]
@icrunchbanger 

Try calling the following api to see if you really have the permission for GPT-4.
```
curl https://api.openai.com/v1/models \
  -H "Authorization: Bearer $OPENAI_API_KEY"
```

**Comment by icrunchbanger** [comment]
@sigoden 

Nvm, im a moron. Didnt know there was a waiting list for API access.
