### ISSUE TITLE
aichat Serve costume Role ?

### ISSUE THREAD

**Issue by Alias4D** [sigoden/aichat#716]
1- i make role named SQLY and specified it for my database question answering and its work fine .

2- I run command `aichat --serve`  

3 - I use below command to get response 

curl -X POST -H "Content-Type: application/json" -d '{
  "model":"ollama:qwen2:1.5b-instruct-q8_0",
  "messages":[{"role":"user","content":"hello"}], 
  "stream":true
}' http://127.0.0.1:8000/v1/chat/completions

but cant get answer from my Role named `SQLY`

my question , how make response from SQLY Role which make it lastly

**Comment by sigoden** [comment]
You can't. Please check out `http://127.0.0.1:8000/playground` and see how it uses the role.

Please check out `http://127.0.0.1:8000/playground` and see how the role is used.

The role will be parsed and then added to messages.

**Comment by Alias4D** [comment]
thanks for replay
