### ISSUE TITLE
Add commands from `aichat -e` to shell history file

### ISSUE THREAD

**Issue by santosh** [sigoden/aichat#724]
**Is your feature request related to a problem? Please describe.**

The README says:

> AIChat is aware of OS and shell you are using, it will provide shell command for specific system you have.

Can we use the same to push the command generated from `aichat -e` to bash/\<your-shell\> history?

I found this missing from the first day I started using `-e`. 

**Describe the solution you'd like**

After selecting _Execute_ from the `-e` prompt, the command should be run in such a way that it is automatically added to the user's shell history file.

I use CTRL-r (with fzf) and PageUp (after a few characters) in shell a lot. Both of them depend on the bash history (I use bash). Not sure why the executed command is not getting added at the first place.

**Describe alternatives you've considered**

NA

**Additional context**

OS: Arch Linux
Shell: Bash
Terminal: Kitty

**Comment by sigoden** [comment]
We will not support this feature.

There are various shells available today (bash, zsh, fish, PowerShell, Nushell), and even within a familiar shell like bash, there can be multiple history strategies (.bash_history, atuin, mcfly).  

Aichat can't handle history correctly.

**Comment by tfriedel** [comment]
Wouldn't it  be possible to just insert the commands into the current shell and then the shell would automatically handle insertion into it's history?
I think there's a few other CLI tools that do this. E.g. the mentioned fzf and atuin.

**Comment by santosh** [comment]
@sigoden Well, if it's too complex and/or does not align with the current roadmap, then it's a different story. But **aichat** as a CLI tool, I was really looking forward to it.

In terms of shell support, bash is generic and default on many Linux systems. And with default settings, it uses .bash_history for persistent (I don't believe we need to write to .bash_history manually as @tfriedel suggested above). 

We can do bash, and let other community members think on others? I found something relevant at `man 3 history` (GNU history library).

**Comment by thiswillbeyourgithub** [comment]
Very sad to see that issue with atuin. I understand the situation but there is a good solution for everyone: add a setting like 'pre-execute-hook" that could contain a one liner that would be run when the user selects 'execute' from aichat -e.

This way, all of the complexity of supporting various shells and histories would reside in the user specified hook instead of aichat's dev.
