### ISSUE TITLE
Save the full-text command in the history with shell integration

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#727]
When we use aichat completions with <c-e> to edit a full-text instruction into a command, we sometimes wants to edit it and retry.
But the full-text command is not save in the shell history. 

Can aichat support this feature ?

**Comment by sigoden** [comment]
Shell history is very trivial and has no standard; those who need this should solve it themselves.

**Comment by dtrckd** [comment]
All right. Thanks.
