### ISSUE TITLE
[RAG] Add a command .sources to see the chunks used in the last query

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#728]
When in a RAG mode, it could be very useful to access the chunks used to answer the last query. The use-cases includes : 
- find the doc/url in which there is the information you are looking for.
- understand/debug why the model say something.

**Comment by sigoden** [comment]
We will not support this feature.

Reason:

1. In addition to plain text, many formats (pdf, docx...) rely on document loaders for conversion, so it is difficult to locate the source.

2. WebUI can open files and highlight chunks, which is difficult to achieve on TUI. This makes this feature not very useful.

**Comment by sigoden** [comment]
For debugging, the recommended approach is to use `debug.log`.

**Comment by dtrckd** [comment]
Thank you for your answer, @sigoden. I have a slightly different viewpoint:

- I believe that the interest in RAG/sourcing, specifically lowering the barrier between LLMs and search engines, is a growing field that captures a large audience.
- The source could simply be a file or a URL.
- My point is to identify the relevant documents (either files on disk or URLs) that powered the LLM response in case one wants to delve deeper. Which is particularly convenient if the RAG has hundreds or more documents...
