### ISSUE TITLE
Database SQL Console like shell aichat -e

### ISSUE THREAD

**Issue by Alias4D** [sigoden/aichat#729]
My idea :
Natural language >> SQL Statement >> RUN on SQL Console >> Result  

just like shell terminal .
aichat -e what is max. sales in year 2024 ? >>  [Select sum(sales) from company-table group by year ] >> execute on database console directly ang get result after get conformation from user 
all database connection parameter available

**Comment by sigoden** [comment]
We encourage using tools/agents to achieve similar requirements. 

see https://github.com/sigoden/llm-functions
