### ISSUE TITLE
Modify role just for one command

### ISSUE THREAD

**Issue by vlp-git** [sigoden/aichat#73]
(thanks for the apps !)

Sometime I need to adapt the profile for a specific request for instance: 
`aichat -r shell install htop packet`
but this time, I use alpine linux, so I would need this time something like:
`aichat -r shell --extra-role "I want you to use alpine linux" install htop packet`

Thanks

**Comment by sigoden** [comment]
Here are many options you can choose:

## use prompt

aichat -p "I  want you to use alpine linux"   install htop packet

## use  role arg

```
- name: shell:linux
  prompt: >
    I want you to act as a __ARG1__ shell expert.
    I want you to answer only with code.
    Do not write explanations.
```

aichat -p shell:alpine-linux install htop packet

**Comment by vlp-git** [comment]
yes the 2nd options work as the first doesn't merge "I want you to use alpine linux"  and the "shell profile"

**Comment by vlp-git** [comment]
> yes the 2nd options work as the first doesn't merge "I want you to use alpine linux" and the "shell profile"

 I correct myself, option 1 works as well
