### ISSUE TITLE
Issues with GPT4o function calling

### ISSUE THREAD

**Issue by hkrutzer** [sigoden/aichat#730]
I am using aichat with argc to give the LLM access to an R programming environment. With gpt4o, this frequently results in errors. With Claude this issue does not happen.

**Describe the bug**

```
Failed to call chat-completions api

Caused by:
    Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'. (type: invalid_request_error)
```

**To Reproduce**

I'm using this:

```sh
#!/usr/bin/env bash
set -e

# @describe Get the current weather in a given location.
# @option --code! The R code to execute

main() {
    Rscript --restore --save -e "$argc_code" >> "$LLM_OUTPUT" 2>&1 || true
}

eval "$(argc --argc-eval "$0" "$@")"
```

to run the R code. I haven't yet been able to reproduce this exact error Python, let me know how I can make debugging easier.

**Expected behavior**
No error

**Screenshots/Logs**
![2024-07-20 at 17 52](https://github.com/user-attachments/assets/1a6d3414-b5e9-4481-942a-a25c10ceb92b)

Another error that might be related:

<img width="1333" alt="image" src="https://github.com/user-attachments/assets/2f32646b-cd9c-4f71-9bb8-1e162b3ed7b6">

but this could also be an issue with the model.

**Configuration**
```
model                   azure-openai-eastus2:gpt-4o
max_output_tokens       -
temperature             -
top_p                   -
dry_run                 false
save                    false
keybindings             emacs
wrap                    no
wrap_code               false
save_session            -
compress_threshold      4000
function_calling        true
rag_reranker_model      -
rag_top_k               4
highlight               true
light_theme             false
```

**Environment (please complete the following information):**
- os version: macos 13
- aichat version: 0.19.0
- terminal version: wezterm

**Comment by sigoden** [comment]
This problem seems to be a bug in the LLM itself.
https://community.openai.com/t/chatgpt-occasionally-reuses-tool-ids-in-the-same-session/577207

Run the debug version of aichat to get the request data for the problematic requests.
```
git clone https://github.com/sigoden/aichat
cargo run
```
A `debug.log` file will be generated in the `<aichat-config-dir>` directory, which contains all request data.
