### ISSUE TITLE
Automatically create the aichat directory

### ISSUE THREAD

**Issue by pup-tv** [sigoden/aichat#732]
Wonderful Project!  Thanks for sharing!

If you don't cargo install aichat, the directory .config/aichat isn't automatically created which leads to slightly unhelpful error message about an unnamed missing directory.

I fixed it with a small edit in config/mod.rs:

    pub fn local_path(name: &str) -> Result<PathBuf> {
        let mut path = Self::config_dir()?;
        std::fs::create_dir_all(&path)?;  // <---   New command here
        path.push(name);
        Ok(path)
    }

You may want to fix it another way.

**Comment by sigoden** [comment]
Please submit an new issue, and tell us how to reproduce the problem.

We can't modify the code just because you said so.

**Comment by pup-tv** [comment]
I'll try this first...

If you don't cargo install aichat, then you don't have a .config/aichat directory...

To recreate the problem, just delete the .config/aichat directory or equivalent.  (I only have experience on a linux system)

When the directory doesn't exist, creating config.yaml pops up an error saying "No such file or directory"

Thanks

**Comment by sigoden** [comment]
The `.config/aichat` directory will be created automatically if anything is saved to it.

**Comment by pup-tv** [comment]
No, it won't...   ask me how I know.

**Comment by sigoden** [comment]
If not, there is a bug. Tell me how to reproduce the bug

**Comment by pup-tv** [comment]
What's the most helpful way?  A video?  

I did quite a bit of debugging, perhaps the backtrace would be a better place to start.

**Comment by pup-tv** [comment]
/exbak/exproj/aichat/aichat/target/debug/aichat
Error: No such file or directory (os error 2)

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /home/d/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.86/src/backtrace.rs:27:14
   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/1871252fc8bb672d40787e67404e6eaae7059369/library/core/src/result.rs:1964:27
   2: aichat::logger::setup_logger
             at ./src/logger.rs:14:20
   3: aichat::main::{{closure}}
             at ./src/main.rs:55:5
   4: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/d/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
   5: tokio::runtime::coop::with_budget
             at /home/d/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
   6: tokio::runtime::coop::budget
             at /home/d/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
   7: tokio::runtime::park::CachedParkThread::block_on
             at /home/d/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
   8: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/d/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
   9: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/d/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  10: tokio::runtime::context::runtime::enter_runtime
             at /home/d/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/d/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  12: tokio::runtime::runtime::Runtime::block_on
             at /home/d/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:349:45
  13: aichat::main
             at ./src/main.rs:151:5
  14: core::ops::function::FnOnce::call_once
             at /rustc/1871252fc8bb672d40787e67404e6eaae7059369/library/core/src/ops/function.rs:250:5
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/1871252fc8bb672d40787e67404e6eaae7059369/library/std/src/sys_common/backtrace.rs:155:18
  16: std::rt::lang_start::{{closure}}
             at /rustc/1871252fc8bb672d40787e67404e6eaae7059369/library/std/src/rt.rs:159:18
  17: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/1871252fc8bb672d40787e67404e6eaae7059369/library/core/src/ops/function.rs:284:13
  18: std::panicking::try::do_call
             at /rustc/1871252fc8bb672d40787e67404e6eaae7059369/library/std/src/panicking.rs:559:40
  19: std::panicking::try
             at /rustc/1871252fc8bb672d40787e67404e6eaae7059369/library/std/src/panicking.rs:523:19
  20: std::panic::catch_unwind
             at /rustc/1871252fc8bb672d40787e67404e6eaae7059369/library/std/src/panic.rs:149:14
  21: std::rt::lang_start_internal::{{closure}}
             at /rustc/1871252fc8bb672d40787e67404e6eaae7059369/library/std/src/rt.rs:141:48
  22: std::panicking::try::do_call
             at /rustc/1871252fc8bb672d40787e67404e6eaae7059369/library/std/src/panicking.rs:559:40
  23: std::panicking::try
             at /rustc/1871252fc8bb672d40787e67404e6eaae7059369/library/std/src/panicking.rs:523:19
  24: std::panic::catch_unwind
             at /rustc/1871252fc8bb672d40787e67404e6eaae7059369/library/std/src/panic.rs:149:14
  25: std::rt::lang_start_internal
             at /rustc/1871252fc8bb672d40787e67404e6eaae7059369/library/std/src/rt.rs:141:20
  26: std::rt::lang_start
             at /rustc/1871252fc8bb672d40787e67404e6eaae7059369/library/std/src/rt.rs:158:17
  27: main
  28: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  29: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  30: _start
Process finished with exit code 1

**Comment by sigoden** [comment]
I know what the problem is.

The debug version of aichat will write to the log file `<aichat-config-dir>/debug.log`, but the `<aichat-config-dir>` does not exist.

**Comment by pup-tv** [comment]
Thoughts on a fix/work-around?   I think it be helpful to avoid this seemingly easy to avoid issue in the future with just a couple of extra lines, even if it's just to ignore the write to debug.log until the folder exists.

**Comment by sigoden** [comment]
I will fix the issue.

I know where the bug is, but I still curious how the bug arose.

If there is no `<aichat-config-dir>`, aichat will ask you to create config.yaml when it starts, and will also create a new directory aichat-config-dir, which will still not cause the bug.

![image](https://github.com/user-attachments/assets/ee5a7f5f-979d-4cf7-8fc5-6bfb71568bea)

Did you specify the new config.yaml path using environment variable AICHAT_CONFIG_FILE?

**Comment by pup-tv** [comment]
Did not setup a AICHAT_CONFIG_FILE environment variable.

Never saw the "create the config.yaml question." Just got a "No such file or directory" error.

**Comment by sigoden** [comment]
Could you please clarify how to reproduce the bug? This should never happen under normal circumstances.

You need to double-check the environment variables.

**Comment by pup-tv** [comment]
Just did a git clean -f and reset --hard, and now it's working.

I had a very recent (less than 24h old) pull that was showing the issue, but now it's fixed. (Updating 17fd7b3..704a096)

What I was seeing:
d@pc:/exbak/exproj/aichat/aichat$ cargo run
   Compiling aichat v0.19.0 (/exbak/exproj/aichat/aichat)
warning: unused import: `log::LevelFilter`
  --> src/config/mod.rs:35:5
   |
35 | use log::LevelFilter;
   |     ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `aichat` (bin "aichat") generated 1 warning (run `cargo fix --bin "aichat"` to apply 1 suggestion)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.15s
     Running `target/debug/aichat`
Error: No such file or directory (os error 2)

Now it's fixed, so all good!  Thanks!
