### ISSUE TITLE
[Feature Request] Add option to pass prompt as file

### ISSUE THREAD

**Issue by pwntester** [sigoden/aichat#744]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I have a library of prompts in separated files. I would love to be able to use `-p <prompt>` for text prompt and `-P <file path>` for reading the prompt from a file

**Describe alternatives you've considered**
Currently you can use `--prompt "$(</path/to/prompt/file)"` to get the desired behaviour but I would prefer a shorter and "native" solution.

**Additional context**

**Comment by sigoden** [comment]
we will not support this feature.

We encourage managing multiple prompts via roles.yaml
`--prompt` is just an escape hatch and not encouraged.

**Comment by pwntester** [comment]
Would it be possible to add `include` functionality in `roles.yml` then? Something along the lines of:

```
- name: summarize
  prompt: !include ~/promtps/summarize.yml
```
