### ISSUE TITLE
经常遇到连接失败的提示

### ISSUE THREAD

**Issue by ali50m** [sigoden/aichat#75]
配置了key和socks5代理,不知道为什么有大概率会遇到下面的错误. 

用过另外一个叫GptCli的程序,那个设置了代理后连接问答就很稳定.

```pwsh
aichat 写一个计算pi的c#程序
```

```
Error: Failed to fetch stream

Caused by:
    0: error sending request for url (https://api.openai.com/v1/chat/completions): error trying to connect: operation timed out
    1: error trying to connect: operation timed out
    2: operation timed out
```

**Comment by sigoden** [comment]
AICHAT has a 10-second connection timeout. If the API cannot be connected within 10 seconds, this error will be reported.

Your problem is caused by bad internet connection.

AICHAT may allow config longer timeouts in the future.
