### ISSUE TITLE
Trailing slash in api_base for openai compatible model cause 404 not found error

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#767]
**Describe the bug**

Setting an `api_base` in a openai compable model with something like `my_url/v1/` in the config, makes aichat fails on finding the url.

If I use `my_url/v1` it works. Furthermore the config.example.yml documentation indicates the first approach. 

**Environment (please complete the following information):**

- aichat version:  v0.19

**Comment by sigoden** [comment]
There is no need for a trailing slash, `config.example.yaml` also states this.

https://github.com/sigoden/aichat/blob/a0d421ffc83ba97a1f99f1ba9f85a1689941d171/config.example.yaml#L114
