### ISSUE TITLE
Add text to speech feature

### ISSUE THREAD

**Issue by Databingo** [sigoden/aichat#78]
Nice work, could you add a feature could speak the response message directly? 
For example, on Mac OS we can use “say `message`" command easily.

**Comment by sigoden** [comment]
Sorry, I have no plan to add this feature in the short term.

Here are reasons:
- A similar effect can be achieved through the tts function that comes with the system
- This feature is not what most people need.
- Integrating this feature may greatly increase binary size and memory consumption
- It is difficult to support multiple platforms, and many scenarios cannot be used at all (such as ssh, wsl)
