### ISSUE TITLE
Ability to suspend aichat (Ctrl+Z)

### ISSUE THREAD

**Issue by einarpersson** [sigoden/aichat#781]
**Is your feature request related to a problem? Please describe.**
Currently, aichat lacks the ability to suspend its execution and return to the shell, which is a common feature in many CLI applications (e.g., Neovim's Ctrl+Z functionality).

I might be in the middle of an aichat session and want to quickly check a file or run a command. I'd like to suspend aichat, perform the task, and then resume their session without losing context.

**Describe the solution you'd like**
Implement job control in aichat, allowing users to:

1. Suspend aichat and return to the shell (e.g., using Ctrl+Z)
2. Resume aichat from the shell (e.g., using fg)

Benefits
- Improved workflow: Users can quickly switch to the shell for other tasks without closing aichat
- Consistency with other CLI tools: Aligns aichat with user expectations for terminal applications

**Describe alternatives you've considered**
- Use tmux, which is what I currently do.
- Add a new command to aichat (eg. `.command` or `.sh` or `.shell` or `.run`) that would run a shell command, inline the result and return to aichat. However, this may create a host of new issues, such as handling the output of the command, and would not be as flexible as job control. 

**Additional context**
I have little experience with job control, so I'm not sure how difficult it would be to implement in aichat. I can live with it if it's too much work, but I think it would be nice to align with other tools.

**Comment by einarpersson** [comment]
(Note: Feel free to close if not prioritized right now and it is a lot of work. It's really most a nice-to-have which I can work around for the moment)

**Comment by sigoden** [comment]
- `Ctrl + Z` is the key binding for undo https://github.com/sigoden/aichat/issues/351#issuecomment-1991129537
- `Ctrl + Z` is not a cross-platform and cross-shell feature.
