### ISSUE TITLE
Feature request: OpenAI structured outputs.

### ISSUE THREAD

**Issue by 0x0f0f0f** [sigoden/aichat#782]
OpenAI recently released https://openai.com/index/introducing-structured-outputs-in-the-api/ 

Is this planned to be supported?

**Comment by sigoden** [comment]
we can't find how to integrate `structured outputs` into CLI tool.

If you really want to experience this feature, you can try `AICHAT_PATCH_OPENAI_CHAT_COMPLETIONS`.
