### ISSUE TITLE
Make `-e` compatible with `-R` to execute customized commands

### ISSUE THREAD

**Issue by cjbarroso** [sigoden/aichat#785]
**Is your feature request related to a problem? Please describe.**
No, it's just a feature that I think more people will like.

**Describe the solution you'd like**
I want to be able to combine a RAG with the shell execution feature. This way I can ask aichat to make shell commands tailored to my needs every time and avoid writing the instructions every time I want to use it.

**Describe alternatives you've considered**
From my understanding, the only change required is that we allow the `-e` argument be compatible with the RAG `-R` argument. I've used the debug function, created my own `%shell%` prompt and I got it to do what I want, it outputted just the command following my preferences. In this example I want the find operations use the `fdfind` inseat of the unix standard `find`. Unfortunately it just output the command, not integrated with the very nice interface the `-e` command provides.

**Additional context**
I think this change may enable more people to do more creative things with their operating systems. In my case as I have ADHD I make decisions about tools or ways to do things that I later forget. I've started using a "wisdom" folder with .txt files containing such decisions, and I've made aichat to use it as a RAG. Now, if I just manage to not only know but also format and use the commands I choose in the past, that will be perfect.
I've implemented the thing on my own using shell scripting, but any change is very painful. When I got acquainted with aichat I understood that it is a better base tool to build it. Unfortunately I don't know Rust and I'm far from learning it.

**Comment by sigoden** [comment]
we will not support this feaure. 

It is recommended to achieve tailored `hell commands` through the following two strategies.

1. Use your own `%shell%`. You can create a shell named `%shell%` in roles.yaml, and Aichat will use it with `-e` (override the built-in `%shell%` role).

2. Create an agent with RAG and the `execute_command` tool.
