### ISSUE TITLE
[Error] Please enable function calling before using the agent.

### ISSUE THREAD

**Issue by oatmealm** [sigoden/aichat#790]
**Describe the bug**

Unable to start an agent. Core aichat works as expected, models are usable, rag is usable etc...

**To Reproduce**

1. Clone functions repo

1. Add agents and functions to `agents.txt` or `tools.txt` as needed 

3. Link functions repo under `~/.config/aichat/functions`

**Configuration**

```
aichat --agent coder

Please enable function calling before using the agent.

ls ~/.config/aichat/functions/
agents  agents.txt  Argcfile.sh  LICENSE  README.md  scripts  tools  tools.txt
```

**Environment (please complete the following information):**

```
system     "Fedora Linux 40 (Workstation Edition)" Linux 6.10.5-200.fc40.x86_64 x86_64

aichat 0.20.0

which aichat
~/.cargo/bin/aichat
```

default model: `model: ollama:llama3.1:8b-instruct-q4_0   # Specify the LLM to use`

Config:

```
models:
      - name: llama3.1:8b-instruct-q4_0
        max_input_tokens: 8192
        supports_function_calling: true
```

**Comment by sigoden** [comment]
@oatmealm 
> Unable to start an agent. 
What does this mean? You need to report the error details.

**Comment by oatmealm** [comment]
That's the error I'm seeing when I try to start an agent, i.e. `aichat --agent coder`

**Comment by sigoden** [comment]
@oatmealm 

I still don't understand the issue you are describing. Is taking a screenshot really that hard?

**Comment by sigoden** [comment]
It is recommended to submit bugs by https://github.com/sigoden/aichat/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

We can't help you without bug details.

**Comment by sigoden** [comment]
@oatmealm 

please submit the output of `aichat --info`.

![image](https://github.com/user-attachments/assets/4eb682ef-03e4-4bd0-b070-f92434964a9b)

The `function_calling` must be `true`. If you install `llm-functions` correctly, it should be true.

**Comment by oatmealm** [comment]
Oh, I see. Sorry for the messy report.
I'm not sure if function calling as implemented by aichat is an implementation detail of aichat or depends on abilities of the model itself...? AFAIK llama3 under ollama doesn't support function calling natively.

I have a model setup this way:

```
models:
      - name: llama3.1:8b-instruct-q4_0
        max_input_tokens: 8192
        supports_function_calling: true
```

```
model                   ollama:llama3.1:8b-instruct-q4_0
max_output_tokens       -
temperature             -
top_p                   -
dry_run                 false
stream                  true
save                    true
keybindings             emacs
wrap                    no
wrap_code               false
save_session            -
compress_threshold      4000
function_calling        false
use_tools               -
rag_reranker_model      jina:jina-reranker-v2-base-multilingual
rag_top_k               4
highlight               true
light_theme             false
config_file             /home/xxx/.config/aichat/config.yaml
roles_file              /home/xxx/.config/aichat/roles.yaml
env_file                /home/xxx/.config/aichat/.env
functions_dir           /home/xxx/.config/aichat/functions
rags_dir                /home/xxx/.config/aichat/rags
sessions_dir            /home/xxx/.config/aichat/sessions
messages_file           /home/xxx/.config/aichat/messages.md
```

**Comment by sigoden** [comment]
@oatmealm 

In your AIChat info, the value of `function_calling` is false. This is the reason for the error. You may not have successfully installed llm-functions.



Perform the following checks:
1. Ensure `llm-functions` is installed correctly, does the directory `/home/xxx/.config/aichat/functions` exist? does `/home/xxx/.config/aichat/functions/functions.json` exist?
2. Ensure there is no `function_calling: false` in `config.yaml`.

**Comment by oatmealm** [comment]
I see. I was working of the example config file but didn't copy over the functions section.  That's taken care of.
I don't see any `functions.json` though...

**Comment by sigoden** [comment]
@oatmealm 

> III. Run `argc build` to build tools and agents.

Maybe you missed this operation.

**Comment by oatmealm** [comment]
It errors on building coder but produces the json file. Thanks for the help I think I can continue from here 😅
