### ISSUE TITLE
Enable custom api_base URL for all providers type

### ISSUE THREAD

**Issue by kwekewk** [sigoden/aichat#792]
**Is your feature request related to a problem? Please describe.**

`Gemini API free tier is not available in your country. Please enable billing on your project in Google AI Studio.`
`api_base` in config only works for OpenAI-compatible providers, limiting workarounds for region-restricted APIs like Gemini and Claude. Therefore custom `api_base` is necessary, allow user use their own proxy server or example Helicone, then change the default `api_base`.
 
**Describe the solution you'd like**

Abillity to set api_base to all provider.

**Comment by sigoden** [comment]
It's just that OpenAI came out early and became the standard. There are many agents and compatible providers whose `api_base` makes sense, but other providers are not like that.

The API of the `gemini` client is fixed: `https://generativelanguage.googleapis.com/v1beta/models/`, no way for a custom `api_base`.

Given your situation, perhaps you should try `vertexai` client, see https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models

**Comment by kwekewk** [comment]
For gemini i believe its `https://generativelanguage.googleapis.com`
Example what Helicone does, they add some headers and change the baseurl [Claude](https://docs.helicone.ai/integrations/anthropic/curl) and [Gemini](https://docs.helicone.ai/integrations/gemini/api/curl)
Yes, I do set up a proxy like LiteLLM, but it consumes too many resources if it goes above 200 models.

**Comment by sigoden** [comment]
Helicone is the first proxy I've encountered that supports `Gemini` and `Claude`.

**Comment by kwekewk** [comment]
Okay, i knew few baseurl
gemini: `https://generativelanguage.googleapis.com`
claude: `https://api.anthropic.com/v1`
cohere: `https://api.cohere.ai/v1`
qianwen: `https://dashscope.aliyuncs.com` they also have openai-compatible `https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions`

**Comment by sigoden** [comment]
@kwekewk 

### 1. The version is important and must not be omitted.

gemini: `https://generativelanguage.googleapis.com/v1beta`

### 2. The openai-compatible qianwen does not support stream function calling. If support is added later, it will be possible to migrate to an OpenAI-compatible client.
