### ISSUE TITLE
In latest version responses are no longer copied to clipboard on Mac OS

### ISSUE THREAD

**Issue by DeonNel1** [sigoden/aichat#794]
set in my config.yaml however after updating to
**Describe the bug**

I have auto_copy: true                 # Automatically copy the last output to the clipboard
in my config.yaml however since updating to the latest version responses are no longer copied to the clipboard.

**To Reproduce**

Update to the latest aichat on mac OS and set the above flag.  After that start a conversation with any model and try paste the response in any editor.

**Expected behavior**

The latest response should be copied to the clipboard.

**Screenshots/Logs**

**Configuration**

model: claude:claude-3-5-sonnet-20240620
temperature: 1.0                 # GPT temperature, between 0 and 2
save: true                       # Whether to save the message
highlight: true                  # Set false to turn highlight
light_theme: false               # Whether to use a light theme
wrap: auto                         # Specify the text-wrapping mode (no, auto, <max-width>)
wrap_code: false                 # Whether wrap code block
auto_copy: true                 # Automatically copy the last output to the clipboard
keybindings: emacs               # REPL keybindings. (emacs, vi)
prelude: ''                      # Set a default role or session (role:<name>, session:<name>)

**Environment (please complete the following information):**
- os version: [e.g. Ubuntu 20.04]
Mac OS latest 

- aichat version: [e.g. 0.9.0]
- aichat 0.20.0
- 
- terminal version: [e.g. GNOME Terminal 3.44.0]
default mac OS terminal

**Additional context**

**Comment by sigoden** [comment]
see #607
