### ISSUE TITLE
Any method to visualize markdown contents?

### ISSUE THREAD

**Issue by guanghaoch** [sigoden/aichat#801]
Hi, I'm using Aichat in Mac terminal. Can anyone suggest some methods to visualize markdown equations?

**Comment by sigoden** [comment]
Not working in the terminal, but it works in the web UI. Try using the LLM playground.

**Comment by kvn1351** [comment]
> It can't be implemented, especially since AIChat needs to support streaming output.

https://github.com/day50-dev/Streamdown

https://github.com/Gaurav-Gosain/streamd

Both of these can be used by piping aichat to them. Perhaps you could take some inspiration from them?
