### ISSUE TITLE
Replace `roles.yaml` with `roles/<name>.md`

### ISSUE THREAD

**Issue by sigoden** [sigoden/aichat#804]
Instead of using a central `roles.yaml` file to store all the roles, we can use a dedicated roles folder. Each file within this folder would represent a single role, with the filename corresponding to the role's name.

#### Benefits

- Create/Edit a single role within the REPL
- Load on demand, resulting in less memory usage

#### REPL

- `.role <name>`: Create a new role if one doesn't exist
- `.edit role`: Edit the current role
- `.save role`: Save the current role to file

#### Options

```md
---
model: openai:gpt-4
temperature: 0
top_p: 0
...
---

Your are a ...
```

**Comment by sigoden** [comment]
We provide a Python script to convert `roles.yaml` to `roles/<name>.md`

```py
import yaml
import os

def convert(yaml_file, saved_dir):
    with open(yaml_file, 'r', encoding='utf-8') as f:
        yaml_content = f.read()

    data = yaml.safe_load(yaml_content)
    
    os.makedirs(saved_dir, exist_ok=True)

    for item in data:
        if 'name' not in item or 'prompt' not in item:
            continue  # Skip items that do not have the necessary fields

        name = item.pop('name')
        prompt = item.pop('prompt')
        
        markdown_file = os.path.join(saved_dir, f"{name}.md")

        metadata = ''
        if item:
            metadata = '---\n' + yaml.dump(item) + '---\n\n'
        
        with open(markdown_file, 'w', encoding='utf-8') as f:
            f.write(metadata + prompt)

convert("roles.yaml", "roles")
```

```
cd <aichat-config-dir>
python convert.py
```

**Comment by jiahut** [comment]
Confirm if there are any parameters that don't support `__ARG1__` ? 
I used the script locally and the original role included `__ARG1__` failed to convert the role

**Comment by sigoden** [comment]
@jiahut

We have deprecated Role Arguments.

Alternatives:
- Expand `ARG` to independent roles. `translate:zh` -> translate-zh.md . `translate:sp` -> translate-sp.md
- Use AI agent instead of role; it has variables.

**Comment by fmaida** [comment]
> We provide a Python script to convert `roles.yaml` to `roles/<name>.md`
> 
> ```python
> import yaml
> import os
> 
> def convert(yaml_file, saved_dir):
>     with open(yaml_file, 'r', encoding='utf-8') as f:
>         yaml_content = f.read()
> 
>     data = yaml.safe_load(yaml_content)
>     
>     os.makedirs(saved_dir, exist_ok=True)
> 
>     for item in data:
>         if 'name' not in item or 'prompt' not in item:
>             continue  # Skip items that do not have the necessary fields
> 
>         name = item.pop('name').replace(':', '#')
>         prompt = item.pop('prompt')
>         
>         markdown_file = os.path.join(saved_dir, f"{name}.md")
> 
>         metadata = ''
>         if item:
>             metadata = '---\n' + yaml.dump(item) + '---\n\n'
>         
>         with open(markdown_file, 'w', encoding='utf-8') as f:
>             f.write(metadata + prompt)
> 
> convert("roles.yaml", "roles")
> ```
> 
> ```
> cd <aichat-config-dir>
> python convert.py
> ```

Thank you for the script. However, please remember to the viewers that in order to work this scripts requires the library pyyaml installed ( https://pypi.org/project/PyYAML/ ).
So if you want to run this script from the command line, maybe you should enter this:

```sh
cd <aichat-config-dir>
python -m venv .venv
source .venv/bin/activate  # if you use bash or zsh, if you are using Fish use "source .venv/bin/activate.fish"
pip install pyyaml
python convert.py
```

**Comment by xeruf** [comment]
Would be nice to have a link to this included when not finding a role for the next few versions, took me a while to get here after my existing roles unexpectedly stopped working

**Comment by xeruf** [comment]
aichat could also offer to automatically run the migration

small issue, this role is not correctly converted:
```yaml
- name: convert:json:yaml
  prompt: convert __ARG1__ below to __ARG2__
```
