### ISSUE TITLE
Automatically create session name

### ISSUE THREAD

**Issue by achhina** [sigoden/aichat#805]
Hi, thanks for the work here, I've been really enjoying using `aichat`! I tried to look through the docs and issues to see if the following feature request is available but wasn't able to find it, but apologies if I missed it.

**Is your feature request related to a problem? Please describe.**

I want to have sessions automatically saved on exit, which includes `temp` sessions. I do not particularly care about the session name usually, and just want the session name to include the timestamp, to roughly know when this session occurred.

The use case here is that I loosely recall a conversation that I found useful retroactively and would like to remember what happened. Having all sessions saved would allow me to quickly search through existing session conversations to find the relevant chat.

**Describe the solution you'd like**

As an MVP I would add a config option that automatically names unnamed sessions as the timestamp of when the session was created.

Something more user friendly later on could include the session name suffixed with an autogenerated session summary name from a model with a title prompt. There could be a separate config to opt into this and provide an alternate title prompt or model.

**Comment by sigoden** [comment]
@achhina 

We will implement the feature in the following way:

The auto-generate session will be triggered only under the following conditions:

1. The config has `save_session: true`.
2. Run `.session` to enter a new session without providing a name.

The session will be auto-saved as `temp-<datetime>.md` (e.g. `temp-20240828231512.md` ) when an existing session exits.

We will not add new configurations for auto-generating session names, nor generate them based on the summary.

**Comment by achhina** [comment]
Thank you for the speedy turn around! Would you know when I can expect to see this in a new release? No urgency here, I just wasn't aware if there were any releases planned and if this would be included in it.

**Comment by sigoden** [comment]
We will release a new version in a few days.
