### ISSUE TITLE
Error: No available model

### ISSUE THREAD

**Issue by Hinatara** [sigoden/aichat#817]
![Screenshot_2024-09-01-08-41-41-26_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/109cb338-ed8d-4310-a50e-70209fd3ef97)
Help me with it now what to do.
......
Thanks admin .
.......

**Comment by sigoden** [comment]
Aichat already explains what happened; the `clients` field in the config.yaml is invalid.


Two Methods:

- Delete `config.yaml` and run it again; let `aichat` help you create `config.yaml`.
- Edit `config.yaml` manually, following https://github.com/sigoden/aichat/blob/main/config.example.yaml
