### ISSUE TITLE
Random channel closing on linux

### ISSUE THREAD

**Issue by tiphaineruy** [sigoden/aichat#833]
**Describe the bug**

Request often fails mid streaming  with "channel closed" 

**To Reproduce**

make requests that have a large response

**Expected behavior**

no channel closed. timeout issue ?

**Screenshots/Logs**

```
> a request
start of answer then
The cursor position could not be read within a normal duration

Failed to send ReplyEvent::Done

Caused by:
    channel closed


> .info
model                   claude:claude-3-5-sonnet-20240620
max_output_tokens       8192 (current model)
temperature             -
top_p                   -
dry_run                 false
stream                  true
save                    false
keybindings             emacs
wrap                    no
wrap_code               false
save_session            -
compress_threshold      4000
function_calling        true
use_tools               -
rag_reranker_model      -
rag_top_k               4
highlight               true
light_theme             false
config_file             /home/tiphaine/.config/aichat/config.yaml
roles_dir               /home/tiphaine/.config/aichat/roles
env_file                /home/tiphaine/.config/aichat/.env
functions_dir           /home/tiphaine/.config/aichat/functions
rags_dir                /home/tiphaine/.config/aichat/rags
sessions_dir            /home/tiphaine/.config/aichat/sessions
messages_file           /home/tiphaine/.config/aichat/messages.md
```

**Configuration**

**Environment (please complete the following information):**
- os version: NAME="TUXEDO OS"
VERSION="3 22.04.4"
- aichat version: 0.21.1
- terminal version: kitty 0.35.2

**Comment by fn5** [comment]
There are currently API issues reported as of two minutes ago: https://status.anthropic.com/incidents/090c72v2y6pd

**Comment by sigoden** [comment]
@tiphaineruy 

Normally, the error `Failed to send ReplyEvent::Done` should not occur. Even if there is a network issue, it shouldn't happen.

The relevant code has been stable for at least 4 months, and you are the only one reporting this bug.

Can you describe it in detail or provide some logs?

**Comment by tiphaineruy** [comment]
I've actually been having this issue for 1 or 2 months on my new linux machine.
Afraid there isn't much more logs than this unless I can enable a verbose mode in aichat ? Happy to help if need. I'll try from source later and see If I get the same errors

but the use case is  start aichat, make requests, and at some point randomly the error message that is displayed in my original post is appended
```
The cursor position could not be read within a normal duration

Failed to send ReplyEvent::Done

Caused by:
    channel closed
```
ending the response

the cli doesn´t crash and if I make subsequent request they succeed.

**Comment by sigoden** [comment]
@tiphaineruy 

After some investigation, I found that the problem here.

https://github.com/sigoden/aichat/blob/d92f102a85eb98ee0cb3eaa8a775b7d3528090ac/src/render/stream.rs#L81

```rs
// https://github.com/crossterm-rs/crossterm/blob/9a6d740ed52c23c3ebaa3d24841d4a441817e160/src/cursor/sys/unix.rs#L39-L50
fn read_position_raw() -> io::Result<(u16, u16)> {
    // Use `ESC [ 6 n` to and retrieve the cursor position.
    let mut stdout = io::stdout();
    stdout.write_all(b"\x1B[6n")?;
    stdout.flush()?;

    loop {
        match poll_internal(Some(Duration::from_millis(2000)), &CursorPositionFilter) {
            Ok(true) => {
                if let Ok(InternalEvent::CursorPosition(x, y)) =
                    read_internal(&CursorPositionFilter)
                {
                    return Ok((x, y));
                }
            }
            Ok(false) => {
                return Err(Error::new(
                    ErrorKind::Other,
                    "The cursor position could not be read within a normal duration",
                ));
            }
            Err(_) => {}
        }
    }
}
```

It seems your terminal has poor performance, and it is unable to get the cursor position within 2 seconds.

**Comment by sigoden** [comment]
@tiphaineruy 

I find it difficult to reproduce this issue on my end. I have submitted a fix, and could you test it?
