### ISSUE TITLE
Allow specifying serve address via config.yml

### ISSUE THREAD

**Issue by av** [sigoden/aichat#834]
**Is your feature request related to a problem? Please describe.**

Currently, when I want to customize how `aichat` is served, I can specify an argument for `--serve` option:
```bash
aichat --serve 0.0.0.0:34051
```

I would like to have an option to pre-configure the CLI via either env var or `config.yml` file so that I can run the serve without specifying address explicitly.

**Describe the solution you'd like**

```bash
# Via env
AICHAT_ADDRESS=0.0.0.0:34051 aichat --serve

# Via config.toml
address: 0.0.0.0:34051
```

It'd be even better to be able to specify host/port pair separately, but I understand that it's a bit more to ask

**Comment by sigoden** [comment]
We will implement this feature, but we will use `server_address` instead of `address`.

```
# Via Env
AICHAT_SERVER_ADDRESS=0.0.0.0:3000

# Via config.yaml
server_address: 0.0.0.0:3000
```
