### ISSUE TITLE
"No available embedding model" with Ollama

### ISSUE THREAD

**Issue by jadbox** [sigoden/aichat#836]
AIChat 0.21.1

When selecting Ollama, there's no ability to select a RAG model (like mxbai-embed-large:latest).

Related: it would be awesome if AIChat could auto discover models installed in Ollama without having to specify names exactly.

**Comment by sigoden** [comment]
AIChat v0.21.1 already includes some favorite models for ollama:

https://github.com/sigoden/aichat/blob/d92f102a85eb98ee0cb3eaa8a775b7d3528090ac/models.yaml#L322-L345

If your Ollama has these models installed, you may delete the `models` field in your Ollama config, let aichat use these builtin model defintions.

If your Ollama has different models installed, you may add models manually.

Remember, the embedding model must have the field `type: embedding` to distinguish it from the chat model.

There are too many models in the Ollama library, and new ones are added from time to time, making it impossible to automatically discover and detect models.

**Comment by jadbox** [comment]
@sigoden This worked! There's no documentation in the project about the "type: embedding" flag so I had no idea. I'd recommend something to the Readme under Rag that explains how to add an embedding model. Maybe also have the CLI indicate how to add an embedding model config if "No available embedding model" error triggers. :)

**Comment by sigoden** [comment]
While, we update [Configuration Guide](https://github.com/sigoden/aichat/wiki/Configuration-Guide). You can ask aichat-wiki.

![image](https://github.com/user-attachments/assets/ef8b0aef-d8a0-4488-9352-4ef4490c3f09)
