### ISSUE TITLE
Aichat is not making a complete function call.

### ISSUE THREAD

**Issue by euser1** [sigoden/aichat#837]
**Describe the bug**
On my machine I cannot make function calling work.
Am I missing something ?

**To Reproduce**
$ aichat --role %functions% what is the weather in Paris?
{"name": "get_current_weather", "parameters": {"location": "Paris"}}

I've had similar results with bash functions.
I did not succeed in  adding  tools/execute_py_code.py to avilable tools.

**Expected behavior**
Actually running the function get_current_weather(location="Paris").
Not getting the json dictionary.

**Configuration**

model                   ollama:llama3.1:8b-instruct-q8_0
max_output_tokens       -
temperature                   0.8
top_p                                -
dry_run                            false
stream                             true
save                                  true
keybindings                     emacs
wrap                                  no
wrap_code                       false
save_session                   -
compress_threshold      4000
function_calling             true
use_tools                         fs, web_search, search_arxiv, search_wikipedia, get_current_weather
rag_reranker_model      -
rag_top_k                       4
highlight                        true
light_theme                   false
config_file                      /home/user/.config/aichat/config.yaml
roles_dir                         /home/user/.config/aichat/roles
env_file                           /home/user/.config/aichat/.env
functions_dir                 /home/user/.config/aichat/functions
rags_dir                          /home/user/.config/aichat/rags
sessions_dir                  /home/user/.config/aichat/sessions
messages_file              /home/user/.config/aichat/messages.md

**Environment**
- os version:                 Debian 12.0
- aichat version:          0.21.1 
- terminal version:     Xterm 379-1

**Comment by sigoden** [comment]
See https://github.com/sigoden/aichat/wiki/FAQ#why-llms-dont-call-functions-even-though-they-support-function-calling

![image](https://github.com/user-attachments/assets/0d58435e-0c7c-4c8e-ad49-b4d897ac9e5a)
