### ISSUE TITLE
args in roles.yaml

### ISSUE THREAD

**Issue by luckman212** [sigoden/aichat#84]
_✨amazing project btw!✨_

I was trying to use the [`translator:` role example](https://github.com/sigoden/aichat/wiki/Role-Examples#translator), but I'm not quite understanding the [`ARGn` substitutions](https://github.com/sigoden/aichat/wiki/Role-Guide#role-args) and how they relate to the role name definition in `roles.yaml`.

#### Example **roles.yaml**:
```yaml
- name: translator:french
  prompt: >
    You will act as a translator between English and __ARG1__.
    Whenever you receive a prompt in either language, you will translate the text into the opposite language and provide the translated output as your response.
    Please ensure that your response contains only the translated text.
    No additional descriptions or explanations, No tags or comments to indicate language direction.

```

Must I define the name as `translator:french` or can I make it generic and use `translator:lang`? Or does it not matter? Is `french` just a _placeholder_? Or is it a _default_? If it's a default, I would expect to be able to write:

```
aichat -r translator Good afternoon
```

...without specifying a language parameter. But that doesn't work. You must type the full role spec. Am I using this incorrectly?

**Comment by sigoden** [comment]
see https://github.com/sigoden/aichat/wiki/Role-Guide#role-args

**Comment by luckman212** [comment]
@sigoden Thanks, yes I did see that, still not understanding what significance the named params in the roles.yaml have. To be more specific, what is the difference (if any?) between the following 2 role definitions:

```yaml
- name: convert:json:yaml
  prompt: convert __ARG1__ below to __ARG2__

- name: convert2:sdfgksjdfghksdfjghsdf:c434rhirfhs
  prompt: convert __ARG1__ below to __ARG2__
```

It appears to me that both of these could be used as

```
aichat -r convert:yaml:json
aichat -r convert2:yaml:json
```

?

**Comment by sigoden** [comment]
The `:french` suffix is a reminder that you must pass `language` as role arg, it can be `:frech` or `:chinese`.

The `:json:yaml` suffix is a reminer that you must pass `two format` as role args.  it can be `:toml:yaml` or `:json:ini`.

`:sdfgksjdfghksdfjghsdf:c434rhirfhs` desn't make sense, you won't know how to pass the role arg until you check roles.yaml.

**Comment by sigoden** [comment]
Give role arg a meaningful name for convenience.

**Comment by sigoden** [comment]
Without role arg, if you want to do following things:
- convert english to french
- convert english to chinese
- convert english to japenese

You need to create three roles seperately

```
- name: translator-french
  prompt: >
    You will act as a translator between English and french.
- name: translator-chinese
  prompt: >
    You will act as a translator between English and chinese.
- name: translator-japenese
  prompt: >
    You will act as a translator between English and japenese.
```
```
aichat -r translator-french hello world
aichat -r translator-chinese hello world
aichat -r translator-japenese hello world
```

But with role arg, you only need to create one role:
```
- name: translator:french
  prompt: >
    You will act as a translator between English and __ARG1__.
```
```
aichat -r translator:french hello world
aichat -r translator:chinese hello world
aichat -r translator:japenese hello world
```
It is a generic role now.

**Comment by sigoden** [comment]
If you want to use `aichat -r translate` without specifying `:french`. just add following role to `roles.yaml`

```
- name: translate
  prompt: >
    You will act as a translator between English and French.
```
