### ISSUE TITLE
RAG ignore/skip non-UTF-8 files

### ISSUE THREAD

**Issue by UreshiiPanda** [sigoden/aichat#841]
Currently trying out your tool, thanks for all the hard work you've put into this awesome project.

When inputting an entire directory for the "Add Documents" prompt of the RAG functionality, is there a way to tell aichat to ignore/skip files that are not UTF-8 compliant? I keep getting the following error anytime the downloader runs into a binary file within the directory:   

"Error: stream did not contain valid UTF-8
Aborted"

Or can I only feed in directories that have no non-UTF-8 files in them?

**Comment by sigoden** [comment]
Tip: using file extensions can effectively avoid these kinds of errors. 

```
Add documents: <path-to-dir>/.{md,txt}
```
