### ISSUE TITLE
BUG: old session deleted after saving to a new session (with a new name)

### ISSUE THREAD

**Issue by milanglacier** [sigoden/aichat#842]
# Bug describe

```bash

aichat -s

##### some conversation

.save session hello

```

```bash

aichat -s hello

 #### some conversion

.save session hello-2

```

Found that `hello.yaml` was deleted and `hello-2.yaml` was created.

# Correct behavior

A new session `hello-2.yaml` is created but `hello.yaml` should leave unchanged (this is the behavior before 1.21).

**Comment by sigoden** [comment]
This is expected behavior.
