### ISSUE TITLE
feature request: support prompt / context caching

### ISSUE THREAD

**Issue by rbutera** [sigoden/aichat#858]
This week Anthropic introduced prompt caching to Claude Sonnet, and Gemini has had context caching for a while. 

Adding this to `aichat` could help us reduce costs significantly for long conversations.

I'm sure this is already on your radar, @sigoden and other maintainers, but I thought it would be useful to create an issue just in case it wasn't.

Prompt caching increases the cost of the initial request by up to 90%, but in subsequent requests can reduce costs by up to 75% I believe.

**Comment by sigoden** [comment]
We are also researching it, but we suggest you not to have too many expectations.

### The cache implementation varies greatly across platforms.

- Claude requires adding the `cache_control` field in the `message`.
- Gemini/Moonshot needs to call the cache api first to obtain the `cache_id` before using it.
- Deepseek is enabled by default for all users, allowing them to benefit without needing to modify their code.

> The way of Deepseek is the future.

### Cache usage scenarios are quite limited.

First, we need to understand the characteristics of cache:

- The tokens of the text must be particularly large (> 2000) to necessitate cache.
- Cache has a ttl, usually only a few minutes.

In AIChat, the only suitable scenario for cache is: starting a session, uploading a large document, and chatting with it.

However, for this scenario, we also have a better solution: RAG.

**Comment by jimmycav** [comment]
Thanks, sorry I tried searching for it but couldn't find it.
