### ISSUE TITLE
The compatible platforms should include anthropic's Claude as it's an option in the config file itself

### ISSUE THREAD

**Issue by xdannyrobertsx** [sigoden/aichat#859]
https://github.com/sigoden/aichat/blob/8b3bd63c3c976ee1081a751b1eb5f0dab6763c72/Argcfile.sh#L81

**Comment by sigoden** [comment]
It is a list for OpenAI-compatible platforms, but Claude is not.

Cluade has its own separate command.

https://github.com/sigoden/aichat/blob/8b3bd63c3c976ee1081a751b1eb5f0dab6763c72/Argcfile.sh#L225
