### ISSUE TITLE
Multi-line input hotkey

### ISSUE THREAD

**Issue by martin-eder-zeiss** [sigoden/aichat#869]
Personally, I find the use of `:::` to start/end multiline input a bit more cumbersome than it needs to be.
It would be nice if there was an alternative way with a hotkey to achieve the same thing.

**Comment by sigoden** [comment]
![image](https://github.com/user-attachments/assets/fea19347-5085-42f8-9881-8bd758b0134e)

**Comment by martin-eder-zeiss** [comment]
The wiki is known, but I believe my point remains valid.

Regarding multi-line input, there is an inconsistency in the user interface:

- External Editor: Hotkey
- Single Newline: Hotkey
- Direct Input: Custom in-band control character sequence

I'm heavily using multi-line input to structure my prompts, in like every second or third prompt, and none of the provided options is really comfortable to use:

- External Editor: Could theoretically be used, but I prefer not to break the visual flow all the time. The editor is more suitable for situations where the structure of the prompt is still being developed and rearranged significantly.
- Single Newline: Not a meaningful option, as this would need to be pressed for every single line again and again.
- Direct Input: Requires pressing buttons 2x4 times instead of 2x2. It also often happens that I start typing and later realize that a multi-line prompt is actually required. In this case, I would have to manually go to the beginning of the line, add `:::` and then go back. A hotkey would really improve user-friendliness in this case.

**Comment by sigoden** [comment]
@martin-eder-zeiss

There's no other way for multi-line input. The reedline (used by aichat as a REPL framework) doesn't support it.
