### ISSUE TITLE
abacus.ai support

### ISSUE THREAD

**Issue by fn5** [sigoden/aichat#873]
### Please confirm whether the following requirements are met:

- [ x] Must have a REST/HTTP API.
- [ x] Must be publicly accessible. It cannot require application review or have regional restrictions. A beta version is acceptable.
- [ x] Must not act as an agent or proxy for other platforms.

### Please provide the following documents or links:

- API Documentation (required)
Overall documentation: https://abacus.ai/help/ref/overview
Response: https://abacus.ai/help/ref/predict/getChatResponse
(note curl example is provided halfway down the page)

Happy to provide additional information&access where I can. I have checked/explored and cannot find an openai /v1/chat/completions style endpoint.

**Comment by sigoden** [comment]
We will not support this client.

The chat API doesn't support streaming or function calling.
