### ISSUE TITLE
Functions calling from the  playground

### ISSUE THREAD

**Issue by fld-opensource** [sigoden/aichat#875]
is it supposed to work ? 

it works fine in the terminal but not in the playground

**Comment by sigoden** [comment]
We will not support this feature.

Many tools in `llm-functions` are CLI-based, which is incompatiable with WebUI.

![image](https://github.com/user-attachments/assets/609e8637-2945-4021-9ec6-46e16f3e1e29)

**Comment by fld-opensource** [comment]
real shame, would be good to be able generate graphviz image for instance from a chat ...
