### ISSUE TITLE
[Feature Request] Enhance conversation repl

### ISSUE THREAD

**Issue by sigoden** [sigoden/aichat#88]
GPT-3.5 supports up to 4096 tokens, and it is not very likely to have a long conversatio, so there is no need to design a feature-rich conversation repl.

But gpt-4 supports up to 8k tokens, gpt-4-32k supports up to 32k tokens, we can do long conversation. It's necesarry to enhance conversation repl.

### `.conversation revert [num]` - revert current conversation messages.

This give user the ability to edit previous lines, thus branching the conversation in a new direction. This is useful when models get caught in infinite loops, or local optima. 

The `num` parameter specify how many messages to revert. If we omit `num` parameter, Aichat will display a list of current messages, the user can choose where to revert.

### `.conversation delete` - delete a saved conversation

AIChat will display a multi-select list for the user to select the conversation to delete

### `.conversation use` - reuse a saved conversation

AIChat will display a list for the user to select the conversation to load to

## Design details

1. The conversation automaticlly saved to `$CONFIG_DIR/conversations/<datetime>-<first-message-truncated>.json`
2. The conversation is not bound to a specifiy model.
3. Allow to run `.model` in the middle of conversation.
4. Not allow to run `.role` or `.prompt` in the middle of conversation.

**Welcome to provide suggestions for the design of the conversation repl.**

**Comment by alxpettit** [comment]
`.conversation` is a bit long to type every time. Shortening it to `.conv` would be helpful -- perhaps as an optional abbreviation?

**Comment by sigoden** [comment]
aichat's readline supports tab completion, type `.conv` then type tab, you get `.conversation`. there is no need to use abbreviation.

@alxpettit

**Comment by asb** [comment]
One related request/suggestion I have would be to make it easy to convert a one-off request into a conversation. Often I expect a one-off response to be fine, but upon getting it back I realise I have a follow-up question or refinement, and this may be better handled through a conversation rather than editing the prompt.

As a strawman, how about `.conversation last` to start a conversation that incorporates the last question and answer.
