### ISSUE TITLE
"clear screen" feature in repl mode

### ISSUE THREAD

**Issue by domvo** [sigoden/aichat#883]
**Is your feature request related to a problem? Please describe.**
Similar to the POSIX `clear` command I would love to have a `.clear` command for the repl mode, regardless of whether I'm in a session or not.

**Describe the solution you'd like**
After the `.clear` command has been executed, the terminal should be clean and just show the input prompt at the top.

Before:
![image](https://github.com/user-attachments/assets/90992bc4-a028-44fc-80fb-5c14d5e7193f)

After:
![Screenshot 2024-09-24 at 14 15 52](https://github.com/user-attachments/assets/8aa1305c-0a1b-4b02-a204-c861feafd066)

**Comment by sigoden** [comment]
use `ctrl + l`
