### ISSUE TITLE
openai o1 model setting

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#885]
Hi,

The openai o1 models doesn't seem to support a temperature different than one and the stream mode .
Thus, would it be possible to set a per model setting, in order to automatically set a  temperature, and **stream=false** when switching to it (like o1-mini for example) ?

**Comment by sigoden** [comment]
o1 is the only one among all models that doesn't support streaming. This is not a common situation, and we will not introduce a `stream` model configuration.

**Comment by InfImpDrive** [comment]
This may need a re-evaluation if a lot of models start using async CoT

o1 is now available on Tier 4 (250 lifetime spend; can be just a 250 deposit for new users) and did some tests using other tools.

It's absurdly fantastic for coding questions that requires reasoning such as these questions:

> Take a look at [[file1.js]], [[file2.js]] and [[file3.js]]. I need you to generate a new suggested [[baseclass.js]] as a refactored base class. Output only the baseclass.js code.

It works fantastically when I tested this in the Playground.

It also has a 128K input context window and 64K output, so it can output large modules.  You'd use a command line to cat in a few modules (with separators in between like  [[[start of file1.js]]] separating the concatenated files into it.  And outputs much superior code for certain kinds of requests.

**Comment by sigoden** [comment]
Feel free to use o1 with `--no-stream/-S` or `.set stream false`.


AIChat does not automatically set stream=false for special models (like openai:o1*), which does not mean it does not support non-streaming.

**Comment by InfImpDrive** [comment]
Oh!  I was unaware of this setting.  Thanks.
