### ISSUE TITLE
Ability to specify --interactive mode (don't exit immediately) when I specify files with -f

### ISSUE THREAD

**Issue by InfImpDrive** [sigoden/aichat#891]
### Describe the solution you'd like

I would like an --interactive command line option or similar for situations where I specify files on command line. 

Purpose: Stay in chat even when you specify -f files at command line.

Why?  Stays in chat allows iteration to self-improve the current chat request.  Newer language models are now becoming much better at multiple-file handling (Example: o1), but not always zero-shot.  Some of the models now appear useful at answering questions even for entire projects/folders (e.g. 20 files).  Iterating with CoT models actually rapidly improves the output in fewer turns than non-CoT models.

### Describe alternatives you've considered

There's none similar 

### Additional context

To add --interactive to continue chatting after specifying files, would allow conversations about many files:

> aichat -S -model openai:o1-mini -f file1.js -f file2.js -f file3.js --interactive "Heres my custom advanced coding request bla bla bla"

or

> aichat -S -model openai:o1-mini -f test1.html -f test2.html -f test3.html -f test.css -f test.js --interactive "Custom advanced modification request here more suited for a CoT model"

or

> aichat -S -model openai:o1-mini -f test.html -f test2.html -f test3.html -f test.css -f test.js --interactive "Custom obscure-debugging request here more suitable for a CoT model"

And simialr.

And then it outputs the first response and drops me into the interactive chat to iterate back-and-fourth (requesting changes).  I did tests in playground API and it usually requires 2-shot and 3-shot before I trusted the quality of the code to test it, but that is massively better than the frustrations I've had with other models (Claude, GPT-4o, etc).  

It's easy to generate custom aichat commands from a script e.g. (asky-chattty.sh *.html "question-here") which can autoformat the long -f command line necessary for a wildcard mask, and automatically select specific models, so that isn't aichat's responsibility.  But aichat's limitations prevent me from iterating back-and-fourth requests on multiple files.

aichat already lets me specify multiple files at command line, unlike a lot of other utilities, which makes it easy to chat about multiple files without copying and pasting.  Since o1-mini API is fairly expensive, the ability to stay in chat to iterate back and fourth is useful -- as o1 usually requires only 2 or 3 cycles of chat to do what many other models failed after 10-20 chat iterations.  o1 is now able to write code much more reliably since it actually self-repeatedly proofreads itself, and often has only 1/10th the coding error rate (e.g. 500 line code as reliable as 50 line code skeletons).  

Therefore, an --interactive would be a big moneysaver for a lot of aichat fans, consequently.  

So my pressure is very high to figure out a way to effectively chat about multiple files to o1 in an interactive manner, as well as other AI providers' upcoming CoT models.

**TIP: As of September 24th, the first major CoT model, o1 now only requires Tier 4 which activated immediately once I deposited my 250th dollar (50 dollars more if you already spent 200). Much easier than Tier 5!  For other readers, the author of openai helpfully told me that o1 requires the -S command line option to work**

**Comment by sigoden** [comment]
We will not support this features. Please use `.file` instead. `--file` for CLI, `.file` for REPL.

**Comment by InfImpDrive** [comment]
> We will not support this features. Please use `.file` instead. `--file` for CLI, `.file` for REPL.

Oh?  Do you mean I can have an external script generate the .file list automatically, and then let the user continue chat?  

I could not find a way to automate the initial multi-.file at entry into chat.

**Comment by InfImpDrive** [comment]
UPDATE! Solution is to use --session NAME --save-session
Then enter REPL (interactive) via a second call to aichat.

Example

```
# Initial query about bunch of files
aichat --session ABCDEF --save-session -f file1.txt -f file2.txt -f file3.txt "Custom request about these files"
# Enter REPL mode
aichat --session ABCDEF 
```

So problem solved (in a roundabout way).

Posting this info for other users to figure out that this is, of course, indeed possible.
