### ISSUE TITLE
Disable tab completion when in block-edit (:::) mode 

### ISSUE THREAD

**Issue by tkanarsky** [sigoden/aichat#892]
**Is your feature request related to a problem? Please describe.**
Right now, when you are editing a reply in block mode by surrounding it with `:::`, the <tab> key is still bound to auto-complete. This means I can't indent text, e.g. to ask questions with accompanying code.

**Describe the solution you'd like**
Make <tab> key insert a tab character or N number of spaces (potentially configurable) when within a block reply. 

Let me know if this sounds feasible! I see that your REPL implementation handles multi-line support (via regex) downstream of autocomplete, so inverting that dependency structure may be challenging.

Don't worry about it though, if it's going to require too much work.

**Comment by sigoden** [comment]
We will not support this feature. 

Most people agree that tab completions are needed even when in block-edit (:::) mode. On the contrary, using tab for indentation is less common.

If you want to input the code (which may require tabs), it is recommended to use an external editor (ctrl+o).

**Comment by tkanarsky** [comment]
Could you elaborate on what you mean by ctrl+o?On Oct 1, 2024 3:41 PM, sigoden ***@***.***> wrote:
We will not support this feature.
Most people agree that tab completions are needed even when in block-edit (:::) mode. On the contrary, using tab for indentation is less common.
If you want to input the code (which may require tabs), it is recommended to use an external editor (ctrl+o).

**Comment by sigoden** [comment]
![image](https://github.com/user-attachments/assets/c1503155-f847-446f-8902-87759c13d399)
