### ISSUE TITLE
Bedrock Cross-region Inference (covers Llama 3.2 and Claude)

### ISSUE THREAD

**Issue by fn5** [sigoden/aichat#893]
**Is your feature request related to a problem? Please describe.**

Amazon Bedrock is moving more of their API to a "cross-region inference" system. They have soft launched Claude models there (existing endpoints still work), but **all Llama 3.2 models are cross-region inference only.**
![image](https://github.com/user-attachments/assets/08f853d7-c49b-4832-897b-88decb8edca7)

If you call `.model bedrock:meta.llama3-2-3b-instruct-v1:0` there will be the following error:

> Error: Failed to call chat-completions api
> 
> Caused by:
>     The provided model doesn't support on-demand throughput.

I am able to call the model using manual items:
.model bedrock:us.meta.llama3-2-1b-instruct-v1:0
.model bedrock:us.meta.llama3-2-3b-instruct-v1:0
.model bedrock:us.meta.llama3-2-11b-instruct-v1:0
.model bedrock:us.meta.llama3-2-90b-instruct-v1:0
and they do work.

Cyncially I think they may move the Claude models to this as well - they have soft launched it, but existing per-region IDs still work.
![image](https://github.com/user-attachments/assets/ae7a4991-074a-493d-9db8-6fd5ca39224b)

**Describe the solution you'd like**

Correct management of cross-region inference only models.

**Describe alternatives you've considered**

Specifying all relevant US regions, however this does not work to show either.

**Additional context**

https://aws.amazon.com/blogs/machine-learning/getting-started-with-cross-region-inference-in-amazon-bedrock/
https://docs.aws.amazon.com/bedrock/latest/userguide/cross-region-inference-support.html

**Comment by fn5** [comment]
Also, I use the following in my models.yaml at the moment:

```
    - name: us.meta.llama3-2-1b-instruct-v1:0
      max_input_tokens: 128000
      max_output_tokens: 2048
      input_price: 0.10
      output_price: 0.10

    - name: us.meta.llama3-2-3b-instruct-v1:0
      max_input_tokens: 128000
      max_output_tokens: 2048
      input_price: 0.15
      output_price: 0.15

    - name: us.meta.llama3-2-11b-instruct-v1:0
      max_input_tokens: 128000
      max_output_tokens: 2048
      input_price: 0.35
      output_price: 0.35

    - name: us.meta.llama3-2-11b-instruct-v1:0
      max_input_tokens: 128000
      max_output_tokens: 2048
      input_price: 2.00
      output_price: 2.00

**Comment by sigoden** [comment]
Currently, we add the `us.` prefix to each LLM that only supports cross-region inference.

https://github.com/sigoden/aichat/blob/419c626485ca045adfe6d99e5ed34ebb51524ced/models.yaml#L521-L540

For users who prefer `eu.`, please manually configure the client's models field.
