### ISSUE TITLE
How to install on Raspberry Pi without having to install the Rust toolchain?

### ISSUE THREAD

**Issue by Boscop** [sigoden/aichat#894]
Thanks for making such a useful tool. I'm gonna try this, since [shell-GPT](https://github.com/TheR1D/shell_gpt) doesn't support Claude.

Can you please add instructions to the readme for how to install on Raspberry Pi without having to install the Rust toolchain? 🙂

**Comment by sigoden** [comment]
The CPU architecture of the latest Raspberry Pi is `aarch64`, so you can try to install aichat via
https://github.com/sigoden/aichat/releases/download/v0.22.0/aichat-v0.22.0-aarch64-unknown-linux-musl.tar.gz

> Have  not been tested. If it fails, you must build the AIchat yourself with rust toolchain.

**Comment by Boscop** [comment]
@sigoden My Raspberry Pi is `armv7l` (`uname -m`). 
Can I use aichat on there? 🙂
