### ISSUE TITLE
Please add keyboard shortcuts to select between `[E]xecute`, `[R]evise`, `[D]escribe`, and `[C]ancel`

### ISSUE THREAD

**Issue by Boscop** [sigoden/aichat#895]
Please add keyboard shortcuts to select between `[E]xecute`, `[R]evise`, `[D]escribe`, and `[C]ancel`.
It would be faster to press one key than 3 (two arrows + Enter in the worst case):

Example:
<img width="330" alt="{9033861D-51B4-4325-9FA7-32A5014BCFBA}" src="https://github.com/user-attachments/assets/c417dfb5-8a73-4cad-b144-32c9ae48ac1b">

To select `Explain`, it takes 3 key presses, which it wouldn't have to: With keyboard shortcuts, it would be just 1 keypress in any case.

To disambiguate the `e` keypress, I suggest using it for `Execute`, and renaming `Explain` to `Describe`.

Could you please add this? 🙂
Thanks 🙏

**Comment by sigoden** [comment]
Sometimes I also feel that the older version is better.
https://github.com/sigoden/aichat/blob/a3f63a5e04cf56e4cc39b32bb33a3506d4366249/src/main.rs#L170-L180

We will revert to the old version.
