### ISSUE TITLE
Don't show backtrace on Ctrl-C

### ISSUE THREAD

**Issue by Boscop** [sigoden/aichat#896]
Just a cosmetic UX thing:

<img width="327" alt="{2AB88BE0-34E4-45BC-9746-F346FF5407E5}" src="https://github.com/user-attachments/assets/abd2d2d5-c3b9-4327-9385-fff9fb67dcb4">

I suggest not showing a backtrace on Ctrl-C :)

Btw, I installed aichat via scoop on Windows.
And while I do have `RUST_BACKTRACE=full` in my global env vars, it shouldn't affect any installed release binaries written in Rust, because Rust is essentially an implementation detail of them, and this env var is for when developing in Rust, not for affecting end user application :)

Could you maybe switch to using a different env var, like `AICHAT_BACKTRACE`? :)
I've seen some Rust applications follow this convention.

But yeah, it's a minor thing..

**Comment by sigoden** [comment]
We don’t think there’s any problem with this. This is the expected effect of `RUST_BACKTRACE`..
