### ISSUE TITLE
A visual indication of Vi/emacs mode

### ISSUE THREAD

**Issue by kqvanity** [sigoden/aichat#897]
**Is your feature request related to a problem? Please describe.**

Whenever I turn Vi mode on, I'm always in a loss of which mode I'm at!

**Describe the solution you'd like**

The shell prompt change accordingly instead of static arrow >

**Comment by sigoden** [comment]
We will not support this feature.
See https://github.com/sigoden/aichat/wiki/Custom-REPL-Prompt for customizing the REPL prompt.

**Comment by kqvanity** [comment]
why not?

**Comment by sigoden** [comment]
In AIChat, the keybings must be one of `emacs` and `vi`. There is no support for dynamic switching. What's the point of having a visual indication of keybindings mode.

If you don't know the current keybindings, there are three ways to find them:
- type `ESC`, then type `l`, if the cursor move left, it is `vi`.
- run `.info` REPL command, there is a field `keybindings`.
- modify REPL prompt by youself.

**Comment by kqvanity** [comment]
By mode I mean insert or normal mode!

**Comment by kqvanity** [comment]
sorry my bad. I meant Vi's very own normal/insert model

**Comment by sigoden** [comment]
Is it necessary? Even a CLI as popular as Python doesn't provide a visual indication of Vi's insert/normal mode.

**Comment by kqvanity** [comment]
I just think it makes the VI mode a lot more usable
