### ISSUE TITLE
DeepSeek Coder not working? (Termux)

### ISSUE THREAD

**Issue by LucasMatuszewski** [sigoden/aichat#899]
**Describe the bug**

I try to use DeepSeek Coder with AIChat and Termux on Android (I will check if it works on Ubuntu).
But it looks it's always Chat model, not Code model. In DeepSeek Dashboard I only see Chat tokens, for Code I see zero. Model when asked also claims to be Chat, not Code, but I don't trust him ;)

In model.toml file in this repo I also only see Chat model. Can we add Code 2.5?

I also can't find information about version, but I guess if it's not specified it's always using the latest version, so v2.5?

**To Reproduce**

On initial configuration I choose DeepSeak.

When I list models I see both chat and Coder models.
```
~ $ aichat --list-models                                   deepseek:deepseek-chat                                     deepseek:deepseek-coder
```

I use model with command:
`~ $ aichat -m deepseek:deepseek-coder`

I talk to the model, generate tokens. You may aks about it's version and cutoff. But rather check in DS Dashboard ;)

**Expected behavior**
I just want to be able to use DeepSeek Coder when I select this model with -m flag. Even if chat is set as default.

**Configuration**

```
model                   deepseek:deepseek-chat
max_output_tokens       -
temperature             -
top_p                   -                                  dry_run                 false                              stream                  true                               save                    false                              keybindings             emacs                              wrap                    no                                 wrap_code               false                              function_calling        true                               use_tools               -                                  agent_prelude           -                                  save_session            -                                  compress_threshold      4000                               rag_reranker_model      -                                  rag_top_k               4                                  highlight               true                               light_theme             false                              env_file                /data/data/com.termux/files/home/.config/aichat/.env                                          config_file             /data/data/com.termux/files/home/.config/aichat/config.yaml                                   roles_dir               /data/data/com.termux/files/home/.config/aichat/roles                                         sessions_dir            /data/data/com.termux/files/home/.config/aichat/sessions                                      rags_dir                /data/data/com.termux/files/home/.config/aichat/rags                                          functions_dir           /data/data/com.termux/files/home/.config/aichat/functions                                     messages_file           /data/data/com.termux/files/home/.config/aichat/messages.md
```

**Environment (please complete the following information):**
- os version: Android 14
- aichat version: 0.22.0
- terminal version: Termux 118

**Comment by sigoden** [comment]
There is no longer a `deepseek:deepseek-coder`.

![image](https://github.com/user-attachments/assets/40218f3f-456c-4013-891c-bbe5b0356835)

see https://platform.deepseek.com/api-docs/

**Comment by LucasMatuszewski** [comment]
> There is no longer a `deepseek:deepseek-coder`.

Ahh, my bad... sorry 😂 
I misunderstood their latest documentation. THX!
