### ISSUE TITLE
[Bug] Unknown role when do role select on macos

### ISSUE THREAD

**Issue by weiliu1031** [sigoden/aichat#90]
![image](https://user-images.githubusercontent.com/108661493/226795836-d39536ae-cd8c-45bc-a04d-d711ca887448.png)

need help

**Comment by sigoden** [comment]
After editing `$CONFIG_DIR/roles.yaml`, you need to exit aichat and re-enter to make the roles take effect.

**Comment by weiliu1031** [comment]
> After editing `$CONFIG_DIR/roles.yaml`, you need to exit aichat and re-enter to make the roles take effect.

already tried exit and re-enter, like this 
![image](https://user-images.githubusercontent.com/108661493/226796973-f83a895c-7ca5-49be-b5bb-8c8247b97b12.png)

**Comment by sigoden** [comment]
Does `roles.yaml` really exist? Try `cat "/Users/zilliz/Library/Application Support/aichat/roles.yaml"`. You need quotes for the path as it contains space.

**Comment by weiliu1031** [comment]
> Does `roles.yaml` really exist? Try `cat "/Users/zilliz/Library/Application Support/aichat/roles.yaml"`. You need quotes for the path as it contains space.

you're right, something wrong happened on  config path.

problem solved and thanks
