### ISSUE TITLE
Auto-split long message

### ISSUE THREAD

**Issue by t18n** [sigoden/aichat#904]
**Describe the solution you'd like**
I would like to request a feature that can automatically split a long message into smaller chunks (based on config option or `max_input_token` value and feed it to the model. I understand that RAG can be used for this but sometimes, I just want a one time paste of a long article, video transcript, code file and chat with it.

**Describe alternatives you've considered**
https://chatgpt-prompt-splitter.jjdiaz.dev/

**Comment by sigoden** [comment]
The `max_input_token` refers to how many tokens the API can handle in a request; splitting them has no significance.

It is precisely because the model can only process a limited number of tokens that an alternative such as RAG is born.

The only solution for long documents is RAG.
