### ISSUE TITLE
Save response into a session without loading the entire session context

### ISSUE THREAD

**Issue by kqvanity** [sigoden/aichat#906]
**Is your feature request related to a problem? Please describe.**

When I execute aichat in the non-interactive mode, along with roles, I sometimes would love to cache/save the response. When I say 'cache' i mean that I'd want to just save it, without 'sending' context of the selected session, else, I'd get the following error message
```bash
... | aichat --role summarize --session articles --save-session
```

```
Error: Failed to call chat-completions api

Caused by:
    Invalid response data: {"error":{"code":"error","message":{"code":"message_length_exceeds_limit","message":"The message you submitted was too long, please reload the conversation and submit something shorter."},"param":null,"type":"413 Request Entity Too Large"}} (status: 413)

```

**Describe the solution you'd like**

Maybe a way to cache the response in a certain session, without loading up the entire previous session.

**Describe alternatives you've considered**

**Additional context**

**Comment by sigoden** [comment]
We don't know what you're talking about.

`message_length_exceeds_limit` means that the input data is too large for the LLM to handle.

The reason it's called a session is that it turns all of its messages into context.

**Comment by kqvanity** [comment]
> The reason it's called a session is that it turns all of its messages into context.

wanted to persist some of the answers in the old session for future reference. Using aichat non-interactively, I don't need the context (not a two-way conversation), but only to append the response.

**Comment by sigoden** [comment]
The session yaml file is also used for persistence.

If you don't need the context, you don't need a session.  The messages.md file is for storing the non-session chat history.

**Comment by kqvanity** [comment]
> The messages.md file is for storing the non-session chat history.

That's what I'm looking, but with more control on where to save it (instead of dumping all of them in one bucket). Basically session's concepts but without actually providing context when sending additional prompts. 
I do need context in certain conversations/sessions, however most of the time, I'm just asking disparate questions. Where the following error is a common encounter

```bash
Error: Failed to call chat-completions api

Caused by:
    Invalid response data: {"error":{"code":"error","message":{"code":"message_length_exceeds_limit","message":"The message you submitted was too long, please reload the conversation and submit something shorter."},"param":null,"type":"413 Request Entity Too Large"}} (status: 413)

```

If you could provide a command to turn off context awareness, that'd be ideal.

**Comment by sigoden** [comment]
There is a `.save session` to save the current session to file.
There is alos a `.clear messages` to clear the current messages in the session.
You can flexibly use these two commands to meet your needs.

**Comment by kqvanity** [comment]
> You can flexibly use these two commands to meet your needs.

but I'll be basically overriding the session everytime

**Comment by sigoden** [comment]
`.save session <new-name>` to avoid overwriting.

**Comment by kqvanity** [comment]
It's unrealistic to create a whole new session for each new message.

Am I the only one who've had this problem?

**Comment by kqvanity** [comment]
> I haven't agreed to anything

I'm laying out the possible options.

>  AICHAT_MESSAGES_FILE=chat1.md aichat hi

I mostly use it in the interactive mode. I wouldn't have asked for fuzzy searching sessions/commands otherwise.

I've explained the reasons why temporarily disabling the context would be helpful
- conflicting AI models in the same session
- Token cap

The possible features I was looking for are: fuzzy searching commands/arguments (have the side effect of making session sprawl more manageable), optional context (with the sane conventional defaults remain the same).

If they made more sense in the future, or had the time to implement them, please mention the release in this issue if possible.

**Comment by kqvanity** [comment]
#### Expanding on my last argument with other challenges that arose since then

- After using the fragmented session approach `topicName-1,2,3,4,5`, it really went out of hand. Unless I use fzf in CLI mode, i keep tabbing my way through the sessions. However If I was using a single session (with optional context), I can easily <C-o> to search Q/A using my favorite editor, or even `.info session` then search the entire session with the terminal.
- I have a workflow of raw input + aichat + certain role = LLM response. I'd ideally want to leverage rag by pointing that session document as the RAG source document.               
- Other web-based AI chat platforms support sessions by other means e.g., session ID (no context whatsoever. You only send new queries & session ID). (I use adapters to use them locally)

 #### Alternative solutions I've tried
- Setting custom max_threshold to ~1 then instruct the summary prompt to maybe only return a single word/headline or so, but it's definitely breaks regular sessions where I do need context. Still a dirty hack.
 - Using a wrapper agent/shell that would prompt response, then save the original input & response in a mirror text file as a RAG source, but I ended up with a sprawl of duplicate text files eventually.
 - Using a single messages.md, but I'd sometimes want to look up the sources in the RAG response

I do use the session functionality to have a conversation with context, but a per-session configuration option to enable/disable context would be really convenient. and that's my biggest gripe. That it's not optional.
