### ISSUE TITLE
Commandline and REPL to automatically delete session

### ISSUE THREAD

**Issue by InfImpDrive** [sigoden/aichat#909]
**Describe the solution you'd like**

There is already ways to create a session both by command line and via REPL:

`aichat --session TEST_SESSION --save-session`

However, there seems to be no way to do targeted deletion of named sessions.  
Could be any of:

`aichat --session TEST_SESSION --delete-session`
or 
`aichat --delete TEST_SESSION`
or 
other similar (And equivalent REPL that automatically deletes a known specific named session).

**Additional context**

This is useful for scripts that create a session automatically.  In many cases, it is preferable to clear the existing named session (from a previous script run) before beginning a new session that is carried across a series of aichat commands.

**Comment by sigoden** [comment]
It is recommended to locate the sessions_dir and then delete the session YAML files to remove the sessions.

Alternatively, create a completely new temp directory each time as the sessions_dir.
```
AICHAT_SESSIONS_DIR=/tmp/sessions01 aichat 
```

**Comment by sigoden** [comment]
This paradigm applies to roles, sessions, rags, and agents.

**Comment by sigoden** [comment]
Since #922 merged, you can use `--empty-session` instead of deleting the session.
