### ISSUE TITLE
Basic (TTY) unthemed mode for parallel logging + interactive (tee, screen, etc)

### ISSUE THREAD

**Issue by InfImpDrive** [sigoden/aichat#910]
### **Is your feature request related to a problem? Please describe.**

There are some (mostly) successfully-interactive ways to log aichat output while in interactive mode:

1. `aichat | tee logfile.md`

And

2. `screen -L aichat`

Method 1 correctly disables theme temporarily, but has messy-terminal problem of using LF's instead of CRLF's.
Method 2 logs to "screenlog.0" (works) but in the log doesn't disable the theme color escape codes

Use cases: I was using a realtime autorefreshing Markdown viewer in a side window while I'm interacting with aichat.  There's many markdown viewers (from 'mdless' to 'md2html' that supports streaming with auto-refreshing HTML viewer). Alot of LLMs output Markdown. Also, Markdown .md files viewed within VSCode are autorefreshing too whenever the file changes, so great for .md logfiles. Also, many Markdown viewers also insert convenient "Copy" links for codeblock snippets (commands, code, config files, etc).  

The problem is several of these Markdown viewers are incompatible with color escape codes embedded inside Markdown. For simplicity, they don't have to be all fully gone, just gone from the chat outputs / responses.

I have also tried "export TERM=dumb" but that doesn't disable the color VT codes that interferes with a live markdown viewer running in another window.

### **Describe the solution you'd like**

A better way to interact with aichat, while simultaneously logging chat output to a file, whether by one of:

1. Fixing method 1 by allowing CRLF mode instead of LFs; or
2. Fixing method 2 by providing a theme-off mode in addition to dark/light themes; or
3. Honoring environment variable TERM=dumb to disable VT colors (which would make method 2 work);
4. Or other recommended solution.

**Comment by sigoden** [comment]
1. AIChat just pipe out everything the LLM generated. Why is there a dispute between CRLF and LR?
2. AIChat supports NO_COLOR and AICHAT_HIGHLIGHT for no color
3. AIChat does not support TERM for color controls. The TERM does not have any standards, and its value is quite arbitrary.

**Comment by InfImpDrive** [comment]
I will use suggestion 2 to solve my problem in a (roundabout) way.

That being said, just to clarify about #1:

> 1. AIChat just pipe out everything the LLM generated. Why is there a dispute between CRLF and LR?

When you pipe aichat into tee, it goes into this TTY mode that becomes ugly for interactive mode.

```
~$ aichat | tee testlog.md
Welcome to aichat 0.22.0
                        Type ".help" for additional help.

> .help
.help                    Show this help message
                                               .info                    View system info
                                                                                        .model                   Change the current LLM
   .prompt                  Create a temporary role using a prompt
                                                                  .role                    Create or switch to a specific role
                                                                                                                              .info role               View role info
                                 .edit role               Edit the current role
                                                                               .save role               Save the current role to file
 .exit role               Leave the role
                                        .session                 Begin a session
                                                                                .clear messages          Erase messages in the current session
          .info session            View session info
                                                    .edit session            Edit the current session
                                                                                                     .save session            Save the current session to file

```

**Comment by sigoden** [comment]
`aichat | ...` is a bug. It should throw error.

**Comment by InfImpDrive** [comment]
tee is a special command that tries to emulate a two-way terminal

__

Solution 2 worked! 
For others who google and find this, this is the usage:

'export NO_COLOR=true
aichat'

Then markdown logged by a specific console/terminal native logging feature (e.g. screen) is interpretable correctly by markdown viewer.

**Comment by dezza** [comment]
> Solution 2 worked! For others who google and find this, this is the usage:
> export NO_COLOR=true

```sh
NO_COLOR=1 aichat # ... also works
```
