### ISSUE TITLE
Subcommand to get answers from the web

### ISSUE THREAD

**Issue by Boscop** [sigoden/aichat#912]
It would be great if you could add web search to `aichat` so that users can query the web from the command line and get a synthesized answer (not just list of search results) 🙂

E.g. via 
- https://crates.io/crates/perplexity
- https://crates.io/crates/tavily
- (later also Perplexica: https://github.com/ItzCrazyKns/Perplexica/issues/141 )

**Comment by sigoden** [comment]
AIChat support web search via llm-functions. Some LLMs natively support web search.

**Comment by Boscop** [comment]
@sigoden Which LLMs support web search? I don't have ChatGPT Plus..

**Comment by sigoden** [comment]
LLMs with web search:

perplexity:*-online
ernie:*

LLMs with web search but need patch body:
vertexai:gemini-*
corhere:*
