### ISSUE TITLE
NIXOS / Google IDX - AIChat v9 - update to v22?

### ISSUE THREAD

**Issue by LucasMatuszewski** [sigoden/aichat#925]
Hey,
first of all thanks for the great tool!
I use `aichat -e` all the time, better than `gh copilot` CLI!

But I've been using Google IDX Project recently, virtual env with VSCode based on NIXOS.

The official package available is v9, which doesn't have `-e` execute command yet.
Edit: it also doesn't know the `deepseek` model yet ;)

The environment is ephemeral so I don't know how to install AIChat 22 permanently myself.
Probably build from source and add to PATH? Homebrew is not available on NIXOS, so I would also have to build it myself.

Any chance to just update the version on NIXOS?
Or maybe I should write a request on their Repo? ;)

**Comment by sigoden** [comment]
Maybe you should use unstable Nixpkgs channel. It provides latest aichat.

![image](https://github.com/user-attachments/assets/ddb93596-b932-4767-b620-2858cb4d572a)

**Comment by LucasMatuszewski** [comment]
ahh, thanks! Sorry, I should check...
I see `--execute` was added in v0.13 so probably `nixpkgs stable 24.05` will be good enough for me. Thanks again!
