### ISSUE TITLE
Provide a setting to display results from function calling transparently

### ISSUE THREAD

**Issue by einarpersson** [sigoden/aichat#932]
**Is your feature request related to a problem? Please describe.**
I use function calling a lot. It often seems as if the assistant assumes that I have also seen the result that the assistant has seen, but that is not the case. The assistant digests the result of the function call, and uses the result to improve its answer to me.

In some situations this is completely fine and allows for a less noise chat experience.

But at other times you definitely want to "see what the assistant sees", so that you can better make a judgment for yourself about things. And sometimes it is just unnecessary to let the assistant "repeat the output", the output of the function call may just as readable _(or more readable)_ than the assistants summary.

**Describe the solution you'd like**
I would like a setting that allows for the result of a function call to be inlined in the chat. It could have the same gray color as the function call so that it is fairly discrete.

I suggest that this is configurable on a global level (`config.yaml`), on a per role level (`<role>.md`)and in a session using the `.set` command. Then it can be toggled on or off during sessions eg. for debugging or when I "know" what kind of output to expect. If I use this setting in a role, I could instruct it to not repeat the output of any function calls as long as they are on a human readable form.

### Another idea
_**Now that I come to think about it**_, I wonder if this setting should not just be a boolean but rather be an enum. Because there is also a third variant: you may want to see the result but it is NOT relevant to give the result to the assistant.

_Concrete example: Fetching a news article from an API_

I can see at least three user stories:
1. I want the assistant to fetch an article and tell me the highlights (do not show the underlying data resulting from the tool)
2. I want to discuss the article with the assistant. Then I would prefer to read it in its original form, but I also want the assistant to digest it so that I can ask follow up question
3. I only want to use the assistant as an api-helper, i.e. give me the article and show it to me. You do not have to mind the contents and waste your precious tokens on that. 

```
tool_output: 'show, digest, show_and_digest'
```

The actual naming is not important. But I really think that the three use cases presented above all are completely valid and useful. If this feature request is not accepted I'd love to get some insight into how I can fulfill the three user stories described above.

**Describe alternatives you've considered**
Modifying each relevant tool so that they themselves also print the output to user as well as to the assistant LLM. Or, adding an optional function parameter that control this output behaviour.

**Comment by sigoden** [comment]
We agree that displaying results from certain function calls is a reasonable requirement, but we do not agree with your proposal.

### Reasons

1. Function calling results always need to be submitted to LLM; this is determined by the design of function calling and cannot be changed. 

2. For some function calls, displaying their results is indeed valuable, but this does not apply to all function calls. We don't need a global switch; instead, we need a solution that gives us fine-grained control over each function call.

**Comment by sigoden** [comment]
Our proposal sigoden/llm-functions#110

**Comment by einarpersson** [comment]
Ok, great that it is on your radar.

As I understand it, your proposal would always imply that the LLM _always_ "digests" the result of the function call. I understand that there may be good reasons for that. 

I suppose that even in my suggested scenario (_show this_long_article to the user but do not digest it yourself_) some returning result is necessary to the LLM, such as a success message or something. If I am not mistaken, I could always design the tool itself to only **_print_** the stuff I want to display and **_return_** a confirmation message to the LLM (and make this behaviour/side-effect clear from the tool description).

**Comment by sigoden** [comment]
@einarpersson You're right.

**Comment by sigoden** [comment]
solved by sigoden/llm-functions#111
