### ISSUE TITLE
Configuration File as an Argument

### ISSUE THREAD

**Issue by ifokeev** [sigoden/aichat#937]
**Is your feature request related to a problem? Please describe.**
I'd like to run multiple AIchat instances with different configurations; these could be different agents.

**Describe the solution you'd like**
It would be beneficial to provide an option to pass the configuration as either a string or a file, since currently, the configuration path is hardcoded.

Thank you in advance.

**Comment by sigoden** [comment]
Please use `AICHAT_CONFIG_FILE` or `AICHAT_CONFIG_DIR`.

Compared to `AICHAT_CONFIG_FILE`, the `AICHAT_CONFIG_DIR` allows for a fully isolated AIchAT instance.
```
AICHAT_CONFIG_DIR=dir1  aichat
AICHAT_CONFIG_DIR=dir2  aichat
```
