### ISSUE TITLE
Playground for agents

### ISSUE THREAD

**Issue by ifokeev** [sigoden/aichat#938]
**Is your feature request related to a problem? Please describe.**
Playground doesn't respect the agent's config

**Describe the solution you'd like**
I'd like to work with agents through the Playground UI and API. Currently, agents are supported by the CLI, but there is no endpoint to call agents within the REST API. It would be cool to also support the session.

**Comment by sigoden** [comment]
see https://github.com/sigoden/aichat/issues/875#issuecomment-2364739690
