### ISSUE TITLE
-f does not support PDFs

### ISSUE THREAD

**Issue by JamesSullivan** [sigoden/aichat#944]
-f does not support PDFs

I believe a similar request was closed at the end of last year because the LLM APIs did not support this, but since that time a number of the models do now support binary PDFs, such as Gemini. The files need to be sent as binary (not text only) to preserve formatting and context as many PDFs contain tables and images which are removed by sending text only.

**Comment by sigoden** [comment]
AIChat doesn't send non-text files (such as pdf/xls files) to the API directly, even if some platforms support it. 

AIChat will not support it before most platforms supported it.

**Comment by 0xdapper** [comment]
Is PDF support wide enough to consider supporting it natively yet?

**Comment by captalphabet** [comment]
You can define a document loader in config.yaml and specify the file type.
Refer to the example config yaml file
