### ISSUE TITLE
LLM based auto-naming for sessions

### ISSUE THREAD

**Issue by jeanlucthumm** [sigoden/aichat#947]
**Is your feature request related to a problem? Please describe.**

It's difficult to come up with session names, especially when you already have a ton of sessions.

**Describe the solution you'd like**

When saving a session, use a call to a small LLM with the contents of the session to generate an appropriate session name. This is a feature in many other LLM interfaces.

**Describe alternatives you've considered**

Could not find a good way to do this right now.

**Additional context**

Maybe related issues:

https://github.com/sigoden/aichat/issues/805
https://github.com/sigoden/aichat/issues/696

One problem is that session names will definitely have spaces and be human readable rather than machine readable. But I guess as long as it's a valid file path it should be fine.

**Comment by jeanlucthumm** [comment]
Also, I would be willing to help with implementation if you decide to do this

**Comment by jeanlucthumm** [comment]
Sorry, what do you mean by "...but also functions similarly to the advanced role."?

Also, in your usage of AIChat, do you not end up with a significant amount of sessions to the point it becomes unmanageable? Is there a workflow that I'm missing? This is the underlying problem for why I opened this ticket

**Comment by sigoden** [comment]
Many people don’t saving session.

Those who do care about saving chat history in session, can address it via #805, or don't mind coming up with a appropriate name. 

AIChat is a REPL, unlike other UIs, not good at listing the session names and displaying the session details in one interface.

Auto-naming for sessions in AIChat is not as valuable as you think.

We don't plan on supporting it any time soon.
