### ISSUE TITLE
Completion is messy

### ISSUE THREAD

**Issue by Barrey** [sigoden/aichat#949]
**Describe the bug**

when i type using role, it is hard to type smoothly. sometimes weird character appeared, i think relate to completion. tried to disable completion but couldn't find it.

**To Reproduce**

aider .role grammar-genie (use role example)

**Expected behavior**

Smoothly typing anything inside prompt (with role)

**Screenshots/Logs**

<img width="378" alt="Screenshot 2024-10-23 at 20 26 09" src="https://github.com/user-attachments/assets/9beb8248-ea37-42e5-812c-657c61d0f7a4">

**Configuration**

```
model                   gemini:gemini-1.5-pro-latest
max_output_tokens       -
temperature             -
top_p                   -
dry_run                 false
stream                  true
save                    false
keybindings             emacs
wrap                    no
wrap_code               false
function_calling        true
use_tools               -
agent_prelude           -
save_session            -
compress_threshold      4000
rag_reranker_model      -
rag_top_k               4
highlight               true
light_theme             false
```

**Environment (please complete the following information):**
- os version: M1 Pro with Sequoia 15.0.1
- aichat version: 0.22.0
- terminal version: iTerm2 Build 3.5.5

**Additional context**

**Comment by sigoden** [comment]
Cannot confirm the problem. 

The REPL framework (reedline) used in aichat is quite mature, so it's unlikely that such a problem would occur. I suggest you investigate other issues.
