### ISSUE TITLE
[Feature request]better support for pasting multi-line content from some terminal emulators

### ISSUE THREAD

**Issue by milanglacier** [sigoden/aichat#95]
In some special terminals (like the embedded terminals in neovim and the libvterm in emacs), when pasting contents of multi lines, the multi lines will be concated into a single line.

Step to reproduce:

In macOS 12.6, using iterm2 (or wezterm, kitty, or alacritty), open `nvim` (neovim 0.8.3 installed from homebrew)

```bash
nvim
```

in neovim, type `:terminal` to open an embedded terminal.

copy the following multi-line content (using Command+c):

```
hello world

hello world

hello world
```

in the embedded terminal opened by neovim,  type `aichat` to enter `aichat`, type `{` to enter multiline mode, type `command+v` to paste the contents, will see the result:

<img width="1440" alt="Screen Shot 2023-03-23 at 02 39 41" src="https://user-images.githubusercontent.com/45728125/227123507-e5454a46-5e59-4ef1-83dc-cc3ebadc79e9.png">

The multi-line content is concated into a single line.

However, if I try to paste the content (type `command+v`) within the shell (bash or zsh) embedded in neovim, then it can be split into multi-line successfully:

<img width="1439" alt="Screen Shot 2023-03-23 at 03 00 21" src="https://user-images.githubusercontent.com/45728125/227127413-3178bef1-bae6-4199-b3f8-a28a3aca3a18.png">

My random guess is that maybe it is related to how `aichat` handles `\n` character when received from a text stream?

**Comment by milanglacier** [comment]
> Only iterm2 and nvim has this problem.
> 
> I have tested it with iterm2 and vim, no problem found.
> 
> This is really strange.

vim + kitty or vim + wezterm can reproduce.

Or iterm2 (and wezterm, kitty) + neovim

**Comment by h0tw4t3r** [comment]
@milanglacier, iTerm2 + nvim, but handled `aichat` outside nvim environment. Works well with `()` curly brackets.

**Comment by milanglacier** [comment]
> @milanglacier, iTerm2 + nvim, but handled `aichat` outside nvim environment. Works well with `()` curly brackets.

Thanks for your advice. But I prefer using the builtin terminal of neovim because I can manipulate the text output from the terminal using my familiar neovim commands and functions. And I can switch between my normal buffer and aichat buffer easily just within neovim. With a separate terminal session, it is not easy to do that.

Plus, it is not just embedded neovim terminal has such issue. The same issue applied for libvterm for emacs, and wezterm/kitty + vim.

**Comment by milanglacier** [comment]
I have the following snippet for a REPL plugin named iron.nvim which basically just append a `\r` character to the end of each line before sending the visually selected lines to the REPL, and then the magic happens, the multi-line content will not be concated into single line.

Not really understand what happens here, but maybe it is related to how MS and Unix handle newline differently? (windows uses `\r\n` while unix uses `\n`?)

https://github.com/hkupty/iron.nvim/blob/aa7aecc4410d475a62efff54896bd021501338f0/lua/iron/fts/markdown.lua#L12
