### ISSUE TITLE
How to add more documents to an existing AIChat RAG database?

### ISSUE THREAD

**Issue by Gerkinfeltser** [sigoden/aichat#950]
I'm trying to use AIChat's RAG (Retrieval Augmented Generation) feature. The documentation clearly explains how to initialize a new RAG database, but I haven't found any information on how to add more documents to an existing database.

**The problem:**
I have a working RAG database set up, but I'm unsure how to append new documents without recreating the database.

**Configuration**
```
model                   openrouter:microsoft/phi-3.5-mini-128k-instruct
max_output_tokens       -
temperature             -
top_p                   -
dry_run                 false
stream                  true
save                    false
keybindings             emacs
wrap                    no
wrap_code               false
function_calling        true
use_tools               -
agent_prelude           -
save_session            -
compress_threshold      4000
rag_reranker_model      -
rag_top_k               4
highlight               true
light_theme             false
env_file                C:\Users\XXXXX\AppData\Roaming\aichat\.env
config_file             C:\Users\XXXXX\AppData\Roaming\aichat\config.yaml
roles_dir               C:\Users\XXXXX\AppData\Roaming\aichat\roles
sessions_dir            C:\Users\XXXXX\AppData\Roaming\aichat\sessions
rags_dir                C:\Users\XXXXX\AppData\Roaming\aichat\rags
functions_dir           C:\Users\XXXXX\AppData\Roaming\aichat\functions
messages_file           C:\Users\XXXXX\AppData\Roaming\aichat\messages.md
```

**Environment:**
```
- os version: Windows 10
- aichat version: aichat 0.22.0
- terminal version: Windows PowerShell 5.1.19041.5007
```

**Comment by jeanlucthumm** [comment]
You might be able to change the condition at the top of the `yaml` file for the database and the do `.rebuild rag`, but I haven't tested this

**Comment by Gerkinfeltser** [comment]
Thank you @jeanlucthumm! I think you're right, it seems in the `aichat-rag.mp4` video that's just what is explained after creating a rag of the aichat-wiki.

**Comment by Gerkinfeltser** [comment]
Unfortunately, after further testing, while `.rebuild` works in some situations (which I'll outline below), it doesn't resolve the issue when appending new files sourced directly or adding new URLs. My current workaround involves setting the initial source(s) of the RAG to a directory (including subdirectories) and then rebuilding when new items are added. As mentioned, this method only works for local files within that directory structure, so URLs still cannot be appended.

That said, this is a step in the right direction!  
(& thanks again for the suggestion, @jeanlucthumm.)

**Comment by sigoden** [comment]
Each rag is an independent knowledge base. We do not encourage users to add or delete documents within it. Therefore, we do not provide the functionality to add or delete RAG documents.

For local files, it is recommended to place them in a single directory and then create the RAG from that directory. You can later update the files in that directory and use `.rebuild rag` to indirectly update the documents in the knowledge base.

For remote urls, it is recommended to create the RAG from website (`<url>/**`).  `.rebuild rag` will re-crawl the website and update the knowledge base.

Otherwise, you can only recreate the RAG.

**Comment by MMesch** [comment]
> Each rag is an independent knowledge base.

I think this is quite limiting and composable knowledge would be very interesting. It'd be great if you could combine knowledge (e.g. from two websites) as you need for the specific use case at hand. 

For example, I'm sometimes starting to explore a subject with a single URL but then realize that additional context from another URL would be helpful. It'd be great to be able to add that, ideally without re-embedding everything.
