### ISSUE TITLE
Ability to save/export an Arena conversation as an aichat session

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#951]
**Is your feature request related to a problem? Please describe.**

Be able to export a meaningful conversation from an arena conversation.

**Describe the solution you'd like**

As the Arena webui might have several conversations (columns), a solution that seems simple and intuitive would be to add a 💾 ("export") button in the prompt input. Clicking on it will generate the session file and prompt the user with a download dialog to save it to their local filesystem (browser feature).

**Comment by dtrckd** [comment]
Hop, actually the prompt input is common to all conversation (columns). So a possible option to placing the 💾 "export" button would be next to (left) the dropdown button to select models.

**Comment by sigoden** [comment]
The principle of playground/arena is to be sufficient. I generally tend to reject non-essential functions in webui.
