### ISSUE TITLE
Issue: Specify Shell Execution for Aichat on Windows

### ISSUE THREAD

**Issue by soulwax** [sigoden/aichat#953]
**Description**: Is there a way to configure Aichat to always execute commands within a specific shell on Windows (e.g., PowerShell, Command Prompt, etc.)?

**Current Behavior**: When executing a command with Aichat, it defaults to using cmd.exe as the shell, as shown in the example below:

```ps
Command:
aichat --execute echo "the type of shell you are running on right now"

Output:
echo %COMSPEC%
> execute | revise | describe | copy | quit: e

Upon executing:
C:\Windows\system32\cmd.exe
```

This default behavior leads to issues when running commands that are intended for other shells. For instance:

```ps
Command:
aichat --execute "search the current path for TypeScript files and list them." (PowerShell command)

Intended Command:
Get-ChildItem -Path . -Filter "*.ts" -Recurse -File | Select-Object FullName

Result:
The command "Get-ChildItem" is either misspelled or could not be found.
```

**Desired Behavior**: It would be beneficial if there was an option to specify the shell Aichat should use when executing commands (e.g., `powershell`, `bash`, or `cmd`). This would prevent compatibility issues and ensure commands are interpreted correctly.

**Suggested Solution**: Introduce a flag or configuration option to set the default shell for Aichat on Windows, allowing commands to execute in the desired environment without requiring manual adjustments.

I understand this may be less of an issue on macOS or linux, but even there, it can make a difference to specify your shell: bash, zsh, fish etc.

**Comment by sigoden** [comment]
![image](https://github.com/user-attachments/assets/3ec55857-9076-42e9-a35a-1036dc8a1faf)
