### ISSUE TITLE
Missing ".exit role" command completion in REPL mode

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#955]
**Describe the bug**

When  using a role in the REPL mode. the `.exit role` is not suggested in the auto-completion.

**To Reproduce**
Set a a role in aichat repl with `.role <my-role>`. Then Enter `.exit` and tabulate. 

**Expected behavior**
the command `.exit role` should be suggested and unset the current role.

**Environment (please complete the following information):**
- os version: Debian 6.10.11-1
- aichat version: 0.23.0
- terminal version: kitty 0.35.2

![image](https://github.com/user-attachments/assets/b52c4671-e43f-42fe-aa0e-18a3fa673143)

**Comment by dtrckd** [comment]
Actually, it seems that “.info role” is not suggested either when tabulating on ".info"...

**Comment by sigoden** [comment]
This is normal in a session; not having these role-specific completions isn't a problem either.

**Comment by dtrckd** [comment]
Why ? We always use role in session...This seems odd to not being able to see the ".info role" currently used or being able to ".exit role".

**Comment by sigoden** [comment]
The `.info role` and `.exit role` REPL commands only work for role, other than session role.

Case A:
```
> .role %code%
%code%> .session
temp/%code%)   
```

Case B:
```
> .session
> .role %code%
temp/%code%)  
```

`Case A` has  the completions for  the`.info role` and `.exit role` REPL commands,  while `Case B` does not.

**Comment by dtrckd** [comment]
Many thanks for that PR.
By the way @sigoden I am not sure if you noticed, but there was a related issue here : once a role was set in a session, we cannot exit it anymore

![image](https://github.com/user-attachments/assets/e2a47729-ffdd-4980-8a8c-05a6e6774f88)

Maybe your PR fixed it, I don"t know. Please let me know you prefer I open a specific issue for it.

**Comment by sigoden** [comment]
@dtrckd solved in #958

**Comment by milanglacier** [comment]
What is the actual things behind when you exit a role while in a session?

suppose your role `A` defines a system prompt. When you type `.exit role`, then the next LLM chat completion request will not contain the system prompt defined by role `A`?

**Comment by sigoden** [comment]
`.exit role` does not affect existing messages (chat history).  It only affects newly generated messages (`.empty session`).

https://github.com/sigoden/aichat/blob/0fc967ea3c7f52924165d1d3452f793d15cb9a0f/src/config/session.rs#L257-L260

**Comment by sigoden** [comment]
To avoid users having such concerns, I have restricted the use of `.exit role` to only empty session (#963)

**Comment by dtrckd** [comment]
But is it still possible to change the role in a non empty session by using `.role another-role` ?
 
I think its a very useful feature to be able to do that. It is like, during a conversation, saying, "ok, we said a lot of interesting thing, but we are now going round in circles, let's talk about this from another perspective...".
Or yet, being able to switch to predefined model configuration within a session.

I would also like to be able "exit" role, to me no role, is like another role...

Maybe to avoid the confusion, while not restricting the user and keep your convention, an idea will be to a have a ".empty role"...

**Comment by sigoden** [comment]
No, you can't change the role in a non empty session.

![image](https://github.com/user-attachments/assets/5981b065-5e04-402e-92d3-776952e6a186)
