### ISSUE TITLE
RAG with many documents

### ISSUE THREAD

**Issue by cmartinez-biohpc** [sigoden/aichat#959]
I have created a rag with thousands of CSV files. My goal is to get global information about all of them, but the answers only refer to three or four of them.
I am using Ollama3.1 and Ollama:nomic-embed-text.

**Comment by dtrckd** [comment]
RAG is designed to use the N most relevant documents of a collection to give a contexte to a LLM.
Your case falls within the scope of **document summarization** which cannot be done with a simple RAG alone.
