### ISSUE TITLE
Error on first run (and all subsequent runs)

### ISSUE THREAD

**Issue by mathomp4** [sigoden/aichat#96]
So I just learned about `aichat` and decided to try it out. I launched `aichat` for the first time and:
```
❯ aichat
> No config file, create a new one? Yes
> Openai API Key: sk_lots_of_letters_and_numbers
> Use proxy? No
> Save chat messages Yes
Error: Failed to build http client

Caused by:
    0: builder error: The Trust Settings Record was corrupted.
    1: The Trust Settings Record was corrupted.
```
And then after that:
```
❯ aichat
Error: Failed to build http client

Caused by:
    0: builder error: The Trust Settings Record was corrupted.
    1: The Trust Settings Record was corrupted.
```

I'm sort of impressed I broke it right out of the gate. 😄 

Help please?

**Comment by sigoden** [comment]
Check your system for corrupt certificates:
```
security dump-trust-settings -d
```
Went into the Keychain Access app, manually delete corrupt certificates.

**Comment by mathomp4** [comment]
@sigoden Ahhh. It took a while, but I figured it out thanks. I could *not* get the `security delete-certificate -c` to work (it would never match a string), but once I figured out how to display expired certs in Keychain Access, I was able to remove them!
