### ISSUE TITLE
Support for RPM based systems

### ISSUE THREAD

**Issue by MartenBE** [sigoden/aichat#960]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

I would like to be able to install aichat on Fedora in a way that it will also be updated when the system is updated like https://github.com/charmbracelet/mods .

**Describe alternatives you've considered**

Ideally this could be done in multiple ways:
- Add it to the official Fedora packages
- Let users install it using a repo file (This is what https://github.com/charmbracelet/mods does)
- Create a COPR repo

**Comment by sigoden** [comment]
The Aichat release follows Rust conventions, and we don't see a need for adjustments.

Download the corresponding release file based on the current system and CPU architecture, and extracting it will give you the aichat executable file. This is already simple enough.

Of course, we also welcome the package management repository to include aichat and are willing to provide any assistance for this.
