### ISSUE TITLE
planed? support sqlite/vec, already exist as external RAG. 

### ISSUE THREAD

**Issue by PorcoRosso85** [sigoden/aichat#961]
Already supported? If not yet, please Consider below.

**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
Supporting sqlite file in addition to exsiting option: file, dir and name filtering.

**Describe alternatives you've considered**
-

**Additional context**

I've imagined the command like this:
`> Add documents: /tmp/dir1/file1.sqlite;/tmp/dir1/file2.sqlite -c 'SELECT * FROM ... ` 

P.S.
sqlite-vec sponsered by mozilla
https://github.com/asg017/sqlite-vec

**Comment by sigoden** [comment]
We will not support this feature, because the current file storage RAG works well.
