### ISSUE TITLE
[Feature request] Add ability to set maximum line width

### ISSUE THREAD

**Issue by asb** [sigoden/aichat#97]
Currently, text will be wrapped at the width of the terminal window. Ideally I could set a maximum width (and even better if this maximum width was ignored for fenced code blocks).

**Comment by sigoden** [comment]
Do you mean no-wrap and horizontal scrolling?

Normal text wrapping is more appropriate.
And the fenced code blocks replied by gpt are usually not very wide.

Given this, I'm not going to add this feature.

**Comment by asb** [comment]
No, I meant setting a maximum width of e.g. 80, or 120 characters and having the text wrapped at that width, even if the terminal window is wider.

**Comment by sigoden** [comment]
This introduce a problem: text copied to from terminal selection may be broken.


For example.

```js
let text = "Lorem ipsum dolor sit amet. Morbi et lobortis nisi, at ullamcorper sem. Vestibulum semper diam nec nulla
tempor dictum. Sed vitae placerat tortor. In ut convallis sapien. Fusce non scelerisque sapien. "
```
In order to meet the max-width limit, Aichat may insert line break: `nulla tempor` => `nulla\n tempor`.

If we copy  this text and run

![image](https://user-images.githubusercontent.com/4012553/227811439-0fa18c1c-99e4-48f3-840d-4b438c3a764f.png)

**Comment by sigoden** [comment]
Technically, a vim-like tui application takes over the terminal, which handles the copying itself. This way you can copy the original text from the selected text.
Aichat uses readline, and copy section is a built-in function of the terminal, which can only copy the text output by Aichat as it is.
So you only copy corrupted text.

**Comment by sigoden** [comment]
With this in mind, max-width can do more harm than good.

text-wrap of #99  is the same

**Comment by asb** [comment]
> So you only copy corrupted text.

That was the motivation for suggesting not to wrap code blocks. Code blocks remain easily copyable, but paragraphs of explanation are more readable. This very roughly approximates the rendering within a browser.
