### ISSUE TITLE
Aichat use GPT provided by DuckDuckGo's free AI Chat service.

### ISSUE THREAD

**Issue by irav2** [sigoden/aichat#976]
I've written GPT in the title just because it would be silly to mention all four of the available options in the title. DuckDuckGo provides a free service where they allow you to use GPT-4o-mini and Claude as well as Llama and Mixtral which I am assuming run locally on their servers through their web interface. duck.ai redirects you to the service. Would it be possible to use GPT via this service, or Llama as I find that to be the best actually, GPT comes in second. This blog post explains how to get their API key or something (https://blek.codes/blog/duckduckgo-ai-chat/), and there are also a couple of programs that allow you to access it from the command line (https://git.blek.codes/blek/hey), but I want the power of aichat. Is there a way I can configure this to work, I don't know much about web stuff and networking stuff and also programming, so I just wanted to see if this is possible, is it?

**Comment by sigoden** [comment]
DuckDuckGo does not officially provide a chat API. You can try it yourself, but the Aichat community cannot provide you with any help.

**Comment by irav2** [comment]
In #390 one of the community members explained how to use Aichat with OpenAI's free no-login GPT-3.5 service, in which they didn't provide an API. I am new to GitHub and similar stuff, I think using Aichat with DuckDuckGO's free service would be the most private way to use it, is there a way I can open a TODO enhancement kind of thing for the community members to solve if they can?
