### ISSUE TITLE
[Feature request] File mode (e.g. aichat -r comment -f somefile.ts)

### ISSUE THREAD

**Issue by olalonde** [sigoden/aichat#98]
It would be nice to have an inline file mode that allows using the content of a file as the aichat input and writing back the output to the file.

It would allow this kind of use case for adding code comments to a file.

```console
aichat -r comment -f somefile.ts 
```

Or fixing grammar:

```console
aichat -r grammar -f README.md
```

etc.

If you approve, I can try writing a PR.

Temporary bash workaround (generated by ChatGPT :P):

```bash
#!/bin/bash

# Check if there are enough arguments
if [ "$#" -lt 2 ]; then
    echo "Usage: $0 <aichat_options> <filename>"
    exit 1
fi

# Store the last argument (filename) and remove it from the argument list
FILENAME="${!#}"
shopt -u nocasematch
set -- "${@:1:$#-1}"

# Check if the file exists
if [ ! -f "$FILENAME" ]; then
    echo "Error: File '$FILENAME' not found"
    exit 1
fi

# Create a temporary file in the OS temporary directory
TMPFILE=$(mktemp)

echo "$FILENAME"
echo "${@}"

# Pass all the arguments except the last one to the aichat command
aichat "${@}" < "$FILENAME" > "$TMPFILE"

# Move the temporary file to the original file
mv "$TMPFILE" "$FILENAME"
```

**Comment by sigoden** [comment]
No, I don't like this feature. it's too tricky.

Use `sponge` to replace text directly on file (like sed -i)
```
cat README.md | aichat -r grammar | sponge README.md
```

**Comment by olalonde** [comment]
> I would not consider this feature. this is too specialized
> 
> [`sponge`](https://linux.die.net/man/1/sponge) is designed to handle this situation
> 
> ```
> cat README.md | aichat -r grammar | sponge README.md
> ```

There's some disadvantages to that method though, like having to type the filename twice or possibly getting a partial output if there's an error during execution. Also doesn't play well with globbing, e.g.:

```console
aichat -r refactor -f *.rs
```

I don't think it's that specialized, actually the majority of CLI tools i can think of take file paths as arguments. `cat`, `grep`, `less`, `tail`, `head`, `wc`, `sort` , `uniq`, `shasum`, etc.
