### ISSUE TITLE
feat: add AI-powered git commit message generation command

### ISSUE THREAD

**Issue by tallesborges** [sigoden/aichat#984]
**Is your feature request related to a problem? Please describe.**
When making git commits, it's often time-consuming to write meaningful commit messages that accurately describe the changes. Currently, I have to manually analyze my changes and compose an appropriate commit message, which can break my workflow.

**Describe the solution you'd like**
I'd like to add a `commit` command that would:
1. Automatically analyze the git diff of staged changes
2. Use AI to generate a concise and descriptive commit message
3. Execute the git commit command with the generated message

Example usage:
```bash
aichat commit
# or
aichat commit --preview  # to review the message before committing

**Comment by sigoden** [comment]
We will not support this feature, AI git commit is a niche demand.

Maybe you can try using llm-functions to implement this feature.
