### ISSUE TITLE
Response text before function calls is not added to session

### ISSUE THREAD

**Issue by eighteyes** [sigoden/aichat#992]
dug into this behavior a little more and found how to reproduce the bug. if a function is called ( dark grey `Call <agent> <function> {payload}` ) all the response text prior to the function call is not added to the session. 

I don't have a clear reproduction case because functions are called at the beginning, middle and end of a response. 

thank you for resolving this, i was wondering why my agents had such terrible memory.

**Comment by sigoden** [comment]
This is expected behavior. 


What's important is the result of the function calls; the text surrounding the function call is not important, it is only used by LLM to explain why and how the function was called.

Most LLMs do not have such thinking texts.

```
$ aichat -s t3 --save-session -r '%functions%' get weathers in london and berlin
Call get_current_weather {"location":"London"}
Call get_current_weather {"location":"Berlin"}
The current weather is as follows:

### London
- Condition: ⛅️
- Temperature: +8°C
- Wind Speed: 2.8 m/s

### Berlin
- Condition: 🌦️
- Temperature: +4°C
- Wind Speed: 1.9 m/s
```

```
model: openai:gpt-4o-mini
use_tools: all
role_name: '%functions%'
messages:
- role: user
  content: get weathers in london and berlin
- role: assistant
  content: |-
    The current weather is as follows:

    ### London
    - Condition: ⛅️
    - Temperature: +8°C
    - Wind Speed: 2.8 m/s

    ### Berlin
    - Condition: 🌦️
    - Temperature: +4°C
    - Wind Speed: 1.9 m/s

```

**Comment by eighteyes** [comment]
Would you consider a flag for this as an option? i have a fairly complex use case for an assistant agent, and they lose the thread too often.

**Comment by sigoden** [comment]
Sorry, we won't save such texts because they are really unnecessary.

Most LLM generated function callings do not come with text. The only common one that includes text is Claude, but it only provides some thinking.

```
$ aichat -m claude:claude-3-5-haiku-latest  -s t3 --save-session -r '%functions%' get weathers in london and berlin
I'll retrieve the current weather for both London and Berlin using the get_current_weather function.
Call get_current_weather {"location":"London"}
Call get_current_weather {"location":"Berlin"}


Here are the current weather conditions:

### London
- Condition: ⛅️ Partly Cloudy
- Temperature: +8°C
- Wind Speed: 2.8 m/s (Downward)

### Berlin
- Condition: 🌦️ Light Rain
- Temperature: +4°C
- Wind Speed: 1.9 m/s (Horizontal)

The weather shows a slightly cooler and rainy condition in Berlin compared to the partly cloudy and milder weather in London.
```

**Comment by eighteyes** [comment]
Oh crazy, you are spot on, I'm using Claude and I am triggering functions with thinking. 

If I did a PR to fix my own problem would you merge it? If you agreed with the implementation of course...

**Comment by sigoden** [comment]
Sorry, we will reject the PR. 

We insist that the response text before function calling has no value for persistence.

**Comment by sigoden** [comment]
I would like to apologize first.

The session not only skiped to save the response text before function calls, but it also did not save the function calls.

Maybe that's why you feel like "you lose the thread too often."

PR #994 change this behavior to allow the session to save details of function calls (including text).

**Comment by eighteyes** [comment]
!!! thank you kind sir. i am glad to have done my part to help make aichat the best llm interface out there ( > GUI )
