### ISSUE TITLE
Ability to insert commands generated through `aichat -e` into the command line

### ISSUE THREAD

**Issue by taha-yassine** [sigoden/aichat#996]
**Is your feature request related to a problem? Please describe.**

I sometimes want to generate a generic command with placeholders that I would manually edit. I think it would generally be a good thing to have the ability to tweak the command before executing it. It would be specially useful if one wants to use sensitive data (eg API key) that they don't want to communicate to model providers. 

**Describe the solution you'd like**

Add the ability to insert commands generated through `aichat -e` into the command line. As mentioned here https://github.com/sigoden/aichat/issues/724#issuecomment-2241088320, this is something other CLI tools can do, so it's theoretically possible.

**Describe alternatives you've considered**

What I currently do is just copy the generated command and manually past and edit it, but this isn't ideal.

**Comment by sigoden** [comment]
see https://github.com/sigoden/aichat/wiki/Command-Line-Guide#shell-integration

**Comment by taha-yassine** [comment]
> see https://github.com/sigoden/aichat/wiki/Command-Line-Guide#shell-integration

Thanks! This script is cool and close to the feature I described, but we lose the ability to revise and describe the generated command which is very useful. I think having an option "insert" when calling `aichat -e` would be ideal and complimentary to the script you shared.

**Comment by sigoden** [comment]
Such functionality cannot be achieved in `aichat -e`; it must be implemented in a shell script. The external command has no way to modify the text input in the current shell.

If you still need to `revise`/`describe`, please patch the shell integration script yourself. Good luck!
