### ISSUE TITLE
Integrate MemoriPy for better memory management.

### ISSUE THREAD

**Issue by hackdefendr** [sigoden/aichat#999]
**Is your feature request related to a problem? Please describe.**
After say for example 30 minutes of conversation with any LLM. The conversations with hallucination starts to become a real issue. Thankfully aichat has the empty session command that clears history. But what if you didn't have to do that any more?

**Describe the solution you'd like**
See if this new library can be integrated with aichat for better memory management.
[MemoriPy](https://github.com/caspianmoon/memoripy)

**Describe alternatives you've considered**
This repo is only a week old. No other alternatives exist AFAIK.

**Additional context**
I use aichat on the daily.

**Comment by sigoden** [comment]
We will not support this features.

Currently, LLM memory is not popular, and its value has not yet been proven. At least for well-known applications like open-webui, it is still not supported.


Aichat provides session compression for lengthy conversations. When there's one topic per session, it should work quite effectively.

**Comment by hackdefendr** [comment]
“When there's one topic per session, it should work quite effectively.”

 

This is a false statement. I use aichat every single day and I’m telling you straight. You get about 30 minutes of conversation with any model and it starts drifting off and printing clear errors. So if you won’t support it, I just assume you think you know better. Or maybe its because you are afraid to try. Since aichat is open source, I will just fork it and re-release it with proper memory management myself.

 

From: sigoden ***@***.***>
Reply-To: sigoden/aichat ***@***.***>
Date: Sunday, November 17, 2024 at 5:03 PM
To: sigoden/aichat ***@***.***>
Cc: HackDefendr ***@***.***>, Author ***@***.***>
Subject: Re: [sigoden/aichat] Integrate MemoriPy for better memory management. (Issue #999)

 

We will not support this feature.

Currently, LLM memory is not popular, and its value has not yet been proven. At least for well-known applications like open-webui, it is still not supported.

AIChat provides session compression for lengthy conversations. When there's one topic per session, it should work quite effectively.

**Comment by dtrckd** [comment]
I like the idea but I also think also that it feels quiet experimental.
But using the auto-summarization feature with a decent max conversation length might help with hallucinations ?
